# Generated by Django 3.0.8 on 2024-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_SweetPOSRoleAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Division', models.IntegerField()),
                ('IsAddNewItem', models.BooleanField(default=False)),
                ('IsImportItems', models.BooleanField(default=False)),
                ('IsImportGroups', models.BooleanField(default=False)),
                ('IsUpdateItem', models.BooleanField(default=False)),
                ('IsCItemId', models.BooleanField(default=False)),
                ('IsItemName', models.BooleanField(default=False)),
                ('IsSalesModify', models.BooleanField(default=False)),
                ('IsSalesDelete', models.BooleanField(default=False)),
                ('IsUnitModify', models.BooleanField(default=False)),
                ('IsShowVoucherButton', models.BooleanField(default=False)),
                ('IsGiveSweetPOSUpdate', models.BooleanField(default=False)),
                ('IsSweetPOSAutoUpdate', models.BooleanField(default=False)),
                ('IsSweetPOSServiceAutoUpdate', models.BooleanField(default=False)),
                ('IsEayBillUploadExist', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'M_SweetPOSRoleAccess',
            },
        ),
    ]
