# Generated by Django 4.2.6 on 2024-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_SweetPOSLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('DivisionID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('MacID', models.IntegerField()),
                ('ExePath', models.CharField(max_length=200)),
                ('ExeVersion', models.CharField(max_length=30)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_SweetPOSLogin',
            },
        ),
        
    ]
