# Generated by Django 3.0.8 on 2024-02-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0003_auto_20240214_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_sweetposlogin',
            old_name='UName',
            new_name='UserName',
        ),
        migrations.AlterField(
            model_name='m_sweetposlogin',
            name='MacID',
            field=models.CharField(max_length=200),
        ),
    ]
