# Generated by Django 3.0.8 on 2024-02-14 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0004_auto_20240214_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_sweetposroleaccess',
            old_name='IsEayBillUploadExist',
            new_name='IsEWayBillUploadExist',
        ),
        migrations.AddField(
            model_name='m_sweetposroleaccess',
            name='LicenseValidTill',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_sweetposroleaccess',
            name='Party',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_sweetposroleaccess',
            name='Query',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='m_sweetposroleaccess',
            name='TopRows',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_sweetposroleaccess',
            name='TouchSaleHistoryRows',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
