# Generated by Django 3.0.8 on 2024-02-15 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0005_auto_20240214_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_sweetposroleaccess',
            old_name='Division',
            new_name='DivisionID',
        ),
        migrations.AddField(
            model_name='m_sweetposroleaccess',
            name='DivName',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
