# Generated by Django 3.0.8 on 2024-02-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0006_auto_20240215_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_SPOSInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaleID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('ClientSaleID', models.IntegerField()),
                ('InvoiceDate', models.DateField()),
                ('InvoiceNumber', models.IntegerField()),
                ('FullInvoiceNumber', models.CharField(max_length=500)),
                ('GrandTotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('RoundOffAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Customer', models.IntegerField()),
                ('Driver', models.IntegerField()),
                ('Party', models.IntegerField()),
                ('Vehicle', models.IntegerField()),
                ('TCSAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DiscountPercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('DiscountAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Hide', models.BooleanField(default=False)),
                ('ImportFromExcel', models.BooleanField(default=False)),
                ('DeletedFromSAP', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'T_SPOSInvoices',
            },
        ),
        migrations.CreateModel(
            name='TC_SPOSInvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaleItemID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('ClientSaleItemID', models.IntegerField()),
                ('ClientSaleID', models.IntegerField()),
                ('ERPItemID', models.IntegerField()),
                ('POSItemID', models.IntegerField()),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('MRPValue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DiscountType', models.CharField(blank=True, max_length=500, null=True)),
                ('Discount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('DiscountAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.IntegerField()),
                ('Unit', models.IntegerField()),
                ('QtyInNo', models.DecimalField(decimal_places=20, max_digits=30)),
                ('QtyInKg', models.DecimalField(decimal_places=20, max_digits=30)),
                ('QtyInBox', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaleItems', to='SweetPOS.T_SPOSInvoices')),
            ],
            options={
                'db_table': 'TC_SPOSInvoiceItems',
            },
        ),
    ]
