# Generated by Django 3.0.8 on 2024-04-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0007_t_sposinvoices_tc_sposinvoiceitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_SweetPOSRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_SweetPOSRoles',
            },
        ),
        migrations.CreateModel(
            name='M_SweetPOSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyID', models.IntegerField()),
                ('DivisionID', models.IntegerField()),
                ('LoginName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('RoleID', models.IntegerField()),
                ('IsActive', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_SweetPOSUser',
            },
        ),
    ]
