# Generated by Django 3.0.8 on 2024-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0008_m_sweetposroles_m_sweetposuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='O_SPOSDateWiseLiveStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockDate', models.DateField()),
                ('Item', models.IntegerField()),
                ('OpeningBalance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('GRN', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Sale', models.DecimalField(decimal_places=10, max_digits=20)),
                ('PurchaseReturn', models.DecimalField(decimal_places=10, max_digits=20)),
                ('SalesReturn', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ClosingBalance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ActualStock', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Unit', models.IntegerField()),
                ('Party', models.IntegerField()),
                ('IsAdjusted', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('MRPValue', models.DecimalField(decimal_places=10, max_digits=20)),
                ('StockAdjustment', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
            options={
                'db_table': 'O_SPOSDateWiseLiveStock',
            },
        ),
        migrations.CreateModel(
            name='T_SPOSStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockDate', models.DateField()),
                ('Item', models.IntegerField()),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Unit', models.IntegerField()),
                ('MRP', models.IntegerField()),
                ('MRPValue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Party', models.IntegerField()),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('IsSaleable', models.BooleanField(default=False)),
                ('BatchCode', models.CharField(blank=True, max_length=500, null=True)),
                ('BatchCodeID', models.CharField(blank=True, max_length=500, null=True)),
                ('Difference', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('IsStockAdjustment', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'T_SPOSStock',
            },
        ),
        migrations.CreateModel(
            name='T_SPOSStockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockDate', models.DateField()),
                ('Item', models.IntegerField()),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Unit', models.IntegerField()),
                ('MRP', models.IntegerField()),
                ('MRPValue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Party', models.IntegerField()),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('IsSaleable', models.BooleanField(default=False)),
                ('BatchCode', models.CharField(blank=True, max_length=500, null=True)),
                ('BatchCodeID', models.CharField(blank=True, max_length=500, null=True)),
                ('Difference', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('IsStockAdjustment', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'T_SPOSStockOut',
            },
        ),
    ]
