# Generated by Django 3.0.8 on 2024-07-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0011_auto_20240626_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_SPOSInvoiceUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AckNo', models.CharField(max_length=500, null=True)),
                ('Irn', models.CharField(max_length=500, null=True)),
                ('QRCodeUrl', models.CharField(max_length=500, null=True)),
                ('EInvoicePdf', models.CharField(max_length=500, null=True)),
                ('EwayBillNo', models.CharField(max_length=500, null=True)),
                ('EwayBillUrl', models.CharField(max_length=500, null=True)),
                ('EInvoiceCreatedBy', models.IntegerField(null=True)),
                ('EInvoiceCreatedOn', models.DateTimeField(null=True)),
                ('EwayBillCreatedBy', models.IntegerField(null=True)),
                ('EwayBillCreatedOn', models.DateTimeField(null=True)),
                ('EInvoiceCanceledBy', models.IntegerField(null=True)),
                ('EInvoiceCanceledOn', models.DateTimeField(null=True)),
                ('EwayBillCanceledBy', models.IntegerField(null=True)),
                ('EwayBillCanceledOn', models.DateTimeField(null=True)),
                ('EInvoiceIsCancel', models.BooleanField(default=False)),
                ('EwayBillIsCancel', models.BooleanField(default=False)),
                ('user_gstin', models.CharField(max_length=500)),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SPOSInvoiceUploads', to='SweetPOS.T_SPOSInvoices')),
            ],
            options={
                'db_table': 'TC_SPOSInvoiceUploads',
            },
        ),
    ]
