# Generated by Django 3.0.8 on 2024-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0012_tc_sposinvoiceuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_sposinvoices',
            name='UploadedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
