# Generated by Django 3.0.8 on 2024-07-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0013_t_sposinvoices_uploadedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='UpdatedOn',
            field=models.DateTimeField(),
        ),
    ]
