# Generated by Django 3.0.8 on 2024-07-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0016_auto_20240704_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='Rate',
            field=models.DecimalField(decimal_places=20, max_digits=60),
        ),
    ]
