# Generated by Django 3.0.8 on 2024-07-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0017_auto_20240704_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='DiscountAmount',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='GrandTotal',
            field=models.DecimalField(decimal_places=20, max_digits=60),
        ),
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='NetAmount',
            field=models.DecimalField(decimal_places=20, max_digits=60),
        ),
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='RoundOffAmount',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=20, max_digits=60),
        ),
    ]
