# Generated by Django 3.0.8 on 2024-07-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0019_auto_20240704_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='MRPValue',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=60, null=True),
        ),
    ]
