# Generated by Django 3.0.8 on 2024-07-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0020_auto_20240705_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='Driver',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='Vehicle',
            field=models.IntegerField(null=True),
        ),
    ]
