# Generated by Django 3.0.8 on 2024-07-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0021_auto_20240706_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='GrandTotal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
