# Generated by Django 3.0.8 on 2024-07-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0023_auto_20240711_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='DiscountAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='NetAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='RoundOffAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='BaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='BasicAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='CGST',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='CGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='DiscountAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='GSTAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='IGST',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='IGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='MRPValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='SGST',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='SGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_sposinvoiceitems',
            name='TaxType',
            field=models.CharField(max_length=10),
        ),
    ]
