# Generated by Django 3.0.8 on 2024-07-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0025_auto_20240712_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
