# Generated by Django 3.0.8 on 2024-07-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0026_auto_20240712_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_SPOSDeletedInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeletedTableAutoID', models.IntegerField()),
                ('ClientID', models.IntegerField()),
                ('ClientSaleID', models.IntegerField()),
                ('InvoiceDate', models.DateField()),
                ('Party', models.IntegerField()),
                ('DeletedBy', models.IntegerField()),
                ('DeletedOn', models.DateTimeField(auto_now_add=True)),
                ('ReferenceInvoiceID', models.IntegerField()),
            ],
            options={
                'db_table': 'T_SPOSDeletedInvoices',
            },
        ),
    ]
