# Generated by Django 3.0.8 on 2024-07-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0027_t_sposdeletedinvoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sposdeletedinvoices',
            name='ReferenceInvoiceID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='t_sposinvoices',
            name='ReferenceInvoiceID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
