# Generated by Django 3.0.8 on 2024-07-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0030_auto_20240727_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_sweetposuser',
            name='POSRateType',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
