# Generated by Django 3.0.8 on 2024-08-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0031_auto_20240730_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sposdeletedinvoices',
            name='DeletedBy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
