# Generated by Django 3.0.8 on 2024-08-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0036_m_consumermobile_macid'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_SweetPOSMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party', models.IntegerField()),
                ('MacID', models.CharField(max_length=200)),
                ('MachineRole', models.IntegerField()),
                ('IsServer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'M_SweetPOSMachine',
            },
        ),
    ]
