# Generated by Django 3.0.8 on 2024-09-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0038_auto_20240919_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_sweetposmachine',
            old_name='MachineRole',
            new_name='MachineType',
        ),
        migrations.AlterField(
            model_name='m_sweetposmachine',
            name='MacID',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
