# Generated by Django 3.0.8 on 2024-10-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0040_auto_20240928_1213'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='m_consumermobile',
            constraint=models.UniqueConstraint(fields=('Mobile', 'MacID'), name='unique_Mobile_MacID'),
        ),
    ]
