# Generated by Django 3.0.8 on 2024-10-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0041_auto_20241001_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_sposinvoiceitems',
            name='IsMixItem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tc_sposinvoiceitems',
            name='MixItemId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
