# Generated by Django 3.0.8 on 2024-10-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0042_auto_20241002_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_sweetposmachine',
            name='MacID',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='m_sweetposmachine',
            constraint=models.UniqueConstraint(fields=('Party', 'MacID'), name='unique_Party_MacID'),
        ),
    ]
