# Generated by Django 3.0.8 on 2024-10-05 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0043_auto_20241003_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_consumermobile',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_consumermobile',
            name='Party',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
