# Generated by Django 3.0.8 on 2024-10-10 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0044_auto_20241005_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='IsAutoUpdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='IsGiveUpdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='IsService',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='MachineName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='ServerSequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='UploadSaleRecordCount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='Validity',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='Version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
