# Generated by Django 3.0.8 on 2024-10-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0046_auto_20241015_1113'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='m_consumermobile',
            name='unique_Mobile_MacID',
        ),
    ]
