# Generated by Django 3.0.8 on 2024-10-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0047_auto_20241015_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='ServerDatabase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='ServerHost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='ServerPassWord',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='ServerUser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='SeverName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
