# Generated by Django 3.0.8 on 2024-10-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0048_auto_20241016_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='Invoiceprefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
