# Generated by Django 3.0.8 on 2024-11-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0049_m_sweetposmachine_invoiceprefix'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='m_sweetposmachine',
            name='unique_Party_MacID',
        ),
        migrations.AddConstraint(
            model_name='m_sweetposmachine',
            constraint=models.UniqueConstraint(fields=('Party', 'MacID', 'SeverName', 'ServerHost', 'Invoiceprefix'), name='unique_Party_MacID_SeverName_ServerHost_Invoiceprefix'),
        ),
    ]
