# Generated by Django 3.0.8 on 2024-12-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0050_auto_20241126_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_sposinvoices',
            name='AdvanceAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
