# Generated by Django 3.0.8 on 2024-12-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0051_t_sposinvoices_advanceamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_SPOSInvoicesReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SPOSInvoicesReferences', to='SweetPOS.T_SPOSInvoices')),
            ],
            options={
                'db_table': 'TC_SPOSInvoicesReferences',
            },
        ),
    ]
