# Generated by Django 3.0.8 on 2024-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0052_tc_sposinvoicesreferences'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='m_sweetposmachine',
            name='unique_Party_MacID_SeverName_ServerHost_Invoiceprefix',
        ),
        migrations.AddConstraint(
            model_name='m_sweetposmachine',
            constraint=models.UniqueConstraint(fields=('Party', 'MacID'), name='unique_Party_MacID'),
        ),
    ]
