# Generated by Django 3.0.8 on 2024-12-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0055_m_servicesettingsimport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_servicesettings',
            name='UpdatedON',
        ),
        migrations.AddField(
            model_name='m_servicesettings',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
