# Generated by Django 3.0.8 on 2024-12-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0056_auto_20241206_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_sposinvoices',
            name='VoucherCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
