# Generated by Django 3.0.8 on 2025-02-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0057_t_sposinvoices_vouchercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_sposstockout',
            name='Quantity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
