# Generated by Django 3.0.8 on 2025-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0058_t_sposstockout_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sposstockout',
            name='Quantity',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
