# Generated by Django 3.0.8 on 2025-02-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0059_auto_20250213_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_sposstockout',
            name='Quantity',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
