# Generated by Django 3.0.8 on 2025-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0060_auto_20250213_1834'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['SaleID'], name='T_SPOSInvoi_SaleID_a00062_idx'),
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['ClientID'], name='T_SPOSInvoi_ClientI_b39332_idx'),
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['InvoiceNumber'], name='T_SPOSInvoi_Invoice_d212e4_idx'),
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['InvoiceDate'], name='T_SPOSInvoi_Invoice_5ecaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['Customer'], name='T_SPOSInvoi_Custome_7c9e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['Party'], name='T_SPOSInvoi_Party_d84261_idx'),
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['NetAmount'], name='T_SPOSInvoi_NetAmou_a70042_idx'),
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['CreatedBy'], name='T_SPOSInvoi_Created_827fac_idx'),
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['Party', 'InvoiceDate', 'IsDeleted'], name='T_SPOSInvoi_Party_a5b401_idx'),
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['Customer', 'InvoiceDate'], name='T_SPOSInvoi_Custome_bb909e_idx'),
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['ClientID', 'Party'], name='T_SPOSInvoi_ClientI_c197c5_idx'),
        ),
    ]
