# Generated by Django 3.0.8 on 2025-03-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0061_auto_20250225_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_InvoicesSchemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SPOSInvoicesScheme', to='SweetPOS.T_SPOSInvoices')),
            ],
            options={
                'db_table': 'TC_InvoicesSchemes',
            },
        ),
    ]
