# Generated by Django 3.0.8 on 2025-03-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0062_tc_invoicesschemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_invoicesschemes',
            name='scheme',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
