# Generated by Django 3.0.8 on 2025-04-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0063_tc_invoicesschemes_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_sposstock',
            name='ClientID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
