# Generated by Django 3.0.8 on 2025-04-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0064_t_sposstock_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_sweetposmachine',
            name='PrimaryUser',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
