# Generated by Django 3.0.8 on 2025-06-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0065_m_sweetposmachine_primaryuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_PosSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Setting_Key', models.CharField(max_length=255)),
                ('Setting_Value', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=400)),
                ('Setting_Type', models.BooleanField(default=False)),
                ('Is_Disabled', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_PosSettings',
            },
        ),
        migrations.CreateModel(
            name='MC_PosSettingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Setting_Value', models.CharField(max_length=255)),
                ('PartyId', models.IntegerField()),
                ('Is_Disabled', models.BooleanField(default=False)),
                ('PosSetting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PosSettingDetails', to='SweetPOS.M_PosSettings')),
            ],
            options={
                'db_table': 'MC_PosSettingDetails',
            },
        ),
    ]
