# Generated by Django 3.0.8 on 2025-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0066_m_possettings_mc_possettingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_PhonePeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('party_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('base_url', models.CharField(max_length=255)),
                ('merchant_id', models.BinaryField(max_length=255)),
                ('provider_id', models.BinaryField(max_length=255)),
                ('salt_key', models.BinaryField(max_length=255)),
                ('key_index', models.CharField(max_length=255)),
                ('store_id', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=255)),
                ('terminal_id', models.CharField(max_length=100)),
                ('merchant_name', models.CharField(max_length=255)),
                ('x_callback_url', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_PhonePeSettings',
            },
        ),
    ]
