# Generated by Django 3.0.8 on 2025-06-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0067_m_phonepesettings'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='t_sposinvoices',
            name='T_SPOSInvoi_NetAmou_a70042_idx',
        ),
        migrations.AddIndex(
            model_name='t_sposinvoices',
            index=models.Index(fields=['Party', 'InvoiceDate', 'FullInvoiceNumber'], name='T_SPOSInvoi_Party_b1c4e9_idx'),
        ),
    ]
