# Generated by Django 3.0.8 on 2025-06-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0068_auto_20250612_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_PaymentModes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Mode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'M_PaymentModes',
            },
        ),
        migrations.CreateModel(
            name='MC_PaymentModeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartyId', models.IntegerField()),
                ('Paymentmodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweetPOS.M_PaymentModes')),
            ],
            options={
                'db_table': 'MC_PaymentModeDetails',
            },
        ),
    ]
