# Generated by Django 3.0.8 on 2025-06-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0069_m_paymentmodes_mc_paymentmodedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_invoicesschemes',
            name='VoucherCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
