# Generated by Django 3.0.8 on 2025-07-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0070_tc_invoicesschemes_vouchercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ERPUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Urls', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'M_ERPUrls',
            },
        ),
        migrations.CreateModel(
            name='MC_ERPUrlsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartyId', models.IntegerField()),
                ('Urls', models.CharField(max_length=400)),
                ('ERPUrls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweetPOS.M_ERPUrls')),
            ],
            options={
                'db_table': 'MC_ERPUrlsDetails',
            },
        ),
    ]
