# Generated by Django 3.0.8 on 2025-07-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0071_m_erpurls_mc_erpurlsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_paymentmodes',
            name='TenderCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='m_paymentmodes',
            name='Payment_Mode',
            field=models.CharField(max_length=50),
        ),
    ]
