# Generated by Django 3.0.8 on 2025-07-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetPOS', '0072_auto_20250725_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_paymentmodes',
            name='Description',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
