# Generated by Django 3.0.8 on 2024-01-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='L_Transactionlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TranasactionDate', models.DateField()),
                ('Transactiontime', models.DateTimeField(auto_now_add=True)),
                ('User', models.IntegerField()),
                ('IPaddress', models.CharField(max_length=500)),
                ('PartyID', models.IntegerField()),
                ('TransactionDetails', models.CharField(max_length=2000)),
                ('JsonData', models.TextField(blank=True)),
                ('TransactionType', models.IntegerField(default=1)),
                ('TransactionID', models.IntegerField(default=1)),
                ('FromDate', models.DateField(blank=True, null=True)),
                ('ToDate', models.DateField(blank=True, null=True)),
                ('CustomerID', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'L_Transactionlog',
            },
        ),
        migrations.CreateModel(
            name='L_TransactionLogJsonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JsonData', models.TextField(blank=True)),
                ('Transactionlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactionlog', to='FoodERPDBLog.L_Transactionlog')),
            ],
            options={
                'db_table': 'L_TransactionLogJsonData',
            },
        ),
    ]
