# Generated by Django 4.0.4 on 2022-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('LoginName', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('EmployeeID', models.IntegerField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('isSendOTP', models.BooleanField(default=False)),
                ('AdminPassword', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
