# Generated by Django 3.0.8 on 2022-07-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='phone_number',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
