# Generated by Django 3.0.8 on 2023-03-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_loadingsheetdetails',
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='tc_loadingsheetdetails',
            name='Loadingsheet',
        ),
        migrations.DeleteModel(
            name='T_LoadingSheet',
        ),
        migrations.DeleteModel(
            name='TC_LoadingSheetDetails',
        ),
    ]
