# Generated by Django 3.0.8 on 2023-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_purchasereturn',
            name='Comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='ItemComment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
