# Generated by Django 3.0.8 on 2022-08-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_vehicals',
            name='Driver',
        ),
        migrations.RemoveField(
            model_name='m_vehicals',
            name='VehicalType',
        ),
        migrations.RemoveField(
            model_name='mc_vehicalsdivisions',
            name='Division',
        ),
        migrations.RemoveField(
            model_name='mc_vehicalsdivisions',
            name='Vehical',
        ),
        migrations.DeleteModel(
            name='M_Drivers',
        ),
        migrations.DeleteModel(
            name='M_Vehicals',
        ),
        migrations.DeleteModel(
            name='M_VehicleTypes',
        ),
        migrations.DeleteModel(
            name='MC_VehicalsDivisions',
        ),
    ]
