# Generated by Django 3.0.8 on 2022-07-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_pages',
            name='isShowOnMenu',
        ),
    ]
