# Generated by Django 3.0.8 on 2023-03-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_vehicletypes',
            name='Party',
        ),
    ]
