# Generated by Django 3.0.8 on 2022-09-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='Margin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemMargin', to='FoodERPApp.M_MarginMaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderCustomer', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='GST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGST', to='FoodERPApp.MC_ItemGSTHSNCode'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='MRP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemMRP', to='FoodERPApp.M_MRPMaster'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderUnitID', to='FoodERPApp.MC_ItemUnits'),
        ),
    ]
