# Generated by Django 3.0.8 on 2023-04-20 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='CRDRNote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CRDRNoteItems', to='FoodERPApp.T_CreditDebitNotes'),
        ),
    ]
