# Generated by Django 3.0.8 on 2022-08-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehical',
            name='Driver',
        ),
        migrations.RemoveField(
            model_name='vehicalsdivisions',
            name='Division',
        ),
        migrations.RemoveField(
            model_name='vehicalsdivisions',
            name='Vehical',
        ),
        migrations.DeleteModel(
            name='VehicleTypes',
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
        migrations.DeleteModel(
            name='Vehical',
        ),
        migrations.DeleteModel(
            name='VehicalsDivisions',
        ),
    ]
