# Generated by Django 3.0.8 on 2023-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employees',
            name='AadharNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='DOB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='PAN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
