# Generated by Django 3.0.8 on 2023-04-20 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_purchasereturnitems',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='tc_purchasereturnitems',
            name='DiscountAmount',
        ),
        migrations.RemoveField(
            model_name='tc_purchasereturnitems',
            name='DiscountType',
        ),
        migrations.AddField(
            model_name='m_users',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='last activity'),
        ),
        migrations.AlterField(
            model_name='tc_purchasereturnitems',
            name='LiveBatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.O_LiveBatches'),
        ),
    ]
