# Generated by Django 3.0.8 on 2023-04-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_creditdebitnotes',
            name='NoteReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NoteReason', to='FoodERPApp.M_GeneralMaster'),
        ),
    ]
