# Generated by Django 3.0.8 on 2023-05-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='SAPPartyCode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
