# Generated by Django 3.0.8 on 2022-07-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=100)),
                ('CompanyAbbreviation', models.CharField(max_length=100)),
                ('EmailID', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'C_Companies',
            },
        ),
        migrations.CreateModel(
            name='C_CompanyGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'C_CompanyGroups',
            },
        ),
        migrations.CreateModel(
            name='H_Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DisplayIndex', models.IntegerField()),
                ('IsActive', models.BooleanField(default=False)),
                ('Icon', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'H_Modules',
            },
        ),
        migrations.CreateModel(
            name='M_Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_Districts',
            },
        ),
        migrations.CreateModel(
            name='M_DivisionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_DivisionType',
            },
        ),
        migrations.CreateModel(
            name='M_States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('StateCode', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_States',
            },
        ),
        migrations.AlterField(
            model_name='m_users',
            name='CreatedBy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='m_users',
            name='EmployeeID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='m_users',
            name='UpdatedBy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='m_users',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='M_PartyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('DivisionTypeID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyTypeDivision', to='FoodERPApp.M_DivisionType')),
            ],
            options={
                'db_table': 'M_PartyType',
            },
        ),
        migrations.CreateModel(
            name='M_Parties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('CustomerDivision', models.IntegerField()),
                ('Email', models.EmailField(max_length=200)),
                ('MobileNo', models.BigIntegerField(unique=True)),
                ('Address', models.CharField(max_length=500)),
                ('PIN', models.CharField(max_length=500)),
                ('Taluka', models.IntegerField()),
                ('City', models.IntegerField()),
                ('GSTIN', models.CharField(max_length=500)),
                ('FSSAINo', models.CharField(max_length=500)),
                ('FSSAIExipry', models.DateField(blank=True)),
                ('IsActive', models.IntegerField()),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartiesDistrict', to='FoodERPApp.M_Districts')),
                ('DivisionTypeID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartiesDivision', to='FoodERPApp.M_DivisionType')),
                ('PartyTypeID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartiesPartyType', to='FoodERPApp.M_PartyType')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartiesState', to='FoodERPApp.M_States')),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartiesCompany', to='FoodERPApp.C_Companies')),
            ],
            options={
                'db_table': 'M_Parties',
            },
        ),
        migrations.AddField(
            model_name='m_districts',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_States'),
        ),
        migrations.AddField(
            model_name='c_companies',
            name='CompanyGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CompanyGroup', to='FoodERPApp.C_CompanyGroups'),
        ),
    ]
