# Generated by Django 3.0.8 on 2023-05-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o_batchwiselivestock',
            name='PurchaseReturn',
        ),
    ]
