# Generated by Django 3.0.8 on 2022-12-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_materialissue',
            old_name='Division',
            new_name='Party',
        ),
        migrations.RenameField(
            model_name='t_workorder',
            old_name='Division',
            new_name='Party',
        ),
    ]
