# Generated by Django 4.0.4 on 2022-05-21 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_Companies',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=100)),
                ('CompanyAbbreviation', models.CharField(max_length=100)),
                ('EmailID', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'C_Companies',
            },
        ),
        migrations.CreateModel(
            name='H_Modules',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DisplayIndex', models.IntegerField()),
                ('IsActive', models.BooleanField(default=False)),
                ('Icon', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'H_Modules',
            },
        ),
        migrations.CreateModel(
            name='M_Roles',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('Dashboard', models.CharField(max_length=200)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_Roles',
            },
        ),
        migrations.CreateModel(
            name='H_Pages',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('DisplayIndex', models.IntegerField()),
                ('Icon', models.CharField(max_length=100)),
                ('ActualPagePath', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='H_PagesModule', to='FoodERPApp.h_modules')),
            ],
            options={
                'db_table': 'H_Pages',
            },
        ),
    ]
