# Generated by Django 3.0.8 on 2023-05-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_PartyBanks',
        ),
    ]
