# Generated by Django 3.0.8 on 2023-05-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_routeschedule',
            name='Friday',
        ),
        migrations.RemoveField(
            model_name='mc_routeschedule',
            name='Monday',
        ),
        migrations.RemoveField(
            model_name='mc_routeschedule',
            name='Saturday',
        ),
        migrations.RemoveField(
            model_name='mc_routeschedule',
            name='Sunday',
        ),
        migrations.RemoveField(
            model_name='mc_routeschedule',
            name='Thrusday',
        ),
        migrations.RemoveField(
            model_name='mc_routeschedule',
            name='Tuesday',
        ),
        migrations.RemoveField(
            model_name='mc_routeschedule',
            name='Wednesday',
        ),
    ]
