# Generated by Django 3.0.8 on 2023-05-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partyimportfields',
            name='ImportField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImportFields', to='FoodERPApp.M_ImportFields'),
        ),
    ]
