# Generated by Django 3.0.8 on 2023-04-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='Company',
        ),
    ]
