# Generated by Django 3.0.8 on 2022-08-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20220829_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=500)),
                ('UID', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'M_Drivers',
            },
        ),
        migrations.CreateModel(
            name='M_Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleNumber', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=300)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DriverName', to='FoodERPApp.M_Drivers')),
            ],
            options={
                'db_table': 'M_Vehicles',
            },
        ),
        migrations.CreateModel(
            name='M_VehicleTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'M_VehicleTypes',
            },
        ),
        migrations.CreateModel(
            name='MC_VehiclesDivisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='VehicleDivision', to='FoodERPApp.M_Parties')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Vehicle', to='FoodERPApp.M_Vehicles')),
            ],
            options={
                'db_table': 'MC_VehiclesDivisions',
            },
        ),
        migrations.AddField(
            model_name='m_vehicles',
            name='VehicleType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='VehicleType', to='FoodERPApp.M_VehicleTypes'),
        ),
    ]
