# Generated by Django 3.0.8 on 2022-12-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20221213_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_materialissueitems',
            old_name='SupplierBatchCode',
            new_name='SystemBatchCode',
        ),
    ]
