# Generated by Django 3.0.8 on 2022-08-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20220829_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MRP_Types',
            new_name='M_MRPTypes',
        ),
        migrations.AlterModelTable(
            name='m_mrptypes',
            table='M_MRPTypes',
        ),
    ]
