# Generated by Django 3.0.8 on 2023-04-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20230420_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_importfields',
            name='CreatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_importfields',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_importfields',
            name='UpdatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_importfields',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mc_partyimportfields',
            name='CreatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_partyimportfields',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_partyimportfields',
            name='UpdatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_partyimportfields',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
