# Generated by Django 3.0.8 on 2023-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20230515_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='BaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='OriginalBaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='o_livebatches',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='BaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='BasicAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='GSTAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='MRP',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
