# Generated by Django 3.0.8 on 2023-04-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20230404_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_receiptinvoices',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
