# Generated by Django 3.0.8 on 2022-07-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20220701_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='DivisionTypeID',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='PartyTypeID',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='companyID',
        ),
    ]
