# Generated by Django 3.0.8 on 2023-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_remove_m_vehicletypes_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='IsSCM',
            field=models.BooleanField(default=False),
        ),
    ]
