# Generated by Django 3.0.8 on 2023-05-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20230517_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_salesmanroutes',
            name='Salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SalesmanRoute', to='FoodERPApp.M_Salesman'),
        ),
    ]
