# Generated by Django 3.0.8 on 2023-04-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20230408_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_PartySubPartyOpeningBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OpeningBalanceAmount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MParty', to='FoodERPApp.M_Parties')),
                ('SubParty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MSubParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'MC_PartySubPartyOpeningBalance',
            },
        ),
    ]
