# Generated by Django 3.0.8 on 2023-05-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_tc_invoiceitems_gstvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_invoiceitems',
            name='GSTPercentage',
        ),
        migrations.RemoveField(
            model_name='tc_invoiceitems',
            name='GSTValue',
        ),
    ]
