# Generated by Django 3.0.8 on 2023-05-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_t_receipts_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_receipts',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptCustomer', to='FoodERPApp.M_Parties'),
        ),
    ]
