# Generated by Django 3.0.8 on 2023-05-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_m_bank_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_bank',
            name='Company',
        ),
    ]
