# Generated by Django 3.0.8 on 2023-05-12 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_delete_mc_partybanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_PartyBanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IFSC', models.CharField(blank=True, max_length=500, null=True)),
                ('BranchName', models.CharField(blank=True, max_length=500, null=True)),
                ('CustomerBank', models.BooleanField(default=False)),
                ('AccountNo', models.CharField(blank=True, max_length=500, null=True)),
                ('IsSelfDepositoryBank', models.BooleanField(default=False)),
                ('IsDefault', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MCPartyBank', to='FoodERPApp.M_Bank')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartyCompanyBank', to='FoodERPApp.C_Companies')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartyBank', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'MC_PartyBanks',
            },
        ),
    ]
