# Generated by Django 3.0.8 on 2023-03-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_m_roles_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_roles',
            name='Company',
        ),
    ]
