# Generated by Django 3.0.8 on 2022-09-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20220923_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_items',
            name='LinkedItem',
        ),
    ]
