# Generated by Django 3.0.8 on 2022-07-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_abc_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
