# Generated by Django 3.0.8 on 2022-11-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20221101_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='GST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OrderItemGST', to='FoodERPApp.M_GSTHSNCode'),
        ),
    ]
