# Generated by Django 3.0.8 on 2022-11-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20221101_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Unit',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderUnitID', to='FoodERPApp.MC_ItemUnits'),
        ),
    ]
