# Generated by Django 3.0.8 on 2022-12-14 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20221213_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='IsOpenPO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_orders',
            name='POFromDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_orders',
            name='POToDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
