# Generated by Django 3.0.8 on 2023-05-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20230512_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_bank',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='CompanyBank', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='PurchaseReturn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BatchWiseLiveStockPurchaseReturnID', to='FoodERPApp.T_PurchaseReturn'),
        ),
    ]
