# Generated by Django 4.2.1 on 2023-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_alter_m_parties_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employees',
            name='AadharNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='DOB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='PAN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
