# Generated by Django 3.0.8 on 2023-04-21 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20230420_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_creditdebitnoteitems',
            name='GSTRate',
        ),
        migrations.RemoveField(
            model_name='tc_creditdebitnoteitems',
            name='HSNCode',
        ),
        migrations.RemoveField(
            model_name='tc_creditdebitnoteitems',
            name='NOC',
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='BaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='BatchDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='GST',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CRDRItemGST', to='FoodERPApp.M_GSTHSNCode'),
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='LiveBatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.O_LiveBatches'),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='BasicAmount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='CGST',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='CGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='GSTAmount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='IGST',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='IGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='Item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='SGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='Unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='CRDRUnit', to='FoodERPApp.MC_ItemUnits'),
            preserve_default=False,
        ),
    ]
