# Generated by Django 3.0.8 on 2023-05-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20230516_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MC_RouteSchedule',
            new_name='MC_SalesManRoutes',
        ),
        migrations.AlterModelTable(
            name='mc_salesmanroutes',
            table='MC_SalesManRoutes',
        ),
    ]
