# Generated by Django 3.0.8 on 2023-04-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20230420_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_purchasereturn',
            name='ReturnReason',
            field=models.ForeignKey(default=59, on_delete=django.db.models.deletion.PROTECT, related_name='ReturnReason', to='FoodERPApp.M_GeneralMaster'),
            preserve_default=False,
        ),
    ]
