# Generated by Django 3.0.8 on 2023-03-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_auto_20230311_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_drivers',
            name='Company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='DCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_vehicles',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='VCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_vehicletypes',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='VTCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_vehicletypes',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='VTParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
