# Generated by Django 3.0.8 on 2023-04-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_remove_mc_partyimportfields_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partyimportfields',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='PartyImportFieldCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
