# Generated by Django 4.0.4 on 2022-05-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0002_c_companies_h_modules_m_roles_h_pages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='C_Companies',
        ),
        migrations.RemoveField(
            model_name='h_pages',
            name='Module',
        ),
        migrations.DeleteModel(
            name='M_Roles',
        ),
        migrations.DeleteModel(
            name='H_Modules',
        ),
        migrations.DeleteModel(
            name='H_Pages',
        ),
    ]
