# Generated by Django 3.0.8 on 2023-04-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_tc_receiptinvoices_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_employeetypes',
            name='IsSalesTeamMember',
        ),
    ]
