# Generated by Django 3.0.8 on 2023-04-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230421_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_PartyCustomerMappingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MapCustomer', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MappingPartiescustomer', to='FoodERPApp.M_Parties')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MappingParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'M_PartyCustomerMappingMaster',
            },
        ),
        migrations.CreateModel(
            name='M_ItemUnitMappingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MapUnit', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('UnitID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Unit', to='FoodERPApp.M_Units')),
            ],
            options={
                'db_table': 'M_ItemUnitMappingMaster',
            },
        ),
        migrations.CreateModel(
            name='M_ItemMappingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MapItem', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MappingItem', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'M_ItemMappingMaster',
            },
        ),
    ]
