# Generated by Django 3.0.8 on 2022-12-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20221229_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_itemshelflife',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
