# Generated by Django 3.0.8 on 2023-04-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230420_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='ImportField',
        ),
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='Party',
        ),
        migrations.DeleteModel(
            name='M_ImportFields',
        ),
        migrations.DeleteModel(
            name='MC_PartyImportFields',
        ),
    ]
