# Generated by Django 3.0.8 on 2023-05-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230512_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o_batchwiselivestock',
            name='PurchaseReturn',
        ),
    ]
