# Generated by Django 3.0.8 on 2023-06-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_alter_m_employees_aadharno_alter_m_employees_dob_and_more'),
        ('FoodERPApp', '0002_auto_20230607_1819'),
    ]

    operations = [
    ]
