# Generated by Django 3.0.8 on 2023-04-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_mc_partysubpartyopeningbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partysubpartyopeningbalance',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
