# Generated by Django 3.0.8 on 2023-05-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230516_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_salesmanroutes',
            name='Route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='SRoute', to='FoodERPApp.M_Routes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mc_salesmanroutes',
            name='Salesman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='SalesmanRoute', to='FoodERPApp.M_Salesman'),
            preserve_default=False,
        ),
    ]
