# Generated by Django 3.0.8 on 2022-09-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_remove_m_items_linkeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_mrpmaster',
            name='Division',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MRPDivision', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
