# Generated by Django 3.0.8 on 2023-05-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230518_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemSetting', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'M_Settings',
            },
        ),
        migrations.CreateModel(
            name='MC_SettingsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=500)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SettingCompany', to='FoodERPApp.C_Companies')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SettingParty', to='FoodERPApp.M_Parties')),
                ('SettingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SettingDetails', to='FoodERPApp.M_Settings')),
            ],
            options={
                'db_table': 'MC_SettingsDetails',
            },
        ),
        migrations.CreateModel(
            name='MC_SettingDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DependentSetting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DependentSettingID', to='FoodERPApp.M_Settings')),
                ('Setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DependentSettingDetails', to='FoodERPApp.M_Settings')),
            ],
            options={
                'db_table': 'MC_SettingDependency',
            },
        ),
    ]
