# Generated by Django 3.0.8 on 2022-05-23 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_delete_c_companies_remove_h_pages_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_Companies',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=100)),
                ('CompanyAbbreviation', models.CharField(max_length=100)),
                ('EmailID', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'C_Companies',
            },
        ),
        migrations.CreateModel(
            name='C_CompanyGroups',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'C_CompanyGroups',
            },
        ),
        migrations.CreateModel(
            name='H_Modules',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DisplayIndex', models.IntegerField()),
                ('IsActive', models.BooleanField(default=False)),
                ('Icon', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'H_Modules',
            },
        ),
        migrations.CreateModel(
            name='H_PageAccess',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'H_PageAccess',
            },
        ),
        migrations.CreateModel(
            name='H_Pages',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('DisplayIndex', models.IntegerField()),
                ('Icon', models.CharField(max_length=100)),
                ('ActualPagePath', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='H_PagesModule', to='FoodERPApp.H_Modules')),
            ],
            options={
                'db_table': 'H_Pages',
            },
        ),
        migrations.CreateModel(
            name='H_SubModules',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Icon', models.CharField(max_length=100)),
                ('IsActive', models.BooleanField(default=False)),
                ('DisplayIndex', models.IntegerField()),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='H_SubModulesModules', to='FoodERPApp.H_Modules')),
            ],
            options={
                'db_table': 'H_SubModules',
            },
        ),
        migrations.CreateModel(
            name='M_Parties',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('PartyTypeID', models.IntegerField()),
                ('DividionTypeID', models.IntegerField()),
                ('companyID', models.IntegerField()),
                ('CustomerDivision', models.IntegerField()),
                ('Email', models.EmailField(max_length=200)),
                ('Address', models.CharField(max_length=500)),
                ('PIN', models.CharField(max_length=500)),
                ('State', models.IntegerField()),
                ('District', models.IntegerField()),
                ('Taluka', models.IntegerField()),
                ('City', models.IntegerField()),
                ('GSTN', models.CharField(max_length=500)),
                ('FSSAINo', models.CharField(max_length=500)),
                ('FSSAIExipry', models.DateField(blank=True)),
                ('IsActive', models.IntegerField()),
            ],
            options={
                'db_table': 'M_Parties',
            },
        ),
        migrations.CreateModel(
            name='M_Roles',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('Dashboard', models.CharField(max_length=200)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_Roles',
            },
        ),
        migrations.CreateModel(
            name='M_RoleAccess',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Company', to='FoodERPApp.C_Companies')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Dividion', to='FoodERPApp.M_Parties')),
                ('Modules', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='M_RoleAccessModules', to='FoodERPApp.H_Modules')),
                ('Pages', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pages', to='FoodERPApp.H_Pages')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Role', to='FoodERPApp.M_Roles')),
                ('SubModule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SubModule', to='FoodERPApp.H_SubModules')),
            ],
            options={
                'db_table': 'M_RoleAccess',
            },
        ),
        migrations.CreateModel(
            name='HC_PageAccessItems',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('AccessID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.H_PageAccess')),
                ('PageID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.H_Pages')),
            ],
            options={
                'db_table': 'HC_PageAccessItems',
            },
        ),
        migrations.AddField(
            model_name='h_pages',
            name='SubModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submodule', to='FoodERPApp.H_SubModules'),
        ),
        migrations.AddField(
            model_name='c_companies',
            name='CompanyGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CompanyGroup', to='FoodERPApp.C_CompanyGroups'),
        ),
    ]
