# Generated by Django 3.0.8 on 2022-12-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20221214_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='DeletedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
