# Generated by Django 3.0.8 on 2023-05-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230515_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_pagefieldmaster',
            name='Alignment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
