# Generated by Django 3.0.8 on 2023-03-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_t_loadingsheet_tc_loadingsheetdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_loadingsheet',
            name='VehicleNo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
