# Generated by Django 3.0.8 on 2023-05-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230515_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_pagefieldmaster',
            name='Alignment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='MC_RouteSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sunday', models.BooleanField(blank=True, default=False, null=True)),
                ('Monday', models.BooleanField(blank=True, default=False, null=True)),
                ('Tuesday', models.BooleanField(blank=True, default=False, null=True)),
                ('Wednesday', models.BooleanField(blank=True, default=False, null=True)),
                ('Thrusday', models.BooleanField(blank=True, default=False, null=True)),
                ('Friday', models.BooleanField(blank=True, default=False, null=True)),
                ('Saturday', models.BooleanField(blank=True, default=False, null=True)),
                ('Route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalesmanRoute', to='FoodERPApp.M_Routes')),
                ('Salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Salesman', to='FoodERPApp.M_Salesman')),
            ],
            options={
                'db_table': 'MC_RouteSchedule',
            },
        ),
    ]
