# Generated by Django 3.0.8 on 2022-12-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20221215_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_materialissueitems',
            name='BatchCodeQuantity',
        ),
    ]
