# Generated by Django 3.0.8 on 2022-07-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_abc_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='abc',
            name='Name',
        ),
    ]
