# Generated by Django 3.0.8 on 2022-08-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20220829_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_itemunits',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemUnitDetails', to='FoodERPApp.M_Items'),
        ),
    ]
