# Generated by Django 3.0.8 on 2023-03-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_m_items_isscm'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptDate', models.DateField()),
                ('ReceiptNo', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('AmountPaid', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('BalanceAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('OpeningBalanceAdjusted', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ChequeDate', models.DateField(blank=True, null=True)),
                ('DocumentNo', models.CharField(blank=True, max_length=500, null=True)),
                ('Bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bank', to='FoodERPApp.M_Bank')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptCustomer', to='FoodERPApp.M_Parties')),
                ('DepositorBank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DepositorBank', to='FoodERPApp.M_Bank')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptParty', to='FoodERPApp.M_Parties')),
                ('ReceiptMode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Receiptmode', to='FoodERPApp.M_GeneralMaster')),
            ],
            options={
                'db_table': 'T_Receipts',
            },
        ),
        migrations.CreateModel(
            name='TC_ReceiptInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrandTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('PaidAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('AdvanceAmtAdjusted', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RInvoice', to='FoodERPApp.T_Invoices')),
                ('Receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Receipt', to='FoodERPApp.T_Receipts')),
            ],
            options={
                'db_table': 'TC_ReceiptInvoices',
            },
        ),
    ]
