# Generated by Django 3.0.8 on 2022-07-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20220701_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Designations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_Designations',
            },
        ),
        migrations.CreateModel(
            name='M_EmployeeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_EmployeeTypes',
            },
        ),
        migrations.AddField(
            model_name='m_parties',
            name='DivisionType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartiesDivision', to='FoodERPApp.M_DivisionType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_parties',
            name='PartyType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartiesPartyType', to='FoodERPApp.M_PartyType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_parties',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartiesCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='M_Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('DOB', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=100)),
                ('AadharNo', models.CharField(max_length=100)),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='EmployeesDesignation', to='FoodERPApp.M_Designations')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='EmployeesDistrict', to='FoodERPApp.M_Districts')),
                ('EmployeeType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='EmployeeType', to='FoodERPApp.M_EmployeeTypes')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='EmployeesState', to='FoodERPApp.M_States')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='EmployeesCompany', to='FoodERPApp.C_Companies')),
            ],
            options={
                'db_table': 'M_Employees',
            },
        ),
    ]
