# Generated by Django 3.0.8 on 2023-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230506_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
