# Generated by Django 3.0.8 on 2023-03-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230311_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_vehicles',
            name='Party',
        ),
    ]
