# Generated by Django 3.0.8 on 2023-04-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230420_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_importfields',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='m_importfields',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='m_importfields',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='m_importfields',
            name='UpdatedOn',
        ),
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='UpdatedOn',
        ),
    ]
