# Generated by Django 3.0.8 on 2023-05-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20230505_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_bank',
            name='Company',
        ),
    ]
