# Generated by Django 3.0.8 on 2022-08-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20220802_1214'),
        ('FoodERPApp', '0002_remove_m_pages_isshowonmenu'),
    ]

    operations = [
    ]
