# Generated by Django 3.0.8 on 2022-11-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0003_auto_20221102_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OrderUnitID', to='FoodERPApp.MC_ItemUnits'),
        ),
    ]
