# Generated by Django 3.0.8 on 2023-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_remove_m_employeetypes_issalesteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employeetypes',
            name='IsSalesTeamMember',
            field=models.BooleanField(default=False),
        ),
    ]
