# Generated by Django 3.0.8 on 2023-04-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_mc_partysubpartyopeningbalance_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mc_partysubpartyopeningbalance',
            old_name='year',
            new_name='Year',
        ),
    ]
