# Generated by Django 3.0.8 on 2023-05-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_m_bank_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_bank',
            name='Companyaa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='CompanyBank1', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_bank',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CompanyBank', to='FoodERPApp.C_Companies'),
        ),
    ]
