# Generated by Django 3.0.8 on 2022-11-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_auto_20221102_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_GRNs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRNDate', models.DateField()),
                ('GRNNumber', models.IntegerField()),
                ('GrandTotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='GRNCustomer', to='FoodERPApp.M_Parties')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='GRNParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'T_GRNs',
            },
        ),
        migrations.CreateModel(
            name='TC_GRNReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GRNReferences', to='FoodERPApp.T_GRNs')),
                ('Invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.T_Invoices')),
                ('Order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.T_Orders')),
            ],
            options={
                'db_table': 'TC_GRNReferences',
            },
        ),
        migrations.CreateModel(
            name='TC_GRNItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ReferenceRate', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DiscountType', models.CharField(max_length=500)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('GRN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GRNItems', to='FoodERPApp.T_GRNs')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_Items')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='GRNUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'TC_GRNItems',
            },
        ),
        migrations.CreateModel(
            name='TC_GRNItemBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('GRN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_GRNs')),
                ('GRNItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GRNItemBatches', to='FoodERPApp.TC_GRNItems')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_Items')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='GRNBatchUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'TC_GRNItemBatches',
            },
        ),
    ]
