# Generated by Django 3.0.8 on 2022-09-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_auto_20220926_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_mrpmaster',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MRPDivision', to='FoodERPApp.M_Parties'),
        ),
    ]
