# Generated by Django 3.0.8 on 2022-09-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_auto_20220830_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_itemcategorydetails',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemCategoryDetails', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='mc_itemdivisions',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemDivisionDetails', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='mc_itemimages',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemImagesDetails', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='mc_itemmargin',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemMarginDetails', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='mc_itemmrp',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemMRPDetails', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='mc_itemunits',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemUnitDetails', to='FoodERPApp.M_Items'),
        ),
    ]
