# Generated by Django 3.0.8 on 2023-03-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_remove_m_vehicles_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_vehicles',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='VParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
