# Generated by Django 3.0.8 on 2022-07-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_auto_20220701_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_employees',
            name='company',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='company',
        ),
    ]
