# Generated by Django 3.0.8 on 2023-05-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_auto_20230512_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_PartyBanks',
        ),
    ]
