# Generated by Django 3.0.8 on 2023-05-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_tc_invoiceitems_gstpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_units',
            name='SAPUnit',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
