# Generated by Django 3.0.8 on 2022-12-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_mc_itemshelflife_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_itemunits',
            name='PODefaultUnit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mc_itemunits',
            name='SODefaultUnit',
            field=models.BooleanField(default=False),
        ),
    ]
