# Generated by Django 3.0.8 on 2023-04-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_m_itemmappingmaster_m_itemunitmappingmaster_m_partycustomermappingmaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_creditdebitnotes',
            old_name='NoteDate',
            new_name='CRDRNoteDate',
        ),
    ]
