# Generated by Django 3.0.8 on 2023-04-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_auto_20230420_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ImportFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FieldName', models.CharField(max_length=500)),
                ('IsCompulsory', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ImportFieldCompany', to='FoodERPApp.C_Companies')),
                ('ControlType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ImportFieldControlType', to='FoodERPApp.M_ControlTypeMaster')),
                ('FieldValidation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ImportFieldValidation', to='FoodERPApp.M_FieldValidations')),
            ],
            options={
                'db_table': 'M_ImportFields',
            },
        ),
        migrations.CreateModel(
            name='MC_PartyImportFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartyImportFieldCompany', to='FoodERPApp.C_Companies')),
                ('ImportField', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ImportFields', to='FoodERPApp.M_ImportFields')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartyImport', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'MC_PartyImportFields',
            },
        ),
    ]
