# Generated by Django 3.0.8 on 2023-03-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_auto_20230309_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_vehicles',
            name='Driver',
        ),
        migrations.AddField(
            model_name='m_drivers',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AddField(
            model_name='m_drivers',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_items',
            name='IsSCM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_parties',
            name='IsSCM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_vehicles',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AddField(
            model_name='m_vehicles',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='VParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_vehicletypes',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VTCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AddField(
            model_name='m_vehicletypes',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='VTParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
