# Generated by Django 3.0.8 on 2022-09-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_auto_20220830_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_roleaccess',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleAccessCompany', to='FoodERPApp.C_Companies'),
        ),
    ]
