# Generated by Django 3.0.8 on 2022-12-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_remove_tc_materialissueitems_batchcodequantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_billofmaterial',
            name='ReferenceBom',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
