# Generated by Django 3.0.8 on 2022-05-23 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_auto_20220523_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_UserRoles',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleIDfromUserRoles', to='FoodERPApp.M_Roles')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserIDfromUserRoles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
