# Generated by Django 3.0.8 on 2023-03-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_m_roles_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_drivers',
            name='UID',
        ),
        migrations.AlterField(
            model_name='m_drivers',
            name='CreatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_drivers',
            name='UpdatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_vehicles',
            name='Driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DriverName', to='FoodERPApp.M_Drivers'),
        ),
        migrations.AlterField(
            model_name='m_vehicles',
            name='VehicleType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VehicleType', to='FoodERPApp.M_VehicleTypes'),
        ),
    ]
