# Generated by Django 3.0.8 on 2023-05-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_m_settings_mc_settingdependency_mc_settingsdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='GSTIN',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='PAN',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mc_partyaddress',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PartyAddress', to='FoodERPApp.M_Parties'),
        ),
    ]
