# Generated by Django 3.0.8 on 2022-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_auto_20220719_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='otp',
            field=models.CharField(default=False, max_length=6),
        ),
    ]
