# Generated by Django 3.0.8 on 2023-05-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_remove_m_bank_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='MRP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OrderItemMRP', to='FoodERPApp.M_MRPMaster'),
        ),
    ]
