# Generated by Django 3.0.8 on 2023-03-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0004_t_receipts_tc_receiptinvoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_receipts',
            name='ReceiptMode',
        ),
    ]
