# Generated by Django 3.0.8 on 2022-08-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_mc_employeeparties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_employeeparties',
            name='EmployeeID',
        ),
        migrations.AddField(
            model_name='mc_employeeparties',
            name='Employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeParties', to='FoodERPApp.M_Employees'),
            preserve_default=False,
        ),
    ]
