# Generated by Django 3.0.8 on 2023-04-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20230420_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_purchasereturnitems',
            name='LiveBatch',
        ),
    ]
