# Generated by Django 3.0.8 on 2023-03-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20230308_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_vehicles',
            name='CreatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_vehicles',
            name='UpdatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
