# Generated by Django 3.0.8 on 2023-04-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20230422_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_receipts',
            name='AmountPaid',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
