# Generated by Django 3.0.8 on 2023-03-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_m_vehicles_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_drivers',
            name='Party',
        ),
    ]
