# Generated by Django 3.0.8 on 2023-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20230505_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_invoiceitems',
            old_name='GSTValue',
            new_name='GSTPercentage',
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='DiscountAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
