# Generated by Django 3.0.8 on 2023-04-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20230408_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='Note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CRDRNote', to='FoodERPApp.T_CreditDebitNotes'),
        ),
        migrations.AlterField(
            model_name='tc_receiptinvoices',
            name='Receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReceiptInvoices', to='FoodERPApp.T_Receipts'),
        ),
    ]
