# Generated by Django 3.0.8 on 2022-12-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_m_billofmaterial_referencebom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_materialissueworkorders',
            name='Bom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Bom', to='FoodERPApp.M_BillOfMaterial'),
            preserve_default=False,
        ),
    ]
