# Generated by Django 3.0.8 on 2023-04-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_m_employeetypes_issalesteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_CreditNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoteType', models.IntegerField()),
                ('NoteTypeMode', models.CharField(max_length=20)),
                ('NoteNumber', models.IntegerField()),
                ('CreditNoteDate', models.DateField(blank=True, null=True)),
                ('GrandTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('RoundOffAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('CreditNoteReason', models.CharField(blank=True, max_length=50, null=True)),
                ('DebitNoteReason', models.CharField(blank=True, max_length=50, null=True)),
                ('IsChequeBounce', models.BooleanField(default=False)),
                ('ReceiptNo', models.CharField(blank=True, max_length=500, null=True)),
                ('Narration', models.CharField(blank=True, max_length=500, null=True)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CNCustomer', to='FoodERPApp.M_Parties')),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CNInvoice', to='FoodERPApp.T_Invoices')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='T_CreditNotesParty', to='FoodERPApp.M_Parties')),
                ('PurchaseReturn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_PurchaseReturn')),
            ],
            options={
                'db_table': 'T_CreditNotes',
            },
        ),
        migrations.CreateModel(
            name='TC_CreditNotesItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HSNCode', models.CharField(blank=True, max_length=500, null=True)),
                ('Quantity', models.IntegerField()),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTRate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('NOC', models.CharField(max_length=20)),
                ('BatchCode', models.CharField(max_length=500)),
                ('CreditNote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CNoteID', to='FoodERPApp.T_CreditNotes')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('MRP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CNoteMRP', to='FoodERPApp.M_MRPMaster')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Units')),
            ],
            options={
                'db_table': 'TC_CreditNotesItems',
            },
        ),
    ]
