# Generated by Django 3.0.8 on 2022-11-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_t_grns_tc_grnitembatches_tc_grnitems_tc_grnreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitembatches',
            name='GRN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GRNBatches', to='FoodERPApp.T_GRNs'),
        ),
    ]
