# Generated by Django 3.0.8 on 2022-07-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20220701_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employees',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='EmployeesCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_parties',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartiesCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
