# Generated by Django 3.0.8 on 2022-05-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_mc_userroles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mc_userroles',
            table='MC_UserRoles',
        ),
    ]
