# Generated by Django 3.0.8 on 2023-05-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20230511_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_bank',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='m_bank',
            name='Companyaa',
        ),
    ]
