# Generated by Django 3.0.8 on 2022-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20220926_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='MkUpMkDn',
            field=models.BooleanField(default=False),
        ),
    ]
