# Generated by Django 3.0.8 on 2022-09-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20220901_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_vehiclesdivisions',
            name='Division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='VDivision', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_vehiclesdivisions',
            name='Vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='VehicleDivisions', to='FoodERPApp.M_Vehicles'),
        ),
    ]
