# Generated by Django 3.0.8 on 2023-06-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20230609_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_grns',
            name='GrandTotal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='t_invoices',
            name='GrandTotal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
