# Generated by Django 3.0.8 on 2023-05-25 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20230525_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partyaddress',
            name='FSSAIExipry',
            field=models.DateField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mc_partyaddress',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PartyAddress', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
