# Generated by Django 3.0.8 on 2023-04-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_m_importfields_mc_partyimportfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_creditdebitnoteitems',
            name='Note',
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='CRDRNote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CRDRNoteItems', to='FoodERPApp.T_CreditDebitNotes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_receiptinvoices',
            name='CRDRNote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CRDRInvoices', to='FoodERPApp.T_CreditDebitNotes'),
        ),
        migrations.AlterField(
            model_name='tc_receiptinvoices',
            name='Receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReceiptInvoices', to='FoodERPApp.T_Receipts'),
        ),
    ]
