# Generated by Django 3.0.8 on 2023-03-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20230309_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_drivers',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='m_vehicles',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='m_vehicletypes',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VTParty', to='FoodERPApp.M_Parties'),
        ),
    ]
