# Generated by Django 3.0.8 on 2022-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_auto_20220719_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_pages',
            name='Description',
        ),
        migrations.AddField(
            model_name='m_pages',
            name='PageDescription',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='m_pages',
            name='PageDescriptionDetails',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='m_pages',
            name='PageHeading',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
