# Generated by Django 3.0.8 on 2023-05-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0005_m_units_sapunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='BillingAddress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='OrderBillingAddress', to='FoodERPApp.MC_PartyAddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='ShippingAddress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='OrderShippingAddress', to='FoodERPApp.MC_PartyAddress'),
            preserve_default=False,
        ),
    ]
