# Generated by Django 3.0.8 on 2022-05-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20220523_1638'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='m_users',
            table='M_Users',
        ),
    ]
