# Generated by Django 3.0.8 on 2023-03-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20230309_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_VehiclesDivisions',
        ),
    ]
