# Generated by Django 3.0.8 on 2023-03-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_t_receipts_receiptmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_invoicesreferences',
            name='Invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvoicesReferences', to='FoodERPApp.T_Invoices'),
        ),
        migrations.AlterField(
            model_name='tc_invoicesreferences',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='InvoiceOrderReferences', to='FoodERPApp.T_Orders'),
        ),
    ]
