# Generated by Django 3.0.8 on 2023-04-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20230424_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_UnitMappingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MapUnit', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UnitMappingParty', to='FoodERPApp.M_Parties')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Unit', to='FoodERPApp.M_Units')),
            ],
            options={
                'db_table': 'M_UnitMappingMaster',
            },
        ),
        migrations.AddField(
            model_name='m_itemmappingmaster',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ItemMappingParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='M_ItemUnitMappingMaster',
        ),
    ]
