# Generated by Django 3.0.8 on 2023-05-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_mc_partybanks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_PartyBanks',
        ),
    ]
