# Generated by Django 3.0.8 on 2023-03-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20230308_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_loadingsheet',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoadingSheetParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_loadingsheet',
            name='Route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoadingSheetRoute', to='FoodERPApp.M_Routes'),
        ),
        migrations.AlterField(
            model_name='tc_loadingsheetdetails',
            name='Invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoadingSheetInvoice', to='FoodERPApp.T_Invoices'),
        ),
        migrations.AlterField(
            model_name='tc_loadingsheetdetails',
            name='Loadingsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoadingSheetDetails', to='FoodERPApp.T_LoadingSheet'),
        ),
        migrations.AlterModelTable(
            name='t_loadingsheet',
            table='T_LoadingSheet',
        ),
    ]
