# Generated by Django 3.0.8 on 2023-04-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_t_creditnotes_tc_creditnotesitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_employeetypes',
            name='IsPartyConnection',
        ),
        migrations.RemoveField(
            model_name='m_employeetypes',
            name='IsSCM',
        ),
    ]
