# Generated by Django 3.0.8 on 2022-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20220722_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_pages',
            name='PageHeading',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
