# Generated by Django 3.0.8 on 2022-09-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_m_parties_mkupmkdn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_pagefieldmaster',
            name='ControlID',
        ),
    ]
