# Generated by Django 3.0.8 on 2023-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20230411_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_purchasereturn',
            name='ReturnNumber',
        ),
        migrations.AddField(
            model_name='t_purchasereturn',
            name='ReturnNo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
