# Generated by Django 3.0.8 on 2022-09-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20220901_1400'),
        ('FoodERPApp', '0005_auto_20220901_1420'),
    ]

    operations = [
    ]
