# Generated by Django 3.0.8 on 2022-07-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20220701_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_partytype',
            name='DivisionTypeID',
        ),
        migrations.RemoveField(
            model_name='m_users',
            name='EmployeeID',
        ),
        migrations.AddField(
            model_name='m_users',
            name='Employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserEmployee', to='FoodERPApp.M_Employees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_districts',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DistrictState', to='FoodERPApp.M_States'),
        ),
    ]
