# Generated by Django 3.0.8 on 2022-08-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20220802_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='IsSCM',
        ),
        migrations.AddField(
            model_name='c_companygroups',
            name='IsSCM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_employeetypes',
            name='IsPartyConnection',
            field=models.BooleanField(default=False),
        ),
    ]
