# Generated by Django 3.0.8 on 2023-05-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20230525_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partyaddress',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PartyAddress', to='FoodERPApp.M_Parties'),
        ),
    ]
