# Generated by Django 3.0.8 on 2023-05-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20230508_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='MRPValue',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
