# Generated by Django 3.0.8 on 2023-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_auto_20230609_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='IsConfirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='QtyInBox',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='QtyInKg',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='QtyInNo',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
