# Generated by Django 3.0.8 on 2022-12-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0006_tc_materialissueworkorders_bom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_billofmaterial',
            name='ReferenceBom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
