# Generated by Django 3.0.8 on 2022-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_remove_mc_pagefieldmaster_controlid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_pagefieldmaster',
            name='ControlID',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
