# Generated by Django 3.0.8 on 2023-04-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_auto_20230405_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_creditnotes',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CNCustomer', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_creditnotes',
            name='Invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CNInvoice', to='FoodERPApp.T_Invoices'),
        ),
        migrations.AlterField(
            model_name='t_creditnotes',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='T_CreditNotesParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_creditnotes',
            name='PurchaseReturn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_PurchaseReturn'),
        ),
        migrations.AlterField(
            model_name='tc_creditnotesitems',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='tc_creditnotesitems',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Units'),
        ),
    ]
