# Generated by Django 3.0.8 on 2023-05-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_o_batchwiselivestock_purchasereturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_partybanks',
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='mc_partybanks',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='mc_partybanks',
            name='Party',
        ),
        migrations.RemoveField(
            model_name='t_receipts',
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='t_receipts',
            name='DepositorBank',
        ),
        migrations.DeleteModel(
            name='M_Bank',
        ),
        migrations.DeleteModel(
            name='MC_PartyBanks',
        ),
    ]
