# Generated by Django 3.0.8 on 2023-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_auto_20230411_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partyprefixs',
            name='PurchaseReturnprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
