# Generated by Django 3.0.8 on 2023-04-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_auto_20230328_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_employees',
            name='Designation',
        ),
        migrations.AddField(
            model_name='m_employeetypes',
            name='IsSalesTeamMember',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_partytype',
            name='IsAdminDivision',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='M_Designations',
        ),
    ]
