# Generated by Django 3.0.8 on 2022-08-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_auto_20220802_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_divisiontype',
            name='IsSCM',
            field=models.BooleanField(default=False),
        ),
    ]
