# Generated by Django 3.0.8 on 2023-04-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_auto_20230424_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_creditdebitnoteitems',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='tc_creditdebitnoteitems',
            name='LiveBatch',
        ),
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='GSTValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='MRPValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='LiveBatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.O_LiveBatches'),
        ),
    ]
