# Generated by Django 3.0.8 on 2022-07-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_auto_20220722_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_pages',
            name='PageHeading',
        ),
    ]
