# Generated by Django 3.0.8 on 2023-03-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_m_drivers_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_employeetypes',
            name='Company',
        ),
    ]
