# Generated by Django 3.0.8 on 2022-05-24 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_auto_20220523_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_userroles',
            name='RoleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_Roles'),
        ),
        migrations.AlterField(
            model_name='mc_userroles',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
