# Generated by Django 3.0.8 on 2022-07-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_auto_20220701_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partytype',
            name='DivisionType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyTypeDivision', to='FoodERPApp.M_DivisionType'),
            preserve_default=False,
        ),
    ]
