# Generated by Django 3.0.8 on 2022-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_merge_20220905_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='LinkedItem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
