# Generated by Django 3.0.8 on 2023-03-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_delete_mc_vehiclesdivisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_items',
            name='IsSCM',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='IsSCM',
        ),
    ]
