# Generated by Django 3.0.8 on 2022-11-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_m_users_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_OrderTermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderTermsAndConditions', to='FoodERPApp.T_Orders')),
                ('TermsAndCondition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_TermsAndConditions')),
            ],
        ),
    ]
