# Generated by Django 3.0.8 on 2023-05-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_auto_20230510_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='IsDamagePieces',
            field=models.BooleanField(default=False),
        ),
    ]
