# Generated by Django 3.0.8 on 2023-03-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_auto_20230309_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='IsSCM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_parties',
            name='IsSCM',
            field=models.BooleanField(default=False),
        ),
    ]
