# Generated by Django 3.0.8 on 2023-04-05 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_auto_20230405_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_receipts',
            name='CreatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_receipts',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_receipts',
            name='UpdatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_receipts',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tc_receiptinvoices',
            name='Receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptInvoices', to='FoodERPApp.T_Receipts'),
        ),
    ]
