# Generated by Django 3.0.8 on 2023-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_auto_20230525_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partyaddress',
            name='FSSAIExipry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
