# Generated by Django 3.0.8 on 2022-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_m_items_linkeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ControlTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'M_ControlTypeMaster',
            },
        ),
        migrations.CreateModel(
            name='M_FieldValidations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'M_FieldValidations',
            },
        ),
    ]
