# Generated by Django 3.0.8 on 2023-03-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_remove_m_employeetypes_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employeetypes',
            name='Company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='Emp_Company', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
