# Generated by Django 3.0.8 on 2022-11-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_tc_ordertermsandconditions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tc_ordertermsandconditions',
            table='TC_OrderTermsAndConditions',
        ),
    ]
