# Generated by Django 3.0.8 on 2022-07-01 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_m_partytype_divisiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='H_PageAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'H_PageAccess',
            },
        ),
        migrations.CreateModel(
            name='M_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Sequence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('BaseunitID', models.IntegerField()),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isActive', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_Items',
            },
        ),
        migrations.CreateModel(
            name='M_ItemsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Sequence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isActive', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_ItemsGroup',
            },
        ),
        migrations.CreateModel(
            name='M_Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('DisplayIndex', models.IntegerField()),
                ('Icon', models.CharField(max_length=100)),
                ('ActualPagePath', models.CharField(max_length=100)),
                ('isShowOnMenu', models.BooleanField(default=False)),
                ('PageType', models.IntegerField()),
                ('RelatedPageID', models.IntegerField()),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_Pages',
            },
        ),
        migrations.CreateModel(
            name='M_RoleAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleAccessCompany', to='FoodERPApp.C_Companies')),
            ],
            options={
                'db_table': 'M_RoleAccess',
            },
        ),
        migrations.CreateModel(
            name='M_Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('Dashboard', models.CharField(max_length=200)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_Roles',
            },
        ),
        migrations.CreateModel(
            name='T_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateField()),
                ('OrderAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Description', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderCustomer', to='FoodERPApp.M_Items')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderParty', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'T_Orders',
            },
        ),
        migrations.RemoveField(
            model_name='h_modules',
            name='IsActive',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='IsActive',
        ),
        migrations.CreateModel(
            name='TC_OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UnitID', models.IntegerField()),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('GST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Items', to='FoodERPApp.M_Items')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItem', to='FoodERPApp.T_Orders')),
            ],
            options={
                'db_table': 'TC_OrderItems',
            },
        ),
        migrations.CreateModel(
            name='MC_UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_Roles')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoleID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MC_UserRoles',
            },
        ),
        migrations.CreateModel(
            name='MC_RolePageAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageAccess', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RolePageAccess', to='FoodERPApp.H_PageAccess')),
                ('RoleAccess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoleAccess', to='FoodERPApp.M_RoleAccess')),
            ],
            options={
                'db_table': 'MC_RolePageAccess',
            },
        ),
        migrations.CreateModel(
            name='MC_PagePageAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Access', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.H_PageAccess')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PagePageAccess', to='FoodERPApp.M_Pages')),
            ],
            options={
                'db_table': 'MC_PagePageAccess',
            },
        ),
        migrations.AddField(
            model_name='m_roleaccess',
            name='Division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleAccessDividion', to='FoodERPApp.M_Parties'),
        ),
        migrations.AddField(
            model_name='m_roleaccess',
            name='Modules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleAccessModules', to='FoodERPApp.H_Modules'),
        ),
        migrations.AddField(
            model_name='m_roleaccess',
            name='Pages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleAccessPages', to='FoodERPApp.M_Pages'),
        ),
        migrations.AddField(
            model_name='m_roleaccess',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleAccessRole', to='FoodERPApp.M_Roles'),
        ),
        migrations.AddField(
            model_name='m_pages',
            name='Module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PagesModule', to='FoodERPApp.H_Modules'),
        ),
        migrations.AddField(
            model_name='m_items',
            name='ItemGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGroup', to='FoodERPApp.M_ItemsGroup'),
        ),
    ]
