# Generated by Django 3.0.8 on 2023-06-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_auto_20230613_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_settingsdetails',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SettingParty', to='FoodERPApp.M_Parties'),
        ),
    ]
