# Generated by Django 3.0.8 on 2022-12-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_auto_20221216_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_materialissue',
            name='Unit',
            field=models.ForeignKey(default=165, on_delete=django.db.models.deletion.PROTECT, related_name='MaterialIssueUnitID', to='FoodERPApp.MC_ItemUnits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tc_materialissueitems',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MaterialIssueItemUnitID', to='FoodERPApp.MC_ItemUnits'),
        ),
    ]
