# Generated by Django 3.0.8 on 2022-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_mc_pagefieldmaster_controlid'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_marginmaster',
            name='CommonID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_mrpmaster',
            name='CommonID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
