# Generated by Django 3.0.8 on 2022-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_remove_m_pages_pageheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_pages',
            name='PageHeading',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
