# Generated by Django 3.0.8 on 2023-05-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_mc_partybanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partybanks',
            name='Bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='MCPartyBank', to='FoodERPApp.M_Bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_partybanks',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='PartyCompanyBank', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_partybanks',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='PartyBank', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
