# Generated by Django 3.0.8 on 2023-04-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_mc_partyprefixs_purchasereturnprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_invoices',
            name='IsLoadingSheetCreated',
            field=models.BooleanField(default=False),
        ),
    ]
