# Generated by Django 3.0.8 on 2023-04-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_auto_20230424_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_creditdebitnotes',
            name='Comment',
        ),
    ]
