# Generated by Django 3.0.8 on 2022-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0008_m_divisiontype_isscm'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_companies',
            name='IsSCM',
            field=models.BooleanField(default=False),
        ),
    ]
