# Generated by Django 3.0.8 on 2022-11-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_auto_20221107_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_ordertermsandconditions',
            name='TermsAndCondition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TermsAndConditions', to='FoodERPApp.M_TermsAndConditions'),
        ),
    ]
