# Generated by Django 3.0.8 on 2022-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_auto_20220701_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_modules',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_parties',
            name='isActive',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
