# Generated by Django 3.0.8 on 2022-07-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_m_pages_pageheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_pageaccess',
            name='DisplayIndex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
