# Generated by Django 3.0.8 on 2023-05-12 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_auto_20230512_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partybanks',
            name='Bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MCPartyBank', to='FoodERPApp.M_Bank'),
        ),
        migrations.AlterField(
            model_name='mc_partybanks',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyCompanyBank', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='mc_partybanks',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyBank', to='FoodERPApp.M_Parties'),
        ),
    ]
