# Generated by Django 3.0.8 on 2023-03-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_m_employeetypes_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_loadingsheetdetails',
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='tc_loadingsheetdetails',
            name='LoadingSheet',
        ),
        migrations.DeleteModel(
            name='T_LoadingSheet',
        ),
        migrations.DeleteModel(
            name='TC_LoadingSheetDetails',
        ),
    ]
