# Generated by Django 3.0.8 on 2022-08-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_c_companies_isscm'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employeetypes',
            name='IsSCM',
            field=models.BooleanField(default=False),
        ),
    ]
