# Generated by Django 3.0.8 on 2022-09-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_auto_20220928_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_marginmaster',
            name='CommonID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='m_mrpmaster',
            name='CommonID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
