# Generated by Django 3.0.8 on 2022-12-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_auto_20221216_1458'),
        ('FoodERPApp', '0004_tc_orderitems_deletedon'),
    ]

    operations = [
    ]
