# Generated by Django 3.0.8 on 2023-06-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_auto_20230613_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='QtyInBox',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='QtyInKg',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='QtyInNo',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
