# Generated by Django 3.0.8 on 2023-03-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_auto_20230309_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_drivers',
            name='Party',
        ),
    ]
