# Generated by Django 3.0.8 on 2022-09-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_m_controltypemaster_m_fieldvalidations'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_PageFieldMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FieldLabel', models.CharField(max_length=300)),
                ('IsCompulsory', models.BooleanField(default=False)),
                ('ListPageSeq', models.IntegerField()),
                ('ShowInListPage', models.BooleanField(default=False)),
                ('ShowInDownload', models.BooleanField(default=False)),
                ('DownloadDefaultSelect', models.BooleanField(default=False)),
                ('LinktoField', models.CharField(max_length=300)),
                ('ControlType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ControlType', to='FoodERPApp.M_ControlTypeMaster')),
                ('FieldValidation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='FieldValidation', to='FoodERPApp.M_FieldValidations')),
            ],
            options={
                'db_table': 'MC_PageFieldMaster',
            },
        ),
    ]
