# Generated by Django 3.0.8 on 2022-05-31 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_t_orders_tc_orderitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Pages',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('DisplayIndex', models.IntegerField()),
                ('Icon', models.CharField(max_length=100)),
                ('ActualPagePath', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='M_PagesModule', to='FoodERPApp.H_Modules')),
            ],
            options={
                'db_table': 'M_Pages',
            },
        ),
        migrations.RemoveField(
            model_name='h_pages',
            name='Module',
        ),
        migrations.RemoveField(
            model_name='h_pages',
            name='SubModule',
        ),
        migrations.RemoveField(
            model_name='m_roleaccess',
            name='SubModule',
        ),
        migrations.DeleteModel(
            name='H_SubModules',
        ),
        migrations.AlterField(
            model_name='hc_pageaccessitems',
            name='PageID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Pages'),
        ),
        migrations.AlterField(
            model_name='m_roleaccess',
            name='Pages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pages', to='FoodERPApp.M_Pages'),
        ),
        migrations.DeleteModel(
            name='H_Pages',
        ),
    ]
