# Generated by Django 3.0.8 on 2023-04-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_remove_t_creditdebitnotes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_invoices',
            name='IsLoadingSheetCreated',
        ),
    ]
