# Generated by Django 3.0.8 on 2023-05-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0009_o_batchwiselivestock_purchasereturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o_batchwiselivestock',
            name='PurchaseReturn',
        ),
    ]
