# Generated by Django 3.0.8 on 2022-09-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_auto_20220928_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_itemgsthsncode',
            name='CommonID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
