# Generated by Django 3.0.8 on 2023-05-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_auto_20230512_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_partybanks',
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='mc_partybanks',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='mc_partybanks',
            name='Party',
        ),
    ]
