# Generated by Django 3.0.8 on 2023-03-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_auto_20230311_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_LoadingSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('No', models.CharField(max_length=500)),
                ('InvoiceCount', models.IntegerField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoadingSheetDriver', to='FoodERPApp.M_Drivers')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoadingSheetParty', to='FoodERPApp.M_Parties')),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoadingSheetRoute', to='FoodERPApp.M_Routes')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoadingSheetVehicle', to='FoodERPApp.M_Vehicles')),
            ],
            options={
                'db_table': 'T_LoadingSheet',
            },
        ),
        migrations.CreateModel(
            name='TC_LoadingSheetDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LoadingSheetInvoice', to='FoodERPApp.T_Invoices')),
                ('LoadingSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoadingSheetDetails', to='FoodERPApp.T_LoadingSheet')),
            ],
            options={
                'db_table': 'TC_LoadingSheetDetails',
            },
        ),
    ]
