# Generated by Django 3.0.8 on 2022-09-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_mc_pagefieldmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_pagefieldmaster',
            name='LinktoField',
        ),
        migrations.AddField(
            model_name='mc_pagefieldmaster',
            name='Page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Page', to='FoodERPApp.M_Pages'),
            preserve_default=False,
        ),
    ]
