# Generated by Django 3.0.8 on 2023-01-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_auto_20221230_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o_batchwiselivestock',
            name='TransactionID',
        ),
        migrations.RemoveField(
            model_name='o_batchwiselivestock',
            name='TransactionType',
        ),
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='GRN',
            field=models.ForeignKey(default=377, on_delete=django.db.models.deletion.PROTECT, related_name='BatchWiseLiveStockGRNID', to='FoodERPApp.T_GRNs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='Production',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='BatchWiseLiveStockProductionID', to='FoodERPApp.T_Production'),
            preserve_default=False,
        ),
    ]
