# Generated by Django 3.0.8 on 2022-07-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_h_pageaccess_displayindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='h_pageaccess',
            old_name='DisplayIndex',
            new_name='Sequence',
        ),
    ]
