# Generated by Django 3.0.8 on 2022-05-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_auto_20220531_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HC_PageAccessItems',
            new_name='MC_PagePageAccess',
        ),
        migrations.AlterModelTable(
            name='mc_pagepageaccess',
            table='MC_PagePageAccess',
        ),
    ]
