# Generated by Django 3.0.8 on 2023-05-10 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_remove_o_batchwiselivestock_purchasereturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='PurchaseReturn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BatchWiseLiveStockPurchaseReturnID', to='FoodERPApp.T_PurchaseReturn'),
        ),
    ]
