# Generated by Django 3.0.8 on 2023-03-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_remove_m_drivers_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_drivers',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DParty', to='FoodERPApp.M_Parties'),
        ),
    ]
