# Generated by Django 3.0.8 on 2023-04-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_auto_20230412_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partybanks',
            name='IsDefault',
            field=models.BooleanField(default=False),
        ),
    ]
