# Generated by Django 3.0.8 on 2023-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_auto_20230614_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partysubparty',
            name='Distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
