# Generated by Django 3.0.8 on 2023-04-05 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_auto_20230405_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_receipts',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_receipts',
            name='ReceiptNo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='t_receipts',
            name='UpdatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_receipts',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
