# Generated by Django 3.0.8 on 2022-12-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_merge_20221217_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductionDate', models.DateField()),
                ('EstimatedQuantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('NumberOfLot', models.IntegerField()),
                ('ActualQuantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('BatchDate', models.DateField()),
                ('BatchCode', models.CharField(max_length=500)),
                ('StoreLocation', models.CharField(max_length=500)),
                ('SupplierBatchCode', models.CharField(max_length=500)),
                ('BestBefore', models.DateField()),
                ('Remark', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.C_Companies')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Parties')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'T_Production',
            },
        ),
        migrations.CreateModel(
            name='TC_ProductionMaterialIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaterialIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MaterialIssue', to='FoodERPApp.T_MaterialIssue')),
                ('Production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductionMaterialIssue', to='FoodERPApp.T_Production')),
            ],
            options={
                'db_table': 'TC_ProductionMaterialIssue',
            },
        ),
    ]
