# Generated by Django 3.0.8 on 2022-08-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0010_m_employeetypes_isscm'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employeetypes',
            name='Description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
