# Generated by Django 3.0.8 on 2023-03-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0011_t_loadingsheet_tc_loadingsheetdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_bank',
            name='Company',
        ),
    ]
