# Generated by Django 3.0.8 on 2022-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0011_auto_20220531_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_pages',
            name='PageList',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_pages',
            name='PageType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_pages',
            name='isShowOnMenu',
            field=models.BooleanField(default=False),
        ),
    ]
