# Generated by Django 3.0.8 on 2022-07-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0011_auto_20220722_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_pagepageaccess',
            name='Access',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.H_PageAccess'),
            preserve_default=False,
        ),
    ]
