# Generated by Django 3.0.8 on 2023-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0011_mc_partysubparty_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='BaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='BasicAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='CGST',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='CGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='DiscountAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='GSTAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='IGST',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='IGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='MRPValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='SGST',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='SGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
