# Generated by Django 3.0.8 on 2022-08-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0011_m_employeetypes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employeetypes',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
