# Generated by Django 3.0.8 on 2023-04-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0011_auto_20230405_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_receipts',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='t_receipts',
            name='UpdatedOn',
        ),
    ]
