# Generated by Django 3.0.8 on 2022-11-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0011_auto_20221108_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_ordertermsandconditions',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderTermsAndConditions', to='FoodERPApp.T_Orders'),
        ),
    ]
