# Generated by Django 3.0.8 on 2022-09-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0007_merge_20220901_1731'),
        ('FoodERPApp', '0011_auto_20220906_1630'),
    ]

    operations = [
    ]
