# Generated by Django 3.0.8 on 2023-04-13 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0011_mc_partybanks_isdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_bank',
            name='Company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
