# Generated by Django 3.0.8 on 2022-09-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0011_auto_20220906_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_pagefieldmaster',
            name='Page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PageFieldMaster', to='FoodERPApp.M_Pages'),
        ),
    ]
