# Generated by Django 3.0.8 on 2022-12-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0011_t_production_tc_productionmaterialissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='GST',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ObatchwiseItemGst', to='FoodERPApp.M_GSTHSNCode'),
        ),
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
