# Generated by Django 3.0.8 on 2023-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_auto_20230405_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_receipts',
            name='UpdatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_receipts',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
