# Generated by Django 3.0.8 on 2023-05-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_auto_20230512_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_PartyBanks',
        ),
    ]
