# Generated by Django 3.0.8 on 2022-07-25 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_auto_20220722_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='IsSCM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IsSCM', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
