# Generated by Django 4.2 on 2023-05-29 15:02

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_m_items_breadth_m_items_grammage_m_items_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_items',
            name='Breadth',
        ),
        migrations.RemoveField(
            model_name='m_items',
            name='Grammage',
        ),
        migrations.RemoveField(
            model_name='m_items',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='m_items',
            name='Length',
        ),
        migrations.RemoveField(
            model_name='m_items',
            name='StoringCondition',
        ),
    ]
