# Generated by Django 3.0.8 on 2022-08-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_auto_20220804_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abc',
            name='SurName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abc',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
