# Generated by Django 3.0.8 on 2022-11-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_auto_20221108_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartiesCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='PartyType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyType', to='FoodERPApp.M_PartyType'),
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='PriceList',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyPriceList', to='FoodERPApp.M_PriceList'),
        ),
    ]
