# Generated by Django 3.0.8 on 2022-09-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_merge_20220907_1206'),
        ('FoodERPApp', '0012_auto_20220907_1311'),
    ]

    operations = [
    ]
