# Generated by Django 3.0.8 on 2022-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_mc_pagefieldmaster_invalidmsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_pagefieldmaster',
            name='InValidMsg',
        ),
        migrations.AddField(
            model_name='m_fieldvalidations',
            name='InValidMsg',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
