# Generated by Django 3.0.8 on 2022-06-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_auto_20220603_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Designations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_Designations',
            },
        ),
        migrations.CreateModel(
            name='M_Employess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('BOD', models.DateField(blank=True, null=True)),
                ('PAN', models.CharField(max_length=100)),
                ('AadharNo', models.CharField(max_length=100)),
                ('EmployeeType', models.IntegerField()),
                ('JoiningDate', models.IntegerField(blank=True, null=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('DesignationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Designation', to='FoodERPApp.M_Designations')),
            ],
            options={
                'db_table': 'M_Employess',
            },
        ),
    ]
