# Generated by Django 3.0.8 on 2023-03-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_auto_20230309_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_vehicles',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='m_vehicles',
            name='Party',
        ),
    ]
