# Generated by Django 3.0.8 on 2022-11-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_auto_20221108_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='file',
        ),
        migrations.RemoveField(
            model_name='abc',
            name='picture',
        ),
    ]
