# Generated by Django 3.0.8 on 2023-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_auto_20230102_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_orders',
            name='Inward',
        ),
        migrations.AddField(
            model_name='tc_grnreferences',
            name='Inward',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
