# Generated by Django 3.0.8 on 2022-07-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0012_m_items_baseunitid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_items',
            name='BaseunitID',
        ),
    ]
