# Generated by Django 3.0.8 on 2023-03-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_m_bank_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partytype',
            name='IsVendor',
            field=models.BooleanField(default=False),
        ),
    ]
