# Generated by Django 3.0.8 on 2023-04-15 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_tc_receiptinvoices_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_receiptinvoices',
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='tc_receiptinvoices',
            name='flag',
        ),
        migrations.CreateModel(
            name='TC_PaymentReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_Receipts')),
                ('Receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentReceipt', to='FoodERPApp.T_Receipts')),
            ],
            options={
                'db_table': 'TC_PaymentReceipt',
            },
        ),
    ]
