# Generated by Django 3.0.8 on 2022-09-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_auto_20220929_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'M_TermsAndConditions',
            },
        ),
    ]
