# Generated by Django 3.0.8 on 2023-03-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_auto_20230309_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_vehicles',
            name='Company',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='VCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_vehicles',
            name='Party',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='VParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
