# Generated by Django 3.0.8 on 2022-09-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_merge_20220907_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_pages',
            name='IsDivisionRequired',
            field=models.BooleanField(default=False),
        ),
    ]
