# Generated by Django 3.0.8 on 2022-07-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_remove_m_items_baseunitid'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='BaseUnitID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='BaseUnitID', to='FoodERPApp.M_Units'),
            preserve_default=False,
        ),
    ]
