# Generated by Django 3.0.8 on 2022-06-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_m_designations_m_employess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employess',
            name='JoiningDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
