# Generated by Django 3.0.8 on 2022-08-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_auto_20220810_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employees',
            name='Designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='EmployeesDesignation', to='FoodERPApp.M_Designations'),
        ),
        migrations.AlterField(
            model_name='mc_employeeparties',
            name='Party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Employeeparty', to='FoodERPApp.M_Parties'),
        ),
    ]
