# Generated by Django 3.0.8 on 2023-04-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_auto_20230405_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_receipts',
            name='FullReceiptNumber',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
