# Generated by Django 3.0.8 on 2022-11-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_auto_20221109_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='OrderType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_orders',
            name='POType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
