# Generated by Django 3.0.8 on 2023-01-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_auto_20230103_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnreferences',
            name='Invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_Invoices'),
        ),
        migrations.AlterField(
            model_name='tc_grnreferences',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OrderReferences', to='FoodERPApp.T_Orders'),
        ),
    ]
