# Generated by Django 3.0.8 on 2022-11-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0014_auto_20221109_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='Division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderDivision', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_orders',
            name='FullOrderNumber',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_orders',
            name='OrderNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
