# Generated by Django 3.0.8 on 2022-07-02 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0014_m_items_baseunitid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_ItemUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IsBase', models.IntegerField()),
                ('IsDefault', models.IntegerField()),
                ('IsSSUnit', models.IntegerField()),
                ('IsDeleted', models.BooleanField(default=False)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemUnitsItemID', to='FoodERPApp.M_Items')),
                ('UnitID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='UnitID', to='FoodERPApp.M_Units')),
            ],
            options={
                'db_table': 'MC_ItemUnits',
            },
        ),
        migrations.AddField(
            model_name='tc_invoiceitembatches',
            name='UnitID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceBatchUnitID', to='FoodERPApp.MC_ItemUnits'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='UnitID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceUnitID', to='FoodERPApp.MC_ItemUnits'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='UnitID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderUnitID', to='FoodERPApp.MC_ItemUnits'),
            preserve_default=False,
        ),
    ]
