# Generated by Django 3.0.8 on 2023-04-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0014_t_receipts_fullreceiptnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_receipts',
            name='ReceiptMode',
        ),
    ]
