# Generated by Django 3.0.8 on 2022-06-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0014_auto_20220609_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employess',
            name='JoiningDate',
            field=models.DateField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_employess',
            name='UpdatedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
