# Generated by Django 3.0.8 on 2022-08-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0014_auto_20220816_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_ProductCategory',
            },
        ),
        migrations.CreateModel(
            name='M_ProductCategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_ProductCategoryType',
            },
        ),
        migrations.CreateModel(
            name='M_ProductSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductCategory', to='FoodERPApp.M_ProductCategory')),
            ],
            options={
                'db_table': 'M_ProductSubCategory',
            },
        ),
        migrations.AddField(
            model_name='m_productcategory',
            name='ProductCategoryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductCategoryType', to='FoodERPApp.M_ProductCategoryType'),
        ),
    ]
