# Generated by Django 3.0.8 on 2023-03-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0014_m_partytype_isvendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_InvoiceType',
        ),
    ]
