# Generated by Django 3.0.8 on 2023-04-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0014_auto_20230415_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_paymentreceipt',
            name='Receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentReceipt', to='FoodERPApp.T_Receipts'),
        ),
    ]
