# Generated by Django 3.0.8 on 2023-01-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0014_auto_20230103_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnreferences',
            name='Inward',
            field=models.BooleanField(default=False),
        ),
    ]
