# Generated by Django 3.0.8 on 2023-03-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0014_auto_20230309_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_vehicletypes',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='m_vehicletypes',
            name='Party',
        ),
    ]
