# Generated by Django 3.0.8 on 2022-09-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0014_m_pages_isdivisionrequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_roles',
            name='IsPartyConnection',
            field=models.BooleanField(default=False),
        ),
    ]
