# Generated by Django 3.0.8 on 2022-12-20 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0015_o_batchwiselivestock_grn'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_POType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.C_Companies')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'M_POType',
            },
        ),
        migrations.CreateModel(
            name='M_InvoiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.C_Companies')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'M_InvoiceType',
            },
        ),
    ]
