# Generated by Django 3.0.8 on 2022-07-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0015_auto_20220702_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='CreatedBy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='UpdatedBy',
            field=models.IntegerField(),
        ),
    ]
