# Generated by Django 3.0.8 on 2022-09-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0015_m_roles_ispartyconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_pagefieldmaster',
            name='Page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PageFieldMaster', to='FoodERPApp.M_Pages'),
        ),
    ]
