# Generated by Django 3.0.8 on 2022-08-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0015_auto_20220818_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_items',
            name='ShortName',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_productcategory',
            name='ProductCategoryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProductCategoryType', to='FoodERPApp.M_ProductCategoryType'),
        ),
        migrations.AlterField(
            model_name='m_productsubcategory',
            name='ProductCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProductCategory', to='FoodERPApp.M_ProductCategory'),
        ),
        migrations.CreateModel(
            name='M_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProductItem', to='FoodERPApp.M_Items')),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MProductCategory', to='FoodERPApp.M_ProductCategory')),
            ],
        ),
    ]
