# Generated by Django 3.0.8 on 2022-06-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0015_auto_20220609_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_employess',
            name='JoiningDate',
        ),
        migrations.RemoveField(
            model_name='m_employess',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='m_employess',
            name='UpdatedOn',
        ),
    ]
