# Generated by Django 3.0.8 on 2022-11-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0015_auto_20221109_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='BillingAddress',
            field=models.ForeignKey(default=64, on_delete=django.db.models.deletion.PROTECT, related_name='OrderBillingAddress', to='FoodERPApp.MC_PartyAddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_orders',
            name='ShippingAddress',
            field=models.ForeignKey(default=64, on_delete=django.db.models.deletion.PROTECT, related_name='OrderShippingAddress', to='FoodERPApp.MC_PartyAddress'),
            preserve_default=False,
        ),
    ]
