# Generated by Django 3.0.8 on 2023-01-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0015_auto_20230103_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='OriginalBaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
