# Generated by Django 3.0.8 on 2023-05-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0015_auto_20230510_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='o_batchwiselivestock',
            old_name='PurchaseReturn',
            new_name='PurchaseReturnID',
        ),
    ]
