# Generated by Django 3.0.8 on 2023-05-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0015_remove_m_importfields_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_importfields',
            name='Company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='ImportFieldCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
