# Generated by Django 3.0.8 on 2023-03-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0015_delete_m_invoicetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_TransactionType',
        ),
    ]
