# Generated by Django 3.0.8 on 2022-10-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_m_categorytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('CategoryType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CategoryType', to='FoodERPApp.M_CategoryType')),
            ],
            options={
                'db_table': 'M_Category',
            },
        ),
    ]
