# Generated by Django 3.0.8 on 2022-08-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_auto_20220818_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='BarCode',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_items',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='m_products',
            table='M_Products',
        ),
    ]
