# Generated by Django 3.0.8 on 2022-07-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_mc_userroles_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_employees',
            name='Party',
        ),
    ]
