# Generated by Django 3.0.8 on 2023-01-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_o_batchwiselivestock_originalbaseunitquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_pages',
            name='CountLabel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_pages',
            name='ShowCountLabel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
