# Generated by Django 3.0.8 on 2022-11-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0013_auto_20221109_1222'),
        ('FoodERPApp', '0016_auto_20221110_1254'),
    ]

    operations = [
    ]
