# Generated by Django 3.0.8 on 2023-04-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_auto_20230406_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_invoices',
            name='Driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InvoiceDriver', to='FoodERPApp.M_Drivers'),
        ),
        migrations.AddField(
            model_name='t_invoices',
            name='Vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InvoiceVehicle', to='FoodERPApp.M_Vehicles'),
        ),
    ]
