# Generated by Django 3.0.8 on 2022-12-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_m_invoicetype_m_potype'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_termsandconditions',
            name='IsDefault',
            field=models.BooleanField(default=False),
        ),
    ]
