# Generated by Django 3.0.8 on 2023-05-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_auto_20230510_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='o_batchwiselivestock',
            old_name='PurchaseReturnID',
            new_name='PurchaseReturn',
        ),
    ]
