# Generated by Django 3.0.8 on 2023-03-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_auto_20230309_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_items',
            name='IsSCM',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='IsSCM',
        ),
    ]
