# Generated by Django 3.0.8 on 2023-04-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_mc_partybanks_customerbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='ReturnReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Returnreason', to='FoodERPApp.M_GeneralMaster'),
        ),
    ]
