# Generated by Django 3.0.8 on 2022-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_auto_20220914_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_pagefieldmaster',
            name='ControlID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_pagefieldmaster',
            name='DefaultSort',
            field=models.BooleanField(default=False),
        ),
    ]
