# Generated by Django 3.0.8 on 2023-05-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0016_m_importfields_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_importfields',
            name='Company',
        ),
    ]
