# Generated by Django 3.0.8 on 2023-05-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_auto_20230510_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_bank',
            name='Company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='CompanyBank', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mc_partybanks',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartyCompanyBank', to='FoodERPApp.C_Companies'),
        ),
    ]
