# Generated by Django 3.0.8 on 2022-07-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_auto_20220702_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_userroles',
            name='RoleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserRoleID', to='FoodERPApp.M_Roles'),
        ),
        migrations.AlterField(
            model_name='mc_userroles',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserID', to=settings.AUTH_USER_MODEL),
        ),
    ]
