# Generated by Django 3.0.8 on 2022-09-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_auto_20220915_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_fieldvalidations',
            name='ControlType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='FieldControlType', to='FoodERPApp.M_ControlTypeMaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_fieldvalidations',
            name='RegularExpression',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
