# Generated by Django 3.0.8 on 2022-07-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_remove_m_employees_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_userroles',
            name='Party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userparty', to='FoodERPApp.M_Parties'),
        ),
    ]
