# Generated by Django 3.0.8 on 2023-05-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_remove_m_importfields_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='Breadth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='m_items',
            name='Grammage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='m_items',
            name='Height',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='m_items',
            name='Length',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='m_items',
            name='StoringCondition',
            field=models.IntegerField(default=False),
        ),
    ]
