# Generated by Django 3.0.8 on 2022-08-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_auto_20220818_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_ItemsGMMH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Margin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('HSNCode', models.CharField(max_length=500)),
                ('FromDate', models.DateTimeField()),
                ('ToDate', models.DateTimeField()),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGstDetails', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemsGMMH',
            },
        ),
    ]
