# Generated by Django 3.0.8 on 2022-11-11 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_merge_20221111_1153'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='t_orders',
            name='DeliveryDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
