# Generated by Django 3.0.8 on 2023-06-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_auto_20230619_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='QtyInBox',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='QtyInKg',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='QtyInNo',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
