# Generated by Django 3.0.8 on 2023-04-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_tc_purchasereturnitems_returnreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ImportFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FieldName', models.CharField(max_length=500)),
                ('IsCompulsory', models.BooleanField(default=False)),
                ('FieldDataType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ImportFieldValidation', to='FoodERPApp.M_FieldValidations')),
            ],
            options={
                'db_table': 'M_ImportFields',
            },
        ),
        migrations.CreateModel(
            name='MC_PartyImportFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=500)),
                ('ImportField', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ImportFields', to='FoodERPApp.M_ImportFields')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartyImport', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'MC_PartyImportFields',
            },
        ),
    ]
