# Generated by Django 3.0.8 on 2023-03-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_auto_20230309_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_loadingsheet',
            name='InvoiceCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_loadingsheet',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
