# Generated by Django 3.0.8 on 2022-12-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0017_m_termsandconditions_isdefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='GRN',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GRN', to='FoodERPApp.T_GRNs'),
        ),
    ]
