# Generated by Django 3.0.8 on 2023-06-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0018_auto_20230619_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactionlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TranasactionDate', models.DateTimeField(auto_now_add=True)),
                ('Transactiontime', models.DateTimeField(auto_now_add=True)),
                ('User', models.IntegerField()),
                ('IPaddress', models.CharField(max_length=500)),
                ('PartyID', models.IntegerField()),
                ('TransactionDetails', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Transactionlog',
            },
        ),
    ]
