# Generated by Django 3.0.8 on 2022-12-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0018_auto_20221221_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='POType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderPOType', to='FoodERPApp.M_POType'),
        ),
    ]
