# Generated by Django 3.0.8 on 2022-11-11 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0018_auto_20221111_1154'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='mc_partyaddress',
            name='AddressType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='AddressType', to='FoodERPApp.M_AddressTypes'),
        ),
    ]
