# Generated by Django 3.0.8 on 2022-07-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0018_auto_20220702_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_userroles',
            name='RoleID',
        ),
        migrations.RemoveField(
            model_name='mc_userroles',
            name='UserID',
        ),
    ]
