# Generated by Django 3.0.8 on 2023-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0018_auto_20230407_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_receipts',
            name='ChequeDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
