# Generated by Django 3.0.8 on 2023-04-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0018_m_importfields_mc_partyimportfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='ImportField',
        ),
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='Party',
        ),
        migrations.DeleteModel(
            name='M_ImportFields',
        ),
        migrations.DeleteModel(
            name='MC_PartyImportFields',
        ),
    ]
