# Generated by Django 3.0.8 on 2022-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0018_mc_itemsgmmh'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_ItemsShelfLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Days', models.IntegerField(default=False)),
            ],
        ),
    ]
