# Generated by Django 3.0.8 on 2022-09-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0018_auto_20220915_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_rolesemployeetypes',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoleEmployeeTypes', to='FoodERPApp.M_Roles'),
        ),
    ]
