# Generated by Django 3.0.8 on 2022-08-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0019_mc_itemsshelflife'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mc_itemsshelflife',
            table='MC_ItemsShelfLife',
        ),
    ]
