# Generated by Django 3.0.8 on 2023-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0019_m_importfields_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='SAPResponse',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
