# Generated by Django 3.0.8 on 2022-06-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0019_m_employess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employess',
            name='BOD',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
