# Generated by Django 3.0.8 on 2023-06-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0019_transactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='TranasactionDate',
            field=models.DateField(),
        ),
    ]
