# Generated by Django 3.0.8 on 2023-03-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0019_auto_20230310_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_loadingsheet',
            name='Driver',
        ),
        migrations.RemoveField(
            model_name='t_loadingsheet',
            name='Vehicle',
        ),
    ]
