# Generated by Django 3.0.8 on 2022-11-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0019_auto_20221111_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_PartyPrefixs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orderprefix', models.CharField(max_length=500)),
                ('Invoiceprefix', models.CharField(max_length=500)),
                ('Grnprefix', models.CharField(max_length=500)),
                ('Receiptprefix', models.CharField(max_length=500)),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyPrefix', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'MC_PartyPrefixs',
            },
        ),
        migrations.DeleteModel(
            name='Abc',
        ),
    ]
