# Generated by Django 3.0.8 on 2022-09-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0019_auto_20220916_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'AddressTypes',
            },
        ),
    ]
