# Generated by Django 3.0.8 on 2022-08-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_auto_20220822_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_items',
            name='GSTPercentage',
        ),
        migrations.RemoveField(
            model_name='m_items',
            name='ItemGroup',
        ),
        migrations.RemoveField(
            model_name='m_items',
            name='MRP',
        ),
        migrations.RemoveField(
            model_name='m_items',
            name='Rate',
        ),
    ]
