# Generated by Django 3.0.8 on 2023-05-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_t_orders_sapresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='SAPResponse',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
