# Generated by Django 3.0.8 on 2023-01-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_auto_20230106_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_workorder',
            name='FullWorkOrderNumber',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_workorder',
            name='WorkOrderNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
