# Generated by Django 3.0.8 on 2022-09-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_addresstypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressTypes',
            new_name='M_AddressTypes',
        ),
        migrations.AlterModelTable(
            name='m_addresstypes',
            table='M_AddressTypes',
        ),
    ]
