# Generated by Django 3.0.8 on 2023-03-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_auto_20230310_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_loadingsheet',
            name='Driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='LoadingSheetDriver', to='FoodERPApp.M_Drivers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_loadingsheet',
            name='Vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='LoadingSheetVehicle', to='FoodERPApp.M_Vehicles'),
            preserve_default=False,
        ),
    ]
