# Generated by Django 3.0.8 on 2023-04-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_auto_20230407_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_receipts',
            name='ChequeDate',
        ),
    ]
