# Generated by Django 3.0.8 on 2022-06-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_auto_20220609_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_employess',
            old_name='BOD',
            new_name='DOB',
        ),
    ]
