# Generated by Django 3.0.8 on 2023-06-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_auto_20230619_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='JsonData',
            field=models.TextField(blank=True),
        ),
    ]
