# Generated by Django 3.0.8 on 2023-04-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_m_importfields_mc_partyimportfields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_importfields',
            old_name='FieldDataType',
            new_name='FieldValidation',
        ),
    ]
