# Generated by Django 3.0.8 on 2022-10-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_mc_subgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_group',
            name='GroupType',
        ),
        migrations.RemoveField(
            model_name='mc_subgroup',
            name='Group',
        ),
        migrations.DeleteModel(
            name='M_Category',
        ),
        migrations.DeleteModel(
            name='M_CategoryType',
        ),
        migrations.DeleteModel(
            name='M_Group',
        ),
        migrations.DeleteModel(
            name='M_GroupType',
        ),
        migrations.DeleteModel(
            name='MC_SubGroup',
        ),
    ]
