# Generated by Django 3.0.8 on 2022-11-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0020_auto_20221111_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_grnitems',
            name='BatchCode',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_grnitems',
            name='BatchDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
