# Generated by Django 3.0.8 on 2023-05-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0021_auto_20230531_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_importfields',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='t_orders',
            name='SAPResponse',
        ),
    ]
