# Generated by Django 3.0.8 on 2022-06-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0021_auto_20220609_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employess',
            name='AadharNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='m_employess',
            name='Mobile',
            field=models.IntegerField(),
        ),
    ]
