# Generated by Django 3.0.8 on 2022-11-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0021_auto_20221114_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_DeliveryChallans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChallanDate', models.DateField()),
                ('ChallanNumber', models.IntegerField()),
                ('GrandTotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DeliveryCustomer', to='FoodERPApp.M_Parties')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DeliveryParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'T_DeliveryChallans',
            },
        ),
        migrations.CreateModel(
            name='TC_DeliveryChallanReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryChallan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeiveryChallanReferences', to='FoodERPApp.T_DeliveryChallans')),
                ('GRN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.T_GRNs')),
            ],
            options={
                'db_table': 'TC_DeliveryChallanReferences',
            },
        ),
        migrations.CreateModel(
            name='TC_DeliveryChallanItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ReferenceRate', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DiscountType', models.CharField(max_length=500)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('DeliveryChallan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryChallanItems', to='FoodERPApp.T_DeliveryChallans')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_Items')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DeliveryChallanUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'TC_DeliveryChallanItems',
            },
        ),
    ]
