# Generated by Django 3.0.8 on 2022-09-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0021_auto_20220916_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_divisiontype',
            name='IsDivision',
            field=models.BooleanField(default=False),
        ),
    ]
