# Generated by Django 3.0.8 on 2023-04-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0021_auto_20230418_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_importfields',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_partyimportfields',
            name='Company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
