# Generated by Django 3.0.8 on 2022-08-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0021_auto_20220822_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='ItemGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGroup', to='FoodERPApp.M_ItemsGroup'),
            preserve_default=False,
        ),
    ]
