# Generated by Django 3.0.8 on 2023-04-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0021_remove_t_receipts_chequedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_receipts',
            name='ChequeDate',
            field=models.DateField(default=False),
        ),
    ]
