# Generated by Django 3.0.8 on 2022-07-02 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0021_auto_20220702_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_userroles',
            name='Role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Userrole', to='FoodERPApp.M_Roles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_userroles',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
