# Generated by Django 3.0.8 on 2023-01-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0021_auto_20230106_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_workorder',
            old_name='WorkOrderNo',
            new_name='WorkOrderNumber',
        ),
    ]
