# Generated by Django 3.0.8 on 2023-04-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0022_auto_20230418_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_importfields',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='mc_partyimportfields',
            name='Company',
        ),
    ]
