# Generated by Django 3.0.8 on 2023-04-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0022_t_receipts_chequedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_receipts',
            name='ChequeDate',
            field=models.DateField(null=True),
        ),
    ]
