# Generated by Django 3.0.8 on 2023-03-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0022_m_bank_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partytype',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='PartyTypeCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_partytype',
            name='IsRetailer',
            field=models.BooleanField(default=False),
        ),
    ]
