# Generated by Django 3.0.8 on 2022-11-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0022_t_deliverychallans_tc_deliverychallanitems_tc_deliverychallanreferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TC_GRNItemBatches',
        ),
    ]
