# Generated by Django 3.0.8 on 2022-07-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0022_auto_20220702_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_userroles',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='mc_userroles',
            name='User',
        ),
    ]
