# Generated by Django 3.0.8 on 2023-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0022_auto_20230106_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partyprefixs',
            name='WorkOrderprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
