# Generated by Django 3.0.8 on 2022-11-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0023_delete_tc_grnitembatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_deliverychallans',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DeliveryCustomer', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_deliverychallans',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DeliveryParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_grns',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GRNCustomer', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_grns',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GRNParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='tc_deliverychallanitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='tc_deliverychallanitems',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DeliveryChallanUnitID', to='FoodERPApp.MC_ItemUnits'),
        ),
        migrations.AlterField(
            model_name='tc_deliverychallanreferences',
            name='DeliveryChallan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DeliveryChallanReferences', to='FoodERPApp.T_DeliveryChallans'),
        ),
        migrations.AlterField(
            model_name='tc_deliverychallanreferences',
            name='GRN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_GRNs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GRNUnitID', to='FoodERPApp.MC_ItemUnits'),
        ),
    ]
