# Generated by Django 3.0.8 on 2022-08-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0023_auto_20220822_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_ItemCategoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProductItem', to='FoodERPApp.M_Items')),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MProductCategory', to='FoodERPApp.M_ProductCategory')),
            ],
            options={
                'db_table': 'MC_ItemCategoryDetails',
            },
        ),
        migrations.DeleteModel(
            name='M_Products',
        ),
    ]
