# Generated by Django 3.0.8 on 2023-06-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0023_tc_invoiceuploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_invoiceuploads',
            name='Invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InvoiceUploads', to='FoodERPApp.T_Invoices'),
        ),
    ]
