# Generated by Django 3.0.8 on 2023-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0023_auto_20230407_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_receipts',
            name='ChequeDate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
