# Generated by Django 3.0.8 on 2022-12-21 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0023_auto_20221221_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_drivers',
            name='CreatedBy',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_drivers',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_drivers',
            name='UpdatedBy',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_drivers',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
