# Generated by Django 3.0.8 on 2023-03-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0023_auto_20230310_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employeetypes',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Emp_Company', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
