# Generated by Django 3.0.8 on 2022-09-17 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0024_mc_partyaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_pagefieldmaster',
            name='Page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PageFieldMaster', to='FoodERPApp.M_Pages'),
            preserve_default=False,
        ),
    ]
