# Generated by Django 3.0.8 on 2023-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0024_m_employeetypes_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='IsRetailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_parties',
            name='IsSCM',
            field=models.BooleanField(default=False),
        ),
    ]
