# Generated by Django 3.0.8 on 2023-06-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0024_auto_20230621_1535'),
    ]
    operations = [
        migrations.AddField(
            model_name='m_units',
            name='EwayBillUnit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
