# Generated by Django 3.0.8 on 2023-05-31 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0024_auto_20230531_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_importfields',
            name='Company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='ImportFieldCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_orders',
            name='SAPResponse',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
