# Generated by Django 3.0.8 on 2022-11-17 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0024_auto_20221114_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='PriceList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyPriceList', to='FoodERPApp.M_PriceList'),
        ),
    ]
