# Generated by Django 3.0.8 on 2023-04-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0024_auto_20230418_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_PurchaseReturnItemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_pic', models.TextField()),
                ('ImageType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RImageType', to='FoodERPApp.M_ImageTypes')),
                ('PurchaseReturnItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReturnitemsImages', to='FoodERPApp.TC_PurchaseReturnItems')),
            ],
            options={
                'db_table': 'TC_PurchaseReturnItemImages',
            },
        ),
    ]
