# Generated by Django 3.0.8 on 2022-10-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0024_auto_20221004_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_itemcategorydetails',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemCategory', to='FoodERPApp.M_Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_itemcategorydetails',
            name='CategoryType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemCategoryType', to='FoodERPApp.M_CategoryType'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MC_GroupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGroup', to='FoodERPApp.M_Group')),
                ('GroupType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGroupType', to='FoodERPApp.M_GroupType')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemGroupDetails', to='FoodERPApp.M_Items')),
                ('SubGroup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemSubGroup', to='FoodERPApp.MC_SubGroup')),
            ],
            options={
                'db_table': 'MC_ItemGroupDetails',
            },
        ),
    ]
