# Generated by Django 3.0.8 on 2023-01-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0024_auto_20230107_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_production',
            old_name='SupplierBatchCode',
            new_name='PrintedBatchCode',
        ),
    ]
