# Generated by Django 3.0.8 on 2022-06-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0024_t_invoice_tc_invoiceitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_pages',
            name='PageList',
        ),
        migrations.AddField(
            model_name='m_pages',
            name='RelatedPageID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_pages',
            name='Module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M_PagesModule', to='FoodERPApp.H_Modules'),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Items'),
        ),
        migrations.CreateModel(
            name='TC_InvoiceItemBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('UnitID', models.IntegerField()),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_Invoice')),
                ('InvoiceItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.TC_InvoiceItems')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'TC_InvoiceItemBatches',
            },
        ),
    ]
