# Generated by Django 3.0.8 on 2023-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0025_remove_t_receipts_chequedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_receipts',
            name='ChequeDate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
