# Generated by Django 3.0.8 on 2022-10-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0025_auto_20221004_0906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MC_GroupDetails',
            new_name='MC_ItemGroupDetails',
        ),
    ]
