# Generated by Django 3.0.8 on 2022-06-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0025_auto_20220613_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TC_InvoiceItemBatches',
        ),
    ]
