# Generated by Django 3.0.8 on 2023-04-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0025_tc_purchasereturnitemimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_purchasereturnitemimages',
            name='ImageType',
        ),
    ]
