# Generated by Django 3.0.8 on 2023-03-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0025_auto_20230310_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='IsRetailer',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='IsSCM',
        ),
    ]
