# Generated by Django 3.0.8 on 2022-11-17 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0025_auto_20221117_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_itemimages',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ItemImagesDetails', to='FoodERPApp.M_Items'),
        ),
    ]
