# Generated by Django 3.0.8 on 2022-09-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0025_auto_20220917_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_pagefieldmaster',
            name='Page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PageFieldMaster', to='FoodERPApp.M_Pages'),
        ),
    ]
