# Generated by Django 3.0.8 on 2023-01-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0025_auto_20230107_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='GRN',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BatchWiseLiveStockGRNID', to='FoodERPApp.T_GRNs'),
        ),
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='Production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BatchWiseLiveStockProductionID', to='FoodERPApp.T_Production'),
        ),
    ]
