# Generated by Django 3.0.8 on 2022-08-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0025_auto_20220822_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ImageTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_ImageTypes',
            },
        ),
        migrations.AlterField(
            model_name='mc_itemunits',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemUnitsID', to='FoodERPApp.M_Items'),
        ),
        migrations.CreateModel(
            name='MC_ItemsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_pic', models.FileField(upload_to='')),
                ('ImageType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ImageType', to='FoodERPApp.M_ImageTypes')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemImagesdetails', to='FoodERPApp.M_Items')),
            ],
        ),
    ]
