# Generated by Django 3.0.8 on 2022-07-02 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0025_remove_mc_userroles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_userroles',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserRole', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
