# Generated by Django 3.0.8 on 2022-07-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_mc_userroles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_items',
            name='MRP',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
