# Generated by Django 3.0.8 on 2022-09-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_auto_20220917_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='PartyType',
        ),
        migrations.RemoveField(
            model_name='m_pricelist',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='m_pricelist',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='m_pricelist',
            name='DivisionType',
        ),
        migrations.RemoveField(
            model_name='m_pricelist',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='m_pricelist',
            name='UpdatedOn',
        ),
        migrations.AddField(
            model_name='m_parties',
            name='PriceList',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PriceList', to='FoodERPApp.M_PriceList'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_pricelist',
            name='BasePriceListID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_pricelist',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PriceListCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_pricelist',
            name='MkupMkDn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='m_pricelist',
            table=None,
        ),
        migrations.CreateModel(
            name='M_PartyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('DivisionType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyTypeDivision', to='FoodERPApp.M_DivisionType')),
            ],
            options={
                'db_table': 'M_PartyType',
            },
        ),
        migrations.AddField(
            model_name='m_pricelist',
            name='PartyType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyType', to='FoodERPApp.M_PartyType'),
            preserve_default=False,
        ),
    ]
