# Generated by Django 3.0.8 on 2023-04-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_remove_tc_purchasereturnitemimages_imagetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_purchasereturnitems',
            name='ReturnReason',
        ),
        migrations.AddField(
            model_name='t_purchasereturn',
            name='ReturnReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Returnreason', to='FoodERPApp.M_GeneralMaster'),
        ),
    ]
