# Generated by Django 3.0.8 on 2022-06-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_delete_tc_invoiceitembatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_InvoiceItemBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('UnitID', models.IntegerField()),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_Invoice')),
                ('InvoiceItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.TC_InvoiceItems')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'TC_InvoiceItemBatches',
            },
        ),
    ]
