# Generated by Django 3.0.8 on 2022-09-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_auto_20220917_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('MkupMkDn', models.IntegerField()),
                ('BasePriceListID', models.IntegerField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PriceListCompany', to='FoodERPApp.C_Companies')),
                ('PartyType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyType', to='FoodERPApp.M_PartyType')),
            ],
        ),
    ]
