# Generated by Django 3.0.8 on 2023-03-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_auto_20230310_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_partytype',
            name='IsRetailer',
        ),
    ]
