# Generated by Django 3.0.8 on 2022-10-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_auto_20221004_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_productsubcategory',
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='M_ProductCategory',
        ),
        migrations.DeleteModel(
            name='M_ProductCategoryType',
        ),
        migrations.DeleteModel(
            name='M_ProductSubCategory',
        ),
    ]
