# Generated by Django 3.0.8 on 2022-11-17 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_auto_20221117_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='PriceList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='PartyPriceList', to='FoodERPApp.M_PriceList'),
            preserve_default=False,
        ),
    ]
