# Generated by Django 3.0.8 on 2023-06-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_auto_20230621_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_invoiceuploads',
            name='EInvoicePdf',
            field=models.CharField(max_length=500),
        ),
    ]
