# Generated by Django 3.0.8 on 2023-01-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_auto_20230107_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_billofmaterial',
            name='EstimatedOutputQty',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
