# Generated by Django 3.0.8 on 2023-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_auto_20230531_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='SAPResponse',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
