# Generated by Django 3.0.8 on 2022-08-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0026_auto_20220822_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_itemcategorydetails',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='mc_itemcategorydetails',
            name='UpdatedBy',
        ),
        migrations.AlterField(
            model_name='mc_itemcategorydetails',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemCategoryDetails', to='FoodERPApp.M_Items'),
        ),
    ]
