# Generated by Django 3.0.8 on 2023-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0027_t_orders_sapresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_items',
            name='SAPItemCode',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='SAPPartyCode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
