# Generated by Django 3.0.8 on 2022-12-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0027_auto_20221221_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_drivers',
            name='CreatedBy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
