# Generated by Django 3.0.8 on 2022-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0027_auto_20221004_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_pages',
            name='IsEditPopuporComponent',
            field=models.BooleanField(default=False),
        ),
    ]
