# Generated by Django 3.0.8 on 2023-04-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0027_auto_20230420_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_purchasereturn',
            name='ReturnReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReturnReason', to='FoodERPApp.M_GeneralMaster'),
        ),
        migrations.AlterField(
            model_name='tc_purchasereturnitemimages',
            name='PurchaseReturnItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReturnItemImages', to='FoodERPApp.TC_PurchaseReturnItems'),
        ),
        migrations.AlterField(
            model_name='tc_purchasereturnitems',
            name='PurchaseReturn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReturnItems', to='FoodERPApp.T_PurchaseReturn'),
        ),
    ]
