# Generated by Django 3.0.8 on 2023-04-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0027_auto_20230407_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_creditdebitnotes',
            name='NoteType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_GeneralMaster'),
        ),
    ]
