# Generated by Django 3.0.8 on 2022-06-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0027_tc_invoiceitembatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ItemsGroup',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Sequence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isActive', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_ItemsGroup',
            },
        ),
        migrations.AlterField(
            model_name='tc_invoiceitembatches',
            name='InvoiceItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceItemBatches', to='FoodERPApp.TC_InvoiceItems'),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='InvoiceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceItems', to='FoodERPApp.T_Invoice'),
        ),
    ]
