# Generated by Django 3.0.8 on 2022-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0027_auto_20220823_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_itemsgmmh',
            name='FromDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mc_itemsgmmh',
            name='ToDate',
            field=models.DateField(),
        ),
    ]
