# Generated by Django 3.0.8 on 2022-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0027_auto_20220704_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_items',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='m_items',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
