# Generated by Django 3.0.8 on 2022-08-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0028_auto_20220823_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_itemunits',
            name='IsSSUnit',
        ),
    ]
