# Generated by Django 3.0.8 on 2022-11-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0028_auto_20221117_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='PriceList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyPriceList', to='FoodERPApp.M_PriceList'),
        ),
    ]
