# Generated by Django 3.0.8 on 2022-06-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0028_auto_20220615_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_ItemsGroup',
        ),
    ]
