# Generated by Django 3.0.8 on 2023-06-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0028_auto_20230531_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employees',
            name='City',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_employees',
            name='PIN',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
