# Generated by Django 3.0.8 on 2023-01-09 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0028_t_production_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='BillingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OrderBillingAddress', to='FoodERPApp.MC_PartyAddress'),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='OrderType',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='POFromDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='POToDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='POType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderPOType', to='FoodERPApp.M_POType'),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='ShippingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OrderShippingAddress', to='FoodERPApp.MC_PartyAddress'),
        ),
    ]
