# Generated by Django 3.0.8 on 2022-07-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0028_auto_20220704_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='UnitID',
        ),
    ]
