# Generated by Django 3.0.8 on 2023-03-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0028_m_partytype_isretailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_partytype',
            name='Company',
        ),
    ]
