# Generated by Django 3.0.8 on 2023-04-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0028_auto_20230407_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_receipts',
            name='ReceiptMode',
        ),
        migrations.RemoveField(
            model_name='t_receipts',
            name='ReceiptType',
        ),
        migrations.AddField(
            model_name='mc_partyprefixs',
            name='Creditprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mc_partyprefixs',
            name='Debitprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
