# Generated by Django 3.0.8 on 2022-09-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0028_auto_20220917_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='PartyType',
        ),
    ]
