# Generated by Django 3.0.8 on 2022-12-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0029_auto_20221221_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_ItemShelfLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.IntegerField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemShelf', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemShelfLife',
            },
        ),
        migrations.DeleteModel(
            name='M_ItemShelfLife',
        ),
    ]
