# Generated by Django 3.0.8 on 2022-08-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0029_remove_mc_itemunits_isssunit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mc_itemsimages',
            table='MC_ItemsImages',
        ),
    ]
