# Generated by Django 3.0.8 on 2022-07-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0029_remove_tc_orderitems_unitid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='Unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderUnitID', to='FoodERPApp.MC_ItemUnits'),
            preserve_default=False,
        ),
    ]
