# Generated by Django 3.0.8 on 2023-04-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0029_auto_20230420_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_purchasereturnitemimages',
            old_name='PurchaseReturnItem',
            new_name='PurchaseReturnItemImage',
        ),
    ]
