# Generated by Django 3.0.8 on 2023-03-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0029_remove_m_partytype_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partytype',
            name='Company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='PartyTypeCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
