# Generated by Django 3.0.8 on 2023-01-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0029_auto_20230109_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='OrderType',
            field=models.IntegerField(),
        ),
    ]
