# Generated by Django 3.0.8 on 2023-06-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0029_auto_20230602_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CityDistrict', to='FoodERPApp.M_Districts')),
            ],
            options={
                'db_table': 'M_Cities',
            },
        ),
    ]
