# Generated by Django 3.0.8 on 2022-09-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0029_remove_m_parties_partytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='PartyType',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyType', to='FoodERPApp.M_PartyType'),
            preserve_default=False,
        ),
    ]
