# Generated by Django 3.0.8 on 2022-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0029_auto_20221117_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_pagefieldmaster',
            name='FieldLabel',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mc_pagefieldmaster',
            name='InValidMsg',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
