# Generated by Django 3.0.8 on 2022-10-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0029_auto_20221007_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='GST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGST', to='FoodERPApp.M_GSTHSNCode'),
        ),
        migrations.DeleteModel(
            name='MC_ItemGSTHSNCode',
        ),
    ]
