# Generated by Django 3.0.8 on 2023-04-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_auto_20230420_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_purchasereturnitemimages',
            old_name='PurchaseReturnItemImage',
            new_name='PurchaseReturnItem',
        ),
    ]
