# Generated by Django 3.0.8 on 2022-06-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_m_itemsgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_ItemsGroup',
        ),
    ]
