# Generated by Django 3.0.8 on 2022-12-22 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_auto_20221222_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='BrandName',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_items',
            name='Tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
