# Generated by Django 3.0.8 on 2022-08-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_auto_20220823_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='CustomerDivision',
        ),
    ]
