# Generated by Django 3.0.8 on 2022-10-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_auto_20221007_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_gsthsncode',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='GstCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
