# Generated by Django 3.0.8 on 2023-01-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_auto_20230109_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='MRP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OrderItemMRP', to='FoodERPApp.M_MRPMaster'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Margin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OrderItemMargin', to='FoodERPApp.M_MarginMaster'),
        ),
        migrations.AlterField(
            model_name='tc_ordertermsandconditions',
            name='TermsAndCondition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TermsAndCondition', to='FoodERPApp.M_TermsAndConditions'),
        ),
    ]
