# Generated by Django 3.0.8 on 2023-03-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_m_partytype_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_partytype',
            name='IsRetailer',
        ),
    ]
