# Generated by Django 3.0.8 on 2022-11-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_auto_20221118_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partyprefixs',
            name='Grnprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mc_partyprefixs',
            name='Invoiceprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mc_partyprefixs',
            name='Orderprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mc_partyprefixs',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PartyPrefix', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_partyprefixs',
            name='Receiptprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
