# Generated by Django 3.0.8 on 2022-07-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_tc_orderitems_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employees',
            name='Party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='EmployeesParty', to='FoodERPApp.M_Parties'),
        ),
    ]
