# Generated by Django 3.0.8 on 2023-06-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_tc_invoiceuploads_ewaybillno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_invoiceuploads',
            old_name='CanceledBy',
            new_name='EInvoiceCanceledBy',
        ),
        migrations.RenameField(
            model_name='tc_invoiceuploads',
            old_name='CreatedBy',
            new_name='EInvoiceCreatedBy',
        ),
        migrations.RemoveField(
            model_name='tc_invoiceuploads',
            name='CanceledOn',
        ),
        migrations.RemoveField(
            model_name='tc_invoiceuploads',
            name='CreatedOn',
        ),
        migrations.AddField(
            model_name='tc_invoiceuploads',
            name='EInvoiceCanceledOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tc_invoiceuploads',
            name='EInvoiceCreatedOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tc_invoiceuploads',
            name='EwayBillCanceledBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_invoiceuploads',
            name='EwayBillCanceledOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tc_invoiceuploads',
            name='EwayBillCreatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_invoiceuploads',
            name='EwayBillCreatedOn',
            field=models.DateTimeField(null=True),
        ),
    ]
