# Generated by Django 3.0.8 on 2023-06-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0030_m_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employees',
            name='City',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='EmployeesCity', to='FoodERPApp.M_Cities'),
            preserve_default=False,
        ),
    ]
