# Generated by Django 3.0.8 on 2022-11-21 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0031_auto_20221119_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grns',
            name='FullGRNNumber',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_grnreferences',
            name='ChallanNo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='BatchDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='MRP',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
