# Generated by Django 3.0.8 on 2022-09-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0031_m_partytype2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='m_partytype2',
            table='M_PartyType2',
        ),
    ]
