# Generated by Django 3.0.8 on 2022-12-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0031_auto_20221222_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_items',
            name='BrandName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='m_items',
            name='Tag',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
