# Generated by Django 3.0.8 on 2023-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0031_auto_20230407_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_creditdebitnotes',
            name='NoteNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
