# Generated by Django 3.0.8 on 2022-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0031_m_gsthsncode_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_grouptype',
            name='IsReserved',
            field=models.BooleanField(default=False),
        ),
    ]
