# Generated by Django 3.0.8 on 2023-06-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0031_auto_20230622_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_invoiceuploads',
            old_name='IsCancel',
            new_name='EInvoiceIsCancel',
        ),
        migrations.AddField(
            model_name='tc_invoiceuploads',
            name='EwayBillIsCancel',
            field=models.BooleanField(default=False),
        ),
    ]
