# Generated by Django 3.0.8 on 2022-07-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0031_m_employees_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_invoiceitembatches',
            old_name='InvoiceID',
            new_name='Invoice',
        ),
        migrations.RenameField(
            model_name='tc_invoiceitembatches',
            old_name='InvoiceItemID',
            new_name='InvoiceItem',
        ),
        migrations.RenameField(
            model_name='tc_invoiceitembatches',
            old_name='ItemID',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='tc_invoiceitembatches',
            old_name='UnitID',
            new_name='Unit',
        ),
        migrations.RemoveField(
            model_name='tc_invoiceitems',
            name='UnitID',
        ),
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='Unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='InvoiceUnitID', to='FoodERPApp.MC_ItemUnits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_invoices',
            name='InvoiceDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitembatches',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='BaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='QtyInBox',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='QtyInKg',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='QtyInNo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
