# Generated by Django 3.0.8 on 2023-06-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0031_auto_20230603_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='City',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='Taluka',
        ),
    ]
