# Generated by Django 3.0.8 on 2023-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0032_auto_20230605_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='MobileNo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
