# Generated by Django 3.0.8 on 2022-06-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0032_m_itemsgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='ItemsGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ItemsGroup', to='FoodERPApp.M_ItemsGroup'),
            preserve_default=False,
        ),
    ]
