# Generated by Django 3.0.8 on 2022-08-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0032_auto_20220823_1718'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='m_productsubcategory',
            table='M_ProductSubCategory',
        ),
    ]
