# Generated by Django 3.0.8 on 2022-10-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0032_m_grouptype_isreserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_itemgroupdetails',
            name='SubGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemSubGroup', to='FoodERPApp.MC_SubGroup'),
        ),
    ]
