# Generated by Django 3.0.8 on 2022-09-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0032_auto_20220919_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='DivisionType',
        ),
        migrations.AddField(
            model_name='m_parties',
            name='PriceList',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyPriceList', to='FoodERPApp.M_PriceList'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='PartyType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyType', to='FoodERPApp.M_PartyType'),
        ),
    ]
