# Generated by Django 3.0.8 on 2022-11-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0032_auto_20221121_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitems',
            name='BatchDate',
            field=models.DateField(),
        ),
    ]
