# Generated by Django 3.0.8 on 2023-01-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0032_auto_20230111_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_GeneralMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('IsActive', models.BooleanField(default=False)),
                ('Flag', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Company', to='FoodERPApp.C_Companies')),
            ],
            options={
                'db_table': 'M_GeneralMaster',
            },
        ),
    ]
