# Generated by Django 3.0.8 on 2022-10-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0033_auto_20221011_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_mrpmaster',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='m_items',
            name='BarCode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='m_items',
            name='Sequence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
