# Generated by Django 3.0.8 on 2022-09-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0033_auto_20220919_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_MRPMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EffectiveDate', models.DateField()),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MRPCompany', to='FoodERPApp.C_Companies')),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MRPCustomer', to='FoodERPApp.M_Parties')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_Items')),
                ('Party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MRPParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'M_MRPMaster',
            },
        ),
        migrations.CreateModel(
            name='M_MarginMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EffectiveDate', models.DateField()),
                ('Margin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='MarginCompany', to='FoodERPApp.C_Companies')),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MarginCustomer', to='FoodERPApp.M_Parties')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_Items')),
                ('PriceList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PriceList', to='FoodERPApp.M_PriceList')),
            ],
            options={
                'db_table': 'M_MarginMaster',
            },
        ),
    ]
