# Generated by Django 3.0.8 on 2022-12-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0033_auto_20221222_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partyaddress',
            name='fssaidocument',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
