# Generated by Django 3.0.8 on 2022-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0033_m_items_itemsgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='Rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
