# Generated by Django 3.0.8 on 2022-11-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0033_auto_20221121_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Items'),
        ),
    ]
