# Generated by Django 3.0.8 on 2022-07-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0033_remove_m_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_invoiceitembatches',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='InvoiceBatchUnitID', to='FoodERPApp.MC_ItemUnits'),
        ),
    ]
