# Generated by Django 3.0.8 on 2023-01-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0033_m_generalmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_generalmaster',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='m_generalmaster',
            name='Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
