# Generated by Django 3.0.8 on 2023-04-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0034_auto_20230407_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_creditdebitnotes',
            name='FullNoteNumber',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_creditdebitnotes',
            name='NoteNo',
            field=models.CharField(max_length=500),
        ),
    ]
