# Generated by Django 3.0.8 on 2022-08-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0034_auto_20220823_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_itemsgmmh',
            name='FromDate',
        ),
        migrations.RemoveField(
            model_name='mc_itemsgmmh',
            name='ToDate',
        ),
    ]
