# Generated by Django 3.0.8 on 2023-06-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0034_tc_invoiceuploads_user_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_settings',
            name='Description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_settings',
            name='IsActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_settings',
            name='IsPartyRelatedSetting',
            field=models.BooleanField(default=False),
        ),
    ]
