# Generated by Django 3.0.8 on 2023-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0034_m_parties_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='MobileNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
