# Generated by Django 3.0.8 on 2022-06-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0034_m_items_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_pagepageaccess',
            name='PageID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PagePageAccess', to='FoodERPApp.M_Pages'),
        ),
    ]
