# Generated by Django 3.0.8 on 2022-11-23 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0034_auto_20221123_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Item', to='FoodERPApp.M_Items'),
        ),
    ]
