# Generated by Django 3.0.8 on 2022-07-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0034_auto_20220705_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_itemunits',
            name='BaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
