# Generated by Django 3.0.8 on 2022-10-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0034_auto_20221011_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_mrpmaster',
            name='IsDeleted',
        ),
    ]
