# Generated by Django 3.0.8 on 2022-12-27 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0034_mc_partyaddress_fssaidocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='Comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mc_itemshelflife',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemShelfLife', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
