# Generated by Django 3.0.8 on 2023-01-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0034_auto_20230111_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_generalmaster',
            name='Flag',
        ),
    ]
