# Generated by Django 3.0.8 on 2023-06-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0035_auto_20230605_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partyimportfields',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyImportFieldCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='mc_partyimportfields',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyImport', to='FoodERPApp.M_Parties'),
        ),
    ]
