# Generated by Django 3.0.8 on 2022-12-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0035_auto_20221227_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o_batchwiselivestock',
            name='GRN',
        ),
    ]
