# Generated by Django 3.0.8 on 2022-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0035_auto_20220705_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
