# Generated by Django 3.0.8 on 2023-01-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0035_remove_m_generalmaster_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_generalmaster',
            name='Type',
        ),
        migrations.AddField(
            model_name='m_generalmaster',
            name='TypeID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
