# Generated by Django 3.0.8 on 2022-09-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0035_auto_20220920_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_marginmaster',
            name='PriceList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PriceList', to='FoodERPApp.M_PriceList'),
            preserve_default=False,
        ),
    ]
