# Generated by Django 3.0.8 on 2022-10-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0035_remove_m_mrpmaster_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partysubparty',
            name='CreatedBy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mc_partysubparty',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MCParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_partysubparty',
            name='SubParty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MCSubParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_partysubparty',
            name='UpdatedBy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
