# Generated by Django 3.0.8 on 2023-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0035_auto_20230623_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_partysettingsdetails',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='m_partysettingsdetails',
            name='UpdatedOn',
        ),
        migrations.AddField(
            model_name='m_settings',
            name='DefaultValue',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
