# Generated by Django 3.0.8 on 2022-06-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0035_auto_20220615_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='CustomerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerID', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='PartyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PartyID', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
