# Generated by Django 3.0.8 on 2022-06-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0036_auto_20220616_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='M_Employess',
            new_name='M_Employees',
        ),
        migrations.AlterModelTable(
            name='m_employees',
            table='M_Employees',
        ),
    ]
