# Generated by Django 3.0.8 on 2023-06-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0036_auto_20230623_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_partysettingsdetails',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SetParty', to='FoodERPApp.M_Parties'),
        ),
    ]
