# Generated by Django 3.0.8 on 2022-09-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0036_auto_20220920_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='PriceList',
        ),
    ]
