# Generated by Django 3.0.8 on 2022-07-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0036_abc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='abc',
            table='Abc',
        ),
    ]
