# Generated by Django 3.0.8 on 2022-12-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0036_m_pagetype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='m_pagetype',
            table='M_PageType',
        ),
    ]
