# Generated by Django 3.0.8 on 2022-10-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0036_auto_20221012_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_gsthsncode',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_marginmaster',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_mrpmaster',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
