# Generated by Django 3.0.8 on 2022-11-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0036_auto_20221123_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='GrnItem', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Item', to='FoodERPApp.M_Items'),
        ),
    ]
