# Generated by Django 3.0.8 on 2022-08-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0036_auto_20220824_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='Image',
        ),
    ]
