# Generated by Django 3.0.8 on 2023-01-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0036_auto_20230112_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_generalmaster',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Company', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='m_generalmaster',
            name='Name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_pages',
            name='ShowCountLabel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
