# Generated by Django 3.0.8 on 2022-07-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0037_auto_20220706_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='PAN',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
