# Generated by Django 3.0.8 on 2022-06-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0037_auto_20220617_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='BaseunitID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
