# Generated by Django 3.0.8 on 2022-09-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0037_remove_m_parties_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='PriceList',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyPriceList', to='FoodERPApp.M_PriceList'),
            preserve_default=False,
        ),
    ]
