# Generated by Django 3.0.8 on 2022-10-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0037_auto_20221014_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_gsthsncode',
            name='IsDeleted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='m_marginmaster',
            name='IsDeleted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='m_mrpmaster',
            name='IsDeleted',
            field=models.IntegerField(),
        ),
    ]
