# Generated by Django 3.0.8 on 2023-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0037_auto_20230623_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_items',
            name='StoringCondition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
