# Generated by Django 3.0.8 on 2023-04-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0037_auto_20230407_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_creditdebitnoteitems',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='tc_creditdebitnoteitems',
            name='MRP',
        ),
        migrations.RemoveField(
            model_name='tc_creditdebitnoteitems',
            name='Note',
        ),
        migrations.RemoveField(
            model_name='tc_creditdebitnoteitems',
            name='Unit',
        ),
        migrations.DeleteModel(
            name='T_CreditDebitNotes',
        ),
        migrations.DeleteModel(
            name='TC_CreditDebitNoteItems',
        ),
    ]
