# Generated by Django 3.0.8 on 2022-12-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0037_auto_20221228_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_PageType',
        ),
    ]
