# Generated by Django 3.0.8 on 2022-06-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0037_auto_20220617_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='CustomerID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='PartyID',
            field=models.IntegerField(),
        ),
    ]
