# Generated by Django 3.0.8 on 2022-08-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0037_remove_abc_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='Image',
            field=models.ImageField(blank=True, upload_to='ItemMaster'),
        ),
    ]
