# Generated by Django 3.0.8 on 2022-08-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_abc_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_ItemDivisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Division', to='FoodERPApp.M_Parties')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemDivisionDetails', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemDivisionss',
            },
        ),
        migrations.CreateModel(
            name='MC_ItemGMH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=20)),
                ('HSNCode', models.CharField(max_length=500)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGstDetails', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemGMH',
            },
        ),
        migrations.CreateModel(
            name='MC_ItemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_pic', models.TextField()),
                ('ImageType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ImageType', to='FoodERPApp.M_ImageTypes')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemImagesDetails', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemImages',
            },
        ),
        migrations.CreateModel(
            name='MC_ItemMargin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PriceList', models.IntegerField(default=False)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemMarginDetails', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemMargin',
            },
        ),
        migrations.RenameModel(
            old_name='M_ItemsShelfLife',
            new_name='M_ItemShelfLife',
        ),
        migrations.RemoveField(
            model_name='mc_itemsimages',
            name='ImageType',
        ),
        migrations.RemoveField(
            model_name='mc_itemsimages',
            name='Item',
        ),
        migrations.RenameField(
            model_name='abc',
            old_name='Image',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='mc_itemunits',
            name='IsBase',
        ),
        migrations.RemoveField(
            model_name='mc_itemunits',
            name='IsDefault',
        ),
        migrations.AddField(
            model_name='abc',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abc',
            name='remark',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_roleaccess',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleAccessDividion', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterModelTable(
            name='m_itemshelflife',
            table='M_ItemShelfLife',
        ),
        migrations.DeleteModel(
            name='MC_ItemsGMMH',
        ),
        migrations.DeleteModel(
            name='MC_ItemsImages',
        ),
    ]
