# Generated by Django 3.0.8 on 2022-06-18 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_auto_20220618_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerID', to='FoodERPApp.M_Parties'),
        ),
    ]
