# Generated by Django 3.0.8 on 2023-01-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_auto_20230113_1726'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='o_livebatches',
            table='O_LiveBatches',
        ),
    ]
