# Generated by Django 3.0.8 on 2023-06-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_m_importfields_importexceltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_importfields',
            name='ImportExceltype',
        ),
    ]
