# Generated by Django 3.0.8 on 2022-10-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_auto_20221014_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_gsthsncode',
            name='IsDeleted',
        ),
        migrations.RemoveField(
            model_name='m_marginmaster',
            name='IsDeleted',
        ),
        migrations.RemoveField(
            model_name='m_mrpmaster',
            name='IsDeleted',
        ),
    ]
