# Generated by Django 3.0.8 on 2022-09-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_m_parties_pricelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_marginmaster',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='m_mrpmaster',
            name='Customer',
        ),
        migrations.AddField(
            model_name='m_marginmaster',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MarginParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AddField(
            model_name='m_mrpmaster',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MRPDivision', to='FoodERPApp.M_Parties'),
        ),
    ]
