# Generated by Django 3.0.8 on 2022-06-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_m_items_baseunitid'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='Sequence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
