# Generated by Django 3.0.8 on 2023-06-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_auto_20230624_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_bank',
            name='Company',
        ),
    ]
