# Generated by Django 3.0.8 on 2022-07-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_m_parties_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_users',
            name='isLoginUsingEmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_users',
            name='isLoginUsingMobile',
            field=models.BooleanField(default=False),
        ),
    ]
