# Generated by Django 3.0.8 on 2022-08-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_abc_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='Image',
        ),
        migrations.AddField(
            model_name='abc',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abc',
            name='remark',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
