# Generated by Django 3.0.8 on 2023-04-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0038_auto_20230408_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_CreditDebitNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoteDate', models.DateField()),
                ('NoteNo', models.IntegerField()),
                ('FullNoteNumber', models.CharField(max_length=500)),
                ('NoteReason', models.CharField(blank=True, max_length=50, null=True)),
                ('GrandTotal', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('RoundOffAmount', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('IsChequeBounce', models.BooleanField(default=False)),
                ('Narration', models.CharField(blank=True, max_length=500, null=True)),
                ('Comment', models.CharField(blank=True, max_length=500, null=True)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NoteCustomer', to='FoodERPApp.M_Parties')),
                ('Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Invoice', to='FoodERPApp.T_Invoices')),
                ('NoteType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_GeneralMaster')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NoteParty', to='FoodERPApp.M_Parties')),
                ('PurchaseReturn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_PurchaseReturn')),
                ('Receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_Receipts')),
            ],
            options={
                'db_table': 'T_CreditDebitNotes',
            },
        ),
        migrations.CreateModel(
            name='TC_CreditDebitNoteItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HSNCode', models.CharField(blank=True, max_length=500, null=True)),
                ('Quantity', models.IntegerField()),
                ('Rate', models.DecimalField(decimal_places=3, max_digits=20)),
                ('BasicAmount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTRate', models.DecimalField(decimal_places=3, max_digits=20)),
                ('GSTAmount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('CGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IGST', models.DecimalField(decimal_places=3, max_digits=15)),
                ('CGSTPercentage', models.DecimalField(decimal_places=3, max_digits=15)),
                ('SGSTPercentage', models.DecimalField(decimal_places=3, max_digits=15)),
                ('IGSTPercentage', models.DecimalField(decimal_places=3, max_digits=15)),
                ('NOC', models.CharField(max_length=20)),
                ('BatchCode', models.CharField(max_length=500)),
                ('Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('MRP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CRDRMRP', to='FoodERPApp.M_MRPMaster')),
                ('Note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CRDRNote', to='FoodERPApp.T_CreditDebitNotes')),
                ('Unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Units')),
            ],
            options={
                'db_table': 'TC_CreditDebitNoteItems',
            },
        ),
    ]
