# Generated by Django 3.0.8 on 2022-11-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_auto_20221123_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='GItem', to='FoodERPApp.M_Items'),
        ),
    ]
