# Generated by Django 3.0.8 on 2022-08-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_auto_20220826_1303'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mc_itemdivisions',
            table='MC_ItemDivisions',
        ),
        migrations.CreateModel(
            name='MC_RolesEmployeeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_EmployeeTypes')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleEmployeeTypes', to='FoodERPApp.M_Roles')),
            ],
        ),
    ]
