# Generated by Django 3.0.8 on 2022-07-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_auto_20220706_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='MobileNo',
            field=models.BigIntegerField(),
        ),
    ]
