# Generated by Django 3.0.8 on 2022-10-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_auto_20221014_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_gsthsncode',
            name='IsDeleted',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_marginmaster',
            name='IsDeleted',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_mrpmaster',
            name='IsDeleted',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
