# Generated by Django 3.0.8 on 2022-06-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_m_items_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_items',
            name='ItemsGroup',
        ),
        migrations.AddField(
            model_name='m_items',
            name='ItemGroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_ItemsGroup'),
            preserve_default=False,
        ),
    ]
