# Generated by Django 3.0.8 on 2023-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_remove_m_bank_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_group',
            name='Sequence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='m_grouptype',
            name='Sequence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mc_subgroup',
            name='Sequence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
