# Generated by Django 3.0.8 on 2022-09-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_auto_20220920_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_ItemGSTHSNCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HSNCode', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemGSTHSNDetails', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemGSTHSNCode',
            },
        ),
        migrations.RemoveField(
            model_name='mc_itemmargin',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='mc_itemmrp',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='mc_itemmrp',
            name='MRPType',
        ),
        migrations.AlterField(
            model_name='m_marginmaster',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemMarginDetails', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='m_mrpmaster',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemMRPDetails', to='FoodERPApp.M_Items'),
        ),
        migrations.DeleteModel(
            name='M_MRPTypes',
        ),
        migrations.DeleteModel(
            name='MC_ItemMargin',
        ),
        migrations.DeleteModel(
            name='MC_ItemMRP',
        ),
    ]
