# Generated by Django 3.0.8 on 2023-04-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_t_creditdebitnotes_tc_creditdebitnoteitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partyprefixs',
            name='Creditprefix',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mc_partyprefixs',
            name='Debitprefix',
            field=models.CharField(blank=True, default=1, max_length=500),
            preserve_default=False,
        ),
    ]
