# Generated by Django 3.0.8 on 2023-01-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_auto_20230113_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='LiveBatche',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='LiveBatcheID', to='FoodERPApp.O_LiveBatches'),
            preserve_default=False,
        ),
    ]
