# Generated by Django 3.0.8 on 2023-06-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_remove_m_bank_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partysubparty',
            name='TCSParty',
            field=models.BooleanField(default=False),
        ),
    ]
