# Generated by Django 3.0.8 on 2022-08-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_auto_20220825_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='picture',
            field=models.ImageField(blank=True, upload_to='ItemMaster'),
        ),
    ]
