# Generated by Django 3.0.8 on 2022-12-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0039_m_pagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_pagetype',
            name='IsAvailableForAccess',
            field=models.BooleanField(default=False),
        ),
    ]
