# Generated by Django 3.0.8 on 2022-08-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0040_abc_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_ItemsDivisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Division', to='FoodERPApp.M_Parties')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemDivision', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemsDivisions',
            },
        ),
        migrations.CreateModel(
            name='MC_ItemsGMH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=20)),
                ('HSNCode', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGstDetails', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemsGMH',
            },
        ),
        migrations.CreateModel(
            name='MC_ItemsMargin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PriceList', models.IntegerField(default=False)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemMarginDetails', to='FoodERPApp.M_Items')),
            ],
        ),
        migrations.DeleteModel(
            name='MC_ItemsGMMH',
        ),
    ]
