# Generated by Django 3.0.8 on 2023-06-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0040_mc_partysubparty_tcsparty'),
        ('FoodERPApp', '0040_auto_20230626_1320'),
    ]

    operations = [
    ]
