# Generated by Django 3.0.8 on 2023-01-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0040_o_batchwiselivestock_livebatche'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Demands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DemandDate', models.DateField()),
                ('DeliveryDate', models.DateField()),
                ('OrderNo', models.IntegerField()),
                ('FullOrderNumber', models.CharField(max_length=500)),
                ('OrderAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('OrderType', models.IntegerField()),
                ('IsOpenPO', models.BooleanField(default=False)),
                ('POFromDate', models.DateField(blank=True, null=True)),
                ('POToDate', models.DateField(blank=True, null=True)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('BillingAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DemandBillingAddress', to='FoodERPApp.MC_PartyAddress')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DemandCustomer', to='FoodERPApp.M_Parties')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DemandDivision', to='FoodERPApp.M_Parties')),
                ('POType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DemandPOType', to='FoodERPApp.M_POType')),
                ('ShippingAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DemandShippingAddress', to='FoodERPApp.MC_PartyAddress')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DemandSupplier', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'T_Demands',
            },
        ),
        migrations.CreateModel(
            name='TC_DemandItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(blank=True, max_length=300, null=True)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('DeletedOn', models.DateTimeField(auto_now=True)),
                ('Demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DemandItems', to='FoodERPApp.T_Demands')),
                ('GST', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DemandItemGst', to='FoodERPApp.M_GSTHSNCode')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DItem', to='FoodERPApp.M_Items')),
                ('MRP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DemandItemMRP', to='FoodERPApp.M_MRPMaster')),
                ('Margin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DemandItemMargin', to='FoodERPApp.M_MarginMaster')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DemandUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'TC_DemandItems',
            },
        ),
    ]
