# Generated by Django 3.0.8 on 2022-10-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0040_auto_20221014_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_invoiceitems',
            name='CreatedOn',
        ),
    ]
