# Generated by Django 3.0.8 on 2022-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0040_auto_20220711_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
