# Generated by Django 3.0.8 on 2023-04-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0040_auto_20230408_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partyprefixs',
            name='Creditprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mc_partyprefixs',
            name='Debitprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
