# Generated by Django 3.0.8 on 2022-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0040_auto_20221123_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partyprefixs',
            name='Challanprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='t_deliverychallans',
            name='FullChallanNumber',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
