# Generated by Django 3.0.8 on 2022-12-28 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0040_m_pagetype_isavailableforaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'M_TransactionType',
            },
        ),
        migrations.RemoveField(
            model_name='o_batchwiselivestock',
            name='GRN',
        ),
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='ItemExpiryDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='TransactionID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='TransactionType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_TransactionType'),
            preserve_default=False,
        ),
    ]
