# Generated by Django 3.0.8 on 2022-06-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0040_auto_20220618_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_items',
            name='ItemGroup',
        ),
    ]
