# Generated by Django 3.0.8 on 2022-09-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0041_mc_itemgsthsncode_effectivedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_itemgsthsncode',
            name='EffectiveDate',
        ),
    ]
