# Generated by Django 3.0.8 on 2022-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0041_auto_20221124_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_itemunits',
            name='IsBase',
            field=models.BooleanField(default=False),
        ),
    ]
