# Generated by Django 3.0.8 on 2022-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0041_auto_20220825_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_itemsimages',
            name='Item_pic',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='mc_itemsmargin',
            table='MC_ItemsMargin',
        ),
    ]
