# Generated by Django 3.0.8 on 2022-10-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0041_remove_tc_invoiceitems_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_gsthsncode',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='m_marginmaster',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='m_mrpmaster',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
