# Generated by Django 3.0.8 on 2022-12-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0041_auto_20221228_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitems',
            name='CGST',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='CGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='IGST',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='IGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='SGST',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='SGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
