# Generated by Django 3.0.8 on 2022-07-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0041_auto_20220713_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_companies',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='c_companies',
            name='EmailID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='c_companies',
            name='PhoneNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
