# Generated by Django 3.0.8 on 2023-01-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0041_t_demands_tc_demanditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_demands',
            name='IsInward',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
