# Generated by Django 3.0.8 on 2023-06-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0041_merge_20230626_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_invoices',
            name='TCSAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
