# Generated by Django 3.0.8 on 2022-06-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0042_m_items_itemgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_items',
            name='ItemGroup',
        ),
    ]
