# Generated by Django 3.0.8 on 2022-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0042_remove_mc_itemgsthsncode_effectivedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_itemgsthsncode',
            name='EffectiveDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
