# Generated by Django 3.0.8 on 2023-06-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0042_t_invoices_tcsamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mc_partysubparty',
            old_name='TCSParty',
            new_name='IsTCSParty',
        ),
    ]
