# Generated by Django 3.0.8 on 2022-11-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0042_mc_itemunits_isbase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='GST',
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
