# Generated by Django 3.0.8 on 2022-08-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0042_auto_20220825_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_ItemDivisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Division', to='FoodERPApp.M_Parties')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemDivisiondetails', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemsDivisions',
            },
        ),
        migrations.RenameModel(
            old_name='MC_ItemsGMH',
            new_name='MC_ItemGMH',
        ),
        migrations.RenameModel(
            old_name='MC_ItemsImages',
            new_name='MC_ItemImages',
        ),
        migrations.RenameModel(
            old_name='MC_ItemsMargin',
            new_name='MC_ItemMargin',
        ),
        migrations.RemoveField(
            model_name='mc_itemunits',
            name='IsBase',
        ),
        migrations.RemoveField(
            model_name='mc_itemunits',
            name='IsDefault',
        ),
        migrations.DeleteModel(
            name='MC_ItemsDivisions',
        ),
    ]
