# Generated by Django 3.0.8 on 2023-01-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0042_t_demands_isinward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_demanditems',
            name='Demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DemandItem', to='FoodERPApp.T_Demands'),
        ),
    ]
