# Generated by Django 3.0.8 on 2022-07-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0042_auto_20220714_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='AlternateContactNo',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
