# Generated by Django 3.0.8 on 2022-11-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0043_auto_20221124_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='O_BatchWiseLiveStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('SystemBatchCode', models.CharField(max_length=500)),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('GRN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_GRNs')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BatchWiseLiveStockParty', to='FoodERPApp.M_Parties')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BatchWiseLiveStockUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'O_BatchWiseLiveStock',
            },
        ),
    ]
