# Generated by Django 3.0.8 on 2023-06-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0043_auto_20230627_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_grnitems',
            old_name='MRP',
            new_name='MRPValue',
        ),
    ]
