# Generated by Django 3.0.8 on 2023-06-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0043_auto_20230627_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_livebatches',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_livebatches',
            name='MRPValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tc_grnitems',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_grnitems',
            name='MRPValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='GST',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GRNItemGst', to='FoodERPApp.M_GSTHSNCode'),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='MRP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GRNItemMRP', to='FoodERPApp.M_MRPMaster'),
        ),
    ]
