# Generated by Django 3.0.8 on 2023-01-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0043_auto_20230116_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_demands',
            old_name='OrderAmount',
            new_name='DemandAmount',
        ),
        migrations.RenameField(
            model_name='t_demands',
            old_name='OrderNo',
            new_name='DemandNo',
        ),
        migrations.RenameField(
            model_name='t_demands',
            old_name='FullOrderNumber',
            new_name='FullDemandNumber',
        ),
    ]
