# Generated by Django 3.0.8 on 2022-09-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0043_mc_itemgsthsncode_effectivedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_ItemGSTHSNCode',
        ),
    ]
