# Generated by Django 3.0.8 on 2022-11-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0044_o_batchwiselivestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_grnitems',
            name='SystemBatchCode',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
