# Generated by Django 3.0.8 on 2022-08-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0044_auto_20220825_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='M_ItemsShelfLife',
            new_name='M_ItemShelfLife',
        ),
        migrations.RenameModel(
            old_name='MC_ItemsDivisions',
            new_name='MC_ItemDivisions',
        ),
        migrations.AlterModelTable(
            name='m_itemshelflife',
            table='M_ItemShelfLife',
        ),
        migrations.AlterModelTable(
            name='mc_itemgmh',
            table='MC_ItemGMH',
        ),
        migrations.AlterModelTable(
            name='mc_itemimages',
            table='MC_ItemImages',
        ),
        migrations.AlterModelTable(
            name='mc_itemmargin',
            table='MC_ItemMargin',
        ),
    ]
