# Generated by Django 3.0.8 on 2023-01-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0044_auto_20230116_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partyprefixs',
            name='Demandprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
