# Generated by Django 3.0.8 on 2022-08-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0045_auto_20220825_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MC_ItemDivisions',
            new_name='MC_ItemsDivisions',
        ),
        migrations.AlterModelTable(
            name='mc_itemsdivisions',
            table='MC_ItemsDivisions',
        ),
    ]
