# Generated by Django 3.0.8 on 2022-11-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0045_tc_grnitems_systembatchcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_BillOfMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('EstimatedOutput', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Comment', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=False)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BOMUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'M_BillOfMaterial',
            },
        ),
    ]
