# Generated by Django 3.0.8 on 2023-01-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0045_mc_partyprefixs_demandprefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_demands',
            old_name='IsInward',
            new_name='DemandClose',
        ),
        migrations.RemoveField(
            model_name='t_demands',
            name='DeliveryDate',
        ),
        migrations.RemoveField(
            model_name='t_demands',
            name='IsOpenPO',
        ),
        migrations.RemoveField(
            model_name='t_demands',
            name='OrderType',
        ),
        migrations.RemoveField(
            model_name='t_demands',
            name='POFromDate',
        ),
        migrations.RemoveField(
            model_name='t_demands',
            name='POToDate',
        ),
        migrations.RemoveField(
            model_name='t_demands',
            name='POType',
        ),
        migrations.RemoveField(
            model_name='tc_demanditems',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='tc_demanditems',
            name='DeletedOn',
        ),
        migrations.RemoveField(
            model_name='tc_demanditems',
            name='IsDeleted',
        ),
    ]
