# Generated by Django 3.0.8 on 2022-09-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0045_mc_itemgsthsncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_marginmaster',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemMarginDetails', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='m_mrpmaster',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemMRPDetails', to='FoodERPApp.M_Items'),
        ),
    ]
