# Generated by Django 3.0.8 on 2023-06-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0045_auto_20230629_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_grnitems',
            old_name='MRPValue',
            new_name='MRP',
        ),
    ]
