# Generated by Django 3.0.8 on 2023-06-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0046_auto_20230629_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitems',
            name='MRP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GRNItemMRP', to='FoodERPApp.M_MRPMaster'),
        ),
    ]
