# Generated by Django 3.0.8 on 2022-06-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0046_m_items_itemgroup'),
        # ('FoodERPApp', '0040_auto_20220618_1216'),
    ]

    operations = [
    ]
