# Generated by Django 3.0.8 on 2023-01-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0046_auto_20230117_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_DemandsReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_Demands')),
                ('MaterialIssue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_MaterialIssue')),
            ],
            options={
                'db_table': 'TC_DemandsReferences',
            },
        ),
    ]
