# Generated by Django 3.0.8 on 2022-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0046_auto_20220921_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='FSSAIExipry',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='FSSAINo',
        ),
        migrations.RemoveField(
            model_name='m_parties',
            name='PIN',
        ),
        migrations.AddField(
            model_name='mc_partyaddress',
            name='FSSAIExipry',
            field=models.DateField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_partyaddress',
            name='FSSAINo',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_partyaddress',
            name='PIN',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
