# Generated by Django 3.0.8 on 2022-10-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0046_auto_20221014_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='Margin',
        ),
    ]
