# Generated by Django 3.0.8 on 2022-06-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0046_m_items_itemgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_EmployeeType',
            },
        ),
        migrations.CreateModel(
            name='M_Resion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_Resion',
            },
        ),
        migrations.CreateModel(
            name='M_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'M_State',
            },
        ),
        migrations.RemoveField(
            model_name='m_employees',
            name='DesignationID',
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='CustomerID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='PartyID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
