# Generated by Django 3.0.8 on 2022-08-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0046_auto_20220825_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_ItemsDivisions',
        ),
    ]
