# Generated by Django 3.0.8 on 2022-11-29 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0046_m_billofmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_grnitems',
            name='SystemBatchDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MC_BillOfMaterialItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('BOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_BillOfMaterial')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BOMItemUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'MC_BillOfMaterialItems',
            },
        ),
    ]
