# Generated by Django 3.0.8 on 2022-06-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0047_auto_20220620_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_Designations',
        ),
        migrations.DeleteModel(
            name='M_Employees',
        ),
        migrations.DeleteModel(
            name='M_EmployeeType',
        ),
        migrations.DeleteModel(
            name='M_Resion',
        ),
        migrations.DeleteModel(
            name='M_State',
        ),
    ]
