# Generated by Django 3.0.8 on 2022-10-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0047_remove_tc_orderitems_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='Margin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemMargin', to='FoodERPApp.M_MarginMaster'),
            preserve_default=False,
        ),
    ]
