# Generated by Django 3.0.8 on 2022-09-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0047_auto_20220921_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_PartyAddress',
        ),
    ]
