# Generated by Django 3.0.8 on 2023-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0047_auto_20230629_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_livebatches',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_livebatches',
            name='MRPValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_grnitems',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_grnitems',
            name='MRPValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
