# Generated by Django 3.0.8 on 2022-11-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0047_auto_20221129_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_grnitems',
            name='SystemBatchDate',
        ),
    ]
