# Generated by Django 3.0.8 on 2022-10-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0048_tc_orderitems_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='GST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderItemGST', to='FoodERPApp.M_GSTHSNCode'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='MRP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderItemMRP', to='FoodERPApp.M_MRPMaster'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Margin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderItemMargin', to='FoodERPApp.M_MarginMaster'),
        ),
    ]
