# Generated by Django 3.0.8 on 2023-06-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0048_auto_20230629_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitems',
            name='GST',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GRNItemGst', to='FoodERPApp.M_GSTHSNCode'),
        ),
    ]
