# Generated by Django 3.0.8 on 2023-01-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0048_auto_20230117_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TC_DemandsReferences',
            new_name='TC_DemandReferences',
        ),
        migrations.AlterModelTable(
            name='tc_demandreferences',
            table='TC_DemandReferences',
        ),
    ]
