# Generated by Django 3.0.8 on 2022-08-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0048_mc_itemsdivisions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_ItemsDivisions',
        ),
    ]
