# Generated by Django 3.0.8 on 2023-01-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0048_auto_20230117_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_livebatches',
            name='OriginalBatchBaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_materialissueitems',
            name='BatchID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.O_LiveBatches'),
            preserve_default=False,
        ),
    ]
