# Generated by Django 3.0.8 on 2022-11-29 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0048_remove_tc_grnitems_systembatchdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_grnitems',
            name='SystemBatchDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
