# Generated by Django 3.0.8 on 2022-10-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0049_auto_20221017_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='MRP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderItemMRP', to='FoodERPApp.M_MRPMaster'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Margin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderItemMargin', to='FoodERPApp.M_MarginMaster'),
        ),
        migrations.CreateModel(
            name='MC_PartyItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartyItem', to='FoodERPApp.M_Items')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Party', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'MC_PartyItems',
            },
        ),
    ]
