# Generated by Django 3.0.8 on 2023-01-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0049_auto_20230117_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_materialissueitems',
            old_name='BatchID',
            new_name='LiveBatchID',
        ),
    ]
