# Generated by Django 3.0.8 on 2023-06-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0049_auto_20230629_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grns',
            name='Comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tc_grnitems',
            name='QtyInBox',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_grnitems',
            name='QtyInKg',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_grnitems',
            name='QtyInNo',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
