# Generated by Django 3.0.8 on 2022-09-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0049_mc_partyaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='IsDivision',
            field=models.BooleanField(default=False),
        ),
    ]
