# Generated by Django 3.0.8 on 2022-06-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0050_m_employeetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employees',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Companies', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_employees',
            name='Resion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Resion', to='FoodERPApp.M_Resion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_employees',
            name='State',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='State', to='FoodERPApp.M_State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='EmployeeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeType', to='FoodERPApp.M_EmployeeType'),
        ),
    ]
