# Generated by Django 3.0.8 on 2023-01-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0050_auto_20230118_1212'),
        ('FoodERPApp', '0049_auto_20230117_1217'),
    ]

    operations = [
    ]
