# Generated by Django 3.0.8 on 2023-06-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0050_auto_20230629_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grns',
            name='Reason',
            field=models.ForeignKey(default=70, on_delete=django.db.models.deletion.PROTECT, related_name='GRNReason', to='FoodERPApp.M_GeneralMaster'),
            preserve_default=False,
        ),
    ]
