# Generated by Django 3.0.8 on 2022-10-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0050_auto_20221018_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_pagefieldmaster',
            name='DefaultSort',
            field=models.IntegerField(),
        ),
    ]
