# Generated by Django 3.0.8 on 2022-11-30 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0050_auto_20221130_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='SystemBatchDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
