# Generated by Django 3.0.8 on 2022-08-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0050_mc_itemdivisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_invoiceitembatches',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='tc_invoiceitems',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='Unit',
        ),
        migrations.DeleteModel(
            name='MC_ItemUnits',
        ),
    ]
