# Generated by Django 3.0.8 on 2022-10-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0051_auto_20221019_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='BaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
