# Generated by Django 3.0.8 on 2022-11-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0051_o_batchwiselivestock_systembatchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='MRP',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
