# Generated by Django 3.0.8 on 2023-01-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0051_merge_20230118_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='LiveBatch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.O_LiveBatches'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tc_demandreferences',
            name='Demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DemandReferences', to='FoodERPApp.T_Demands'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='BaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
