# Generated by Django 3.0.8 on 2022-09-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0051_auto_20220922_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_marginmaster',
            name='IsDelete',
        ),
    ]
