# Generated by Django 3.0.8 on 2023-01-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0052_auto_20230120_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_demanditems',
            name='DeletedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tc_demanditems',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
