# Generated by Django 3.0.8 on 2022-06-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0052_auto_20220618_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employees',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='State', to='FoodERPApp.M_State'),
        ),
    ]
