# Generated by Django 3.0.8 on 2022-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0052_auto_20221130_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='Rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='GRN',
            field=models.IntegerField(),
        ),
    ]
