# Generated by Django 3.0.8 on 2022-06-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0052_m_resion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_Resion',
        ),
    ]
