# Generated by Django 3.0.8 on 2022-08-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0052_auto_20220825_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_itemdivisions',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemDivisionDetails', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='mc_itemimages',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemImagesDetails', to='FoodERPApp.M_Items'),
        ),
    ]
