# Generated by Django 3.0.8 on 2023-06-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0052_tc_grnitems_actualquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitems',
            name='ActualQuantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
