# Generated by Django 3.0.8 on 2022-10-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0052_auto_20221020_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
