# Generated by Django 3.0.8 on 2023-07-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0053_auto_20230630_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockDate', models.DateField()),
                ('BaseunitQuantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('MRPValue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockItem', to='FoodERPApp.M_Items')),
                ('MRP', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='StockItemMRP', to='FoodERPApp.M_MRPMaster')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='StockParty', to='FoodERPApp.M_Parties')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='StockUnit', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'T_Stock',
            },
        ),
    ]

