# Generated by Django 3.0.8 on 2023-01-20 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0053_auto_20230120_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_InterBranchInward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InwardDate', models.DateField()),
                ('InwardNumber', models.IntegerField()),
                ('FullInwardNumber', models.CharField(max_length=500)),
                ('GrandTotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='InterBranchCustomer', to='FoodERPApp.M_Parties')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='InterBranchSupplier', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'T_InterBranchInward',
            },
        ),
        migrations.CreateModel(
            name='TC_InterBranchInwardItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ReferenceRate', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DiscountType', models.CharField(max_length=500)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(blank=True, max_length=500, null=True)),
                ('SystemBatchDate', models.DateField()),
                ('SystemBatchCode', models.CharField(max_length=500)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('GST', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='IBInwardItemGst', to='FoodERPApp.M_GSTHSNCode')),
                ('InterBranchInward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InterBranchInwardItems', to='FoodERPApp.T_InterBranchInward')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='IBInwardItem', to='FoodERPApp.M_Items')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='IBInwardUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'TC_InterBranchInwardItems',
            },
        ),
        migrations.CreateModel(
            name='TC_InterBranchInwardReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inward', models.BooleanField(default=False)),
                ('Demand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DemandReferences', to='FoodERPApp.T_Demands')),
                ('InterBranchInward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InterBranchInwardReferences', to='FoodERPApp.T_InterBranchInward')),
            ],
            options={
                'db_table': 'TC_InterBranchInwardReferences',
            },
        ),
        migrations.DeleteModel(
            name='TC_DemandReferences',
        ),
    ]
