# Generated by Django 3.0.8 on 2022-08-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0053_auto_20220826_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_itemgmh',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='mc_itemgmh',
            name='UpdatedBy',
        ),
    ]
