# Generated by Django 3.0.8 on 2022-11-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0053_auto_20221130_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='GST',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='OrderItemGst', to='FoodERPApp.M_GSTHSNCode'),
            preserve_default=False,
        ),
    ]
