# Generated by Django 3.0.8 on 2023-07-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0054_t_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_purchasereturn',
            name='ReturnReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReturnReason', to='FoodERPApp.M_GeneralMaster'),
        ),
    ]
