# Generated by Django 3.0.8 on 2022-06-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0054_m_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_Region',
        ),
    ]
