# Generated by Django 3.0.8 on 2023-01-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0054_auto_20230120_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_InterbranchChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBChallanDate', models.DateField()),
                ('IBChallanNumber', models.IntegerField()),
                ('FullIBChallanNumber', models.CharField(max_length=500)),
                ('CustomerGSTTin', models.CharField(max_length=500)),
                ('GrandTotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('RoundOffAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='IBChallanCustomer', to='FoodERPApp.M_Parties')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='IBChallanParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'T_InterbranchChallan',
            },
        ),
        migrations.RenameField(
            model_name='t_interbranchinward',
            old_name='FullInwardNumber',
            new_name='FullIBInwardNumber',
        ),
        migrations.RenameField(
            model_name='t_interbranchinward',
            old_name='InwardDate',
            new_name='IBInwardDate',
        ),
        migrations.RenameField(
            model_name='t_interbranchinward',
            old_name='InwardNumber',
            new_name='IBInwardNumber',
        ),
        migrations.RenameField(
            model_name='tc_interbranchinwarditems',
            old_name='InterBranchInward',
            new_name='IBInward',
        ),
        migrations.RenameField(
            model_name='tc_interbranchinwardreferences',
            old_name='InterBranchInward',
            new_name='IBInward',
        ),
        migrations.RenameField(
            model_name='tc_interbranchinwardreferences',
            old_name='Inward',
            new_name='IsInward',
        ),
        migrations.AddField(
            model_name='t_demands',
            name='MaterialIssue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DemandMaterialIssue', to='FoodERPApp.T_MaterialIssue'),
        ),
        migrations.AlterField(
            model_name='t_demands',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DemandCustomer', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_demands',
            name='Division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DemandDivision', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_demands',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DemandSupplier', to='FoodERPApp.M_Parties'),
        ),
        migrations.CreateModel(
            name='TC_InterbranchChallanReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_Demands')),
                ('IBChallan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_InterbranchChallan')),
            ],
            options={
                'db_table': 'TC_InterbranchChallanReferences',
            },
        ),
        migrations.CreateModel(
            name='TC_InterbranchChallanItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('MRP', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DiscountType', models.CharField(blank=True, max_length=500, null=True)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('IBChallan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InterbranchChallan', to='FoodERPApp.T_InterbranchChallan')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_Items')),
                ('LiveBatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.O_LiveBatches')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='InterbranchChallanUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'TC_InterbranchChallanItems',
            },
        ),
        migrations.AddField(
            model_name='tc_interbranchinwardreferences',
            name='IBChallan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_InterbranchChallan'),
        ),
    ]
