# Generated by Django 3.0.8 on 2022-11-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0054_tc_orderitems_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='GSTPercentage',
        ),
    ]
