# Generated by Django 3.0.8 on 2022-06-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0055_delete_m_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('DOB', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=100)),
                ('AadharNo', models.IntegerField()),
                ('EmployeeType', models.IntegerField()),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(blank=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'M_Employees',
            },
        ),
    ]
