# Generated by Django 3.0.8 on 2023-07-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0055_auto_20230704_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='ItemReason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ItemReason', to='FoodERPApp.M_GeneralMaster'),
            preserve_default=False,
        ),
    ]
