# Generated by Django 3.0.8 on 2022-08-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0055_auto_20220826_1131'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mc_itemdivisions',
            table='MC_ItemDivisions',
        ),
    ]
