# Generated by Django 3.0.8 on 2022-11-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0055_remove_tc_orderitems_gstpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_grnitems',
            name='GST',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='GRNItemGst', to='FoodERPApp.M_GSTHSNCode'),
            preserve_default=False,
        ),
    ]
