# Generated by Django 3.0.8 on 2023-01-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0055_auto_20230120_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partyprefixs',
            name='IBChallanprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mc_partyprefixs',
            name='IBInwardprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
