# Generated by Django 3.0.8 on 2022-08-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0056_auto_20220826_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_roleaccess',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleAccessDividion', to='FoodERPApp.M_Parties'),
        ),
        migrations.CreateModel(
            name='MC_RolesEmployeeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_EmployeeTypes')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RoleEmployeeTypes', to='FoodERPApp.M_Roles')),
            ],
        ),
    ]
