# Generated by Django 3.0.8 on 2022-11-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0056_tc_grnitems_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_grnitems',
            name='GSTPercentage',
        ),
    ]
