# Generated by Django 3.0.8 on 2022-06-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0056_m_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_employees',
            name='EmployeeType',
        ),
    ]
