# Generated by Django 3.0.8 on 2023-01-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0056_auto_20230120_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_invoices',
            name='RoundOffAmount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='CGST',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='CGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='Discount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='DiscountAmount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='GSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='IGST',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='IGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='SGST',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_invoiceitems',
            name='SGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
