# Generated by Django 3.0.8 on 2023-07-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0056_tc_purchasereturnitems_itemreason'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='t_stock',
            table=None,
        ),
    ]
