# Generated by Django 3.0.8 on 2023-07-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0057_auto_20230704_1721'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='t_stock',
            table='T_Stock',
        ),
    ]
