# Generated by Django 3.0.8 on 2023-01-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0057_auto_20230120_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='CGST',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='CGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='Discount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='DiscountAmount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='IGST',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='IGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='SGST',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='SGSTPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
