# Generated by Django 3.0.8 on 2022-08-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0057_auto_20220826_1531'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mc_rolesemployeetypes',
            table='MC_RolesEmployeeTypes',
        ),
    ]
