# Generated by Django 3.0.8 on 2022-11-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0057_remove_tc_grnitems_gstpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='GST',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ObatchwiseItemGst', to='FoodERPApp.M_GSTHSNCode'),
            preserve_default=False,
        ),
    ]
