# Generated by Django 3.0.8 on 2023-01-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0058_auto_20230120_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='InterBranchInward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BatchWiseLiveStockInterBranchInwardID', to='FoodERPApp.T_InterBranchInward'),
        ),
    ]
