# Generated by Django 3.0.8 on 2023-01-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0058_auto_20230120_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_interbranchchallanitems',
            name='IBChallan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IBChallanItems', to='FoodERPApp.T_InterbranchChallan'),
        ),
    ]
