# Generated by Django 3.0.8 on 2023-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0058_auto_20230704_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='Comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
