# Generated by Django 3.0.8 on 2022-08-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0058_auto_20220826_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Vehical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicalNumber', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=300)),
                ('VehicalType', models.CharField(max_length=300)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DriverName', to='FoodERPApp.Drivers')),
            ],
            options={
                'db_table': 'Vehical',
            },
        ),
        migrations.CreateModel(
            name='VehicleTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'VehicleTypes',
            },
        ),
        migrations.CreateModel(
            name='VehicalsDivisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Division', to='FoodERPApp.Drivers')),
                ('Vehical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Vehical', to='FoodERPApp.Vehical')),
            ],
        ),
    ]
