# Generated by Django 3.0.8 on 2022-06-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0058_m_employees_employeetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employees',
            name='Designations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Designations'),
            preserve_default=False,
        ),
    ]
