# Generated by Django 3.0.8 on 2023-01-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0059_o_batchwiselivestock_interbranchinward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_interbranchinwardreferences',
            name='Demand',
        ),
        migrations.RemoveField(
            model_name='tc_interbranchinwardreferences',
            name='IsInward',
        ),
    ]
