# Generated by Django 3.0.8 on 2023-01-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0059_auto_20230121_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_interbranchchallanitems',
            name='LiveBatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LiveBatches', to='FoodERPApp.O_LiveBatches'),
        ),
    ]
