# Generated by Django 3.0.8 on 2022-12-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0059_auto_20221201_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='GRN',
            field=models.IntegerField(blank=True),
        ),
    ]
