# Generated by Django 3.0.8 on 2022-08-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0059_drivers_vehical_vehicalsdivisions_vehicletypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_ItemMRP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=20)),
                ('HSNCode', models.CharField(max_length=500)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemMRPDetails', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'MC_ItemMRP',
            },
        ),
        migrations.DeleteModel(
            name='MC_ItemGMH',
        ),
    ]
