# Generated by Django 3.0.8 on 2022-06-20 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0059_m_employees_designations'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employees',
            name='State',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_State'),
            preserve_default=False,
        ),
    ]
