# Generated by Django 3.0.8 on 2023-07-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0059_tc_purchasereturnitems_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PartiesCities', to='FoodERPApp.M_Cities'),
        ),
    ]
