# Generated by Django 3.0.8 on 2022-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0060_auto_20220829_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRP_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'MRP_Types',
            },
        ),
    ]
