# Generated by Django 3.0.8 on 2023-07-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0060_auto_20230704_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='Latitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_parties',
            name='Longitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
