# Generated by Django 3.0.8 on 2023-01-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0060_auto_20230123_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='DiscountType',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
