# Generated by Django 3.0.8 on 2022-06-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0060_m_employees_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employees',
            name='C_Companies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
