# Generated by Django 3.0.8 on 2022-08-29 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0061_mrp_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_itemmrp',
            name='MRPType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MRPType', to='FoodERPApp.MRP_Types'),
            preserve_default=False,
        ),
    ]
