# Generated by Django 3.0.8 on 2023-01-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0061_auto_20230123_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_demanditems',
            name='BaseUnitQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_demanditems',
            name='Quantity',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
