# Generated by Django 3.0.8 on 2023-01-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0062_auto_20230123_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_deliverychallanitems',
            name='DeliveryChallan',
        ),
        migrations.RemoveField(
            model_name='tc_deliverychallanitems',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='tc_deliverychallanitems',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='tc_deliverychallanreferences',
            name='DeliveryChallan',
        ),
        migrations.RemoveField(
            model_name='tc_deliverychallanreferences',
            name='GRN',
        ),
        migrations.DeleteModel(
            name='T_DeliveryChallans',
        ),
        migrations.DeleteModel(
            name='TC_DeliveryChallanItems',
        ),
        migrations.DeleteModel(
            name='TC_DeliveryChallanReferences',
        ),
    ]
