# Generated by Django 3.0.8 on 2023-07-13 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0062_auto_20230706_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='ApprovedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='ApprovedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='ApprovedQuantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
