# Generated by Django 3.0.8 on 2022-12-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0062_remove_o_batchwiselivestock_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='GRN',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
