# Generated by Django 3.0.8 on 2022-08-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0062_mc_itemmrp_mrptype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicalsdivisions',
            table='VehicalsDivisions',
        ),
    ]
