# Generated by Django 3.0.8 on 2022-06-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0062_auto_20220620_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_employees',
            name='State',
        ),
    ]
