# Generated by Django 3.0.8 on 2023-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0063_auto_20230713_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_purchasereturnitems',
            name='ApprovedBy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tc_purchasereturnitems',
            name='ApprovedQuantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
    ]
