# Generated by Django 3.0.8 on 2023-01-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0063_auto_20230124_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_demands',
            old_name='Description',
            new_name='Comment',
        ),
        migrations.RemoveField(
            model_name='tc_demanditems',
            name='Comment',
        ),
    ]
