# Generated by Django 3.0.8 on 2022-08-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0063_auto_20220829_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Vehical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicalNumber', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=300)),
                ('VehicalType', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'M_Vehical',
            },
        ),
        migrations.RenameModel(
            old_name='Drivers',
            new_name='M_Drivers',
        ),
        migrations.RenameModel(
            old_name='VehicleTypes',
            new_name='M_VehicleTypes',
        ),
        migrations.AlterModelTable(
            name='m_drivers',
            table='M_Drivers',
        ),
        migrations.AlterModelTable(
            name='m_vehicletypes',
            table='M_VehicleTypes',
        ),
        migrations.AlterModelTable(
            name='mc_vehicalsdivisions',
            table='MC_VehicalsDivisions',
        ),
        migrations.RenameModel(
            old_name='VehicalsDivisions',
            new_name='MC_VehicalsDivisions',
        ),
        migrations.DeleteModel(
            name='Vehical',
        ),
        migrations.AlterField(
            model_name='mc_vehicalsdivisions',
            name='Vehical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Vehical', to='FoodERPApp.M_Vehical'),
        ),
    ]
