# Generated by Django 3.0.8 on 2022-12-01 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0063_o_batchwiselivestock_grn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_batchwiselivestock',
            name='GRN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='O_BatchWiseLiveStockGrnItems', to='FoodERPApp.T_GRNs'),
        ),
    ]
