# Generated by Django 3.0.8 on 2023-02-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0064_auto_20230125_1829'),
        ('FoodERPApp', '0060_auto_20230121_1531'),
    ]

    operations = [
    ]
