# Generated by Django 3.0.8 on 2022-12-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0064_auto_20221201_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='O_BatchWiseLiveStock',
        ),
    ]
