# Generated by Django 3.0.8 on 2022-06-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0064_m_employees_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employees',
            name='AadharNo',
            field=models.IntegerField(max_length=100),
        ),
    ]
