# Generated by Django 3.0.8 on 2023-07-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0064_auto_20230713_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='DiscountAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='DiscountType',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='TC_PurchaseReturnReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseReturn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Return', to='FoodERPApp.T_PurchaseReturn')),
                ('SubReturn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SubReturns', to='FoodERPApp.T_PurchaseReturn')),
            ],
            options={
                'db_table': 'TC_PurchaseReturnReferences',
            },
        ),
    ]
