# Generated by Django 3.0.8 on 2022-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0065_auto_20220620_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employees',
            name='AadharNo',
            field=models.IntegerField(max_length=12),
        ),
    ]
