# Generated by Django 3.0.8 on 2023-02-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0065_merge_20230201_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_materialissueitems',
            name='MaterialIssue',
        ),
    ]
