# Generated by Django 3.0.8 on 2023-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0065_auto_20230717_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='ApproveComment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
