# Generated by Django 3.0.8 on 2023-02-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0066_remove_tc_materialissueitems_materialissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_materialissueitems',
            name='MaterialIssue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='MaterialIssueItems', to='FoodERPApp.T_MaterialIssue'),
            preserve_default=False,
        ),
    ]
