# Generated by Django 3.0.8 on 2023-07-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0066_tc_purchasereturnitems_approvecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_purchasereturnreferences',
            name='SubReturn',
        ),
    ]
