# Generated by Django 3.0.8 on 2023-07-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0067_remove_tc_purchasereturnreferences_subreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnreferences',
            name='SubReturn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='SubReturn', to='FoodERPApp.T_PurchaseReturn'),
            preserve_default=False,
        ),
    ]
