# Generated by Django 3.0.8 on 2023-02-02 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0067_tc_materialissueitems_materialissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='POType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='OrderPOType', to='FoodERPApp.M_POType'),
            preserve_default=False,
        ),
    ]
