# Generated by Django 3.0.8 on 2022-06-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0068_auto_20220620_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employees',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
