# Generated by Django 3.0.8 on 2023-02-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0068_auto_20230202_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_materialissueworkorders',
            name='WorkOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MaterialIssueWorkOrder', to='FoodERPApp.T_WorkOrder'),
        ),
    ]
