# Generated by Django 3.0.8 on 2022-12-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0068_remove_o_batchwiselivestock_grn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_BillOfMaterialItems',
        ),
    ]
