# Generated by Django 3.0.8 on 2023-07-18 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0069_t_purchasereturn_isapproved'),
    ]

    operations = [
        migrations.CreateModel(
            name='O_DateWiseLiveStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockDate', models.DateField()),
                ('OpeningBalance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('GRN', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Sale', models.DecimalField(decimal_places=10, max_digits=20)),
                ('PurchaseReturn', models.DecimalField(decimal_places=10, max_digits=20)),
                ('SalesReturn', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ClosingBalance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ActualStock', models.DecimalField(decimal_places=10, max_digits=20)),
                ('IsAdjusted', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DStockItem', to='FoodERPApp.M_Items')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DStockParty', to='FoodERPApp.M_Parties')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DStockUnit', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'O_DateWiseLiveStock',
            },
        ),
    ]
