# Generated by Django 3.0.8 on 2022-06-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0069_m_employees_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employees',
            name='Joining_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
