# Generated by Django 3.0.8 on 2023-02-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0069_auto_20230202_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_interbranchchallanitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='tc_interbranchchallanitems',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='InterbranchChallanUnitID', to='FoodERPApp.MC_ItemUnits'),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='IBInwardItem', to='FoodERPApp.M_Items'),
        ),
    ]
