# Generated by Django 3.0.8 on 2023-07-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0070_o_datewiselivestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o_datewiselivestock',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='o_datewiselivestock',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='o_datewiselivestock',
            name='IsAdjusted',
        ),
        migrations.RemoveField(
            model_name='o_datewiselivestock',
            name='Party',
        ),
        migrations.RemoveField(
            model_name='o_datewiselivestock',
            name='Unit',
        ),
    ]
