# Generated by Django 3.0.8 on 2022-06-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0070_auto_20220621_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_invoiceitembatches',
            name='InvoiceID',
        ),
        migrations.RemoveField(
            model_name='tc_invoiceitembatches',
            name='InvoiceItemID',
        ),
        migrations.RemoveField(
            model_name='tc_invoiceitembatches',
            name='ItemID',
        ),
        migrations.RemoveField(
            model_name='tc_invoiceitems',
            name='InvoiceID',
        ),
        migrations.RemoveField(
            model_name='tc_invoiceitems',
            name='ItemID',
        ),
        migrations.DeleteModel(
            name='T_Invoices',
        ),
        migrations.DeleteModel(
            name='TC_InvoiceItemBatches',
        ),
        migrations.DeleteModel(
            name='TC_InvoiceItems',
        ),
    ]
