# Generated by Django 3.0.8 on 2022-12-01 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0070_mc_billofmaterialitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_billofmaterial',
            name='CreatedBy',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_billofmaterial',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
