# Generated by Django 3.0.8 on 2023-02-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0070_auto_20230202_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_ItemDivisions',
        ),
    ]
