# Generated by Django 3.0.8 on 2023-02-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0071_delete_mc_itemdivisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partyitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartyItem', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='mc_partyitems',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Party', to='FoodERPApp.M_Parties'),
        ),
    ]
