# Generated by Django 3.0.8 on 2022-06-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0071_auto_20220621_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceDate', models.DateField(auto_now_add=True)),
                ('CustomerID', models.IntegerField()),
                ('InvoiceNumber', models.IntegerField(blank=True, null=True)),
                ('FullInvoiceNumber', models.CharField(max_length=500)),
                ('CustomerGSTTin', models.CharField(max_length=500)),
                ('GrandTotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PartyID', models.IntegerField(blank=True, null=True)),
                ('RoundOffAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_Orders')),
            ],
            options={
                'db_table': 'T_Invoices',
            },
        ),
        migrations.CreateModel(
            name='TC_InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HSNCode', models.CharField(max_length=500)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('UnitID', models.IntegerField()),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('QtyInKg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QtyInNo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QtyInBox', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DiscountType', models.CharField(max_length=500)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceItems', to='FoodERPApp.T_Invoices')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'TC_InvoiceItems',
            },
        ),
        migrations.CreateModel(
            name='TC_InvoiceItemBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('UnitID', models.IntegerField()),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_Invoices')),
                ('InvoiceItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceItemBatches', to='FoodERPApp.TC_InvoiceItems')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'TC_InvoiceItemBatches',
            },
        ),
    ]
