# Generated by Django 3.0.8 on 2022-12-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0071_auto_20221201_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_billofmaterial',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='m_billofmaterial',
            name='CreatedOn',
        ),
    ]
