# Generated by Django 3.0.8 on 2023-07-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0071_auto_20230718_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_datewiselivestock',
            name='Unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DStockUnit', to='FoodERPApp.MC_ItemUnits'),
            preserve_default=False,
        ),
    ]
