# Generated by Django 3.0.8 on 2023-02-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0072_auto_20230203_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_demanditems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tc_demanditems',
            name='Rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
