# Generated by Django 3.0.8 on 2023-07-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0072_o_datewiselivestock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_datewiselivestock',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DStockParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
