# Generated by Django 3.0.8 on 2022-12-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0072_auto_20221201_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_billofmaterial',
            name='CreatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_billofmaterial',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
