# Generated by Django 3.0.8 on 2023-02-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0073_auto_20230204_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_itemunits',
            name='BaseUnitConversion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
