# Generated by Django 3.0.8 on 2023-07-18 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0073_o_datewiselivestock_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_datewiselivestock',
            name='CreatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_datewiselivestock',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o_datewiselivestock',
            name='IsAdjusted',
            field=models.BooleanField(default=False),
        ),
    ]
