# Generated by Django 3.0.8 on 2023-02-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0074_mc_itemunits_baseunitconversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_itemunits',
            name='BaseUnitConversion',
        ),
    ]
