# Generated by Django 3.0.8 on 2022-12-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0074_remove_m_billofmaterial_createdon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_billofmaterialitems',
            name='BOM',
        ),
        migrations.RemoveField(
            model_name='mc_billofmaterialitems',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='mc_billofmaterialitems',
            name='Unit',
        ),
        migrations.DeleteModel(
            name='M_BillOfMaterial',
        ),
        migrations.DeleteModel(
            name='MC_BillOfMaterialItems',
        ),
    ]
