# Generated by Django 3.0.8 on 2022-06-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0074_t_invoices_tc_invoiceitembatches_tc_invoiceitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_invoices',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_invoices',
            name='PartyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Party', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
