# Generated by Django 3.0.8 on 2023-07-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0074_auto_20230718_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_datewiselivestock',
            name='MRPValue',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mc_partysubparty',
            name='Route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MCSubPartyRoute', to='FoodERPApp.M_Routes'),
        ),
        migrations.AlterField(
            model_name='mc_partysubparty',
            name='SubParty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MCSubParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_partysubpartyopeningbalance',
            name='SubParty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MSubParty', to='FoodERPApp.M_Parties'),
        ),
    ]
