# Generated by Django 3.0.8 on 2022-06-21 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0075_auto_20220621_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderCustomer', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='PartyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderParty', to='FoodERPApp.M_Parties'),
        ),
    ]
