# Generated by Django 3.0.8 on 2023-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0075_remove_mc_itemunits_baseunitconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_interbranchchallanitems',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tc_interbranchchallanitems',
            name='DiscountAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='DiscountAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tc_interbranchinwarditems',
            name='GST',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
