# Generated by Django 3.0.8 on 2022-12-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0075_auto_20221201_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_BillOfMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('EstimatedOutput', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Comment', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BOMUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'M_BillOfMaterial',
            },
        ),
        migrations.CreateModel(
            name='MC_BillOfMaterialItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('BOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BOMItems', to='FoodERPApp.M_BillOfMaterial')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BOMItemUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'MC_BillOfMaterialItems',
            },
        ),
    ]
