# Generated by Django 3.0.8 on 2022-06-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0076_auto_20220621_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='CustomerID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='PartyID',
            field=models.IntegerField(),
        ),
    ]
