# Generated by Django 3.0.8 on 2023-07-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0076_m_discountmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_discountmaster',
            name='PriceList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DiscountPriceList', to='FoodERPApp.M_PriceList'),
            preserve_default=False,
        ),
    ]
