# Generated by Django 3.0.8 on 2022-06-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0077_auto_20220621_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_items',
            name='ItemGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemGroup', to='FoodERPApp.M_ItemsGroup'),
        ),
    ]
