# Generated by Django 3.0.8 on 2023-02-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0077_mc_itemunits_baseunitconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partyitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemDivisionDetails', to='FoodERPApp.M_Items'),
        ),
    ]
