# Generated by Django 3.0.8 on 2022-06-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0077_auto_20220621_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='ItemID',
        ),
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='OrderID',
        ),
        migrations.AlterField(
            model_name='t_invoices',
            name='OrderID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='T_Orders',
        ),
        migrations.DeleteModel(
            name='TC_OrderItems',
        ),
    ]
