# Generated by Django 3.0.8 on 2022-12-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0078_m_billofmaterial_mc_billofmaterialitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_billofmaterial',
            name='Company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
