# Generated by Django 3.0.8 on 2023-02-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0078_auto_20230207_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_livebatches',
            name='MRP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ObatchwiseItemMrp', to='FoodERPApp.M_MRPMaster'),
        ),
    ]
