# Generated by Django 3.0.8 on 2023-07-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0078_m_discountmaster_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_discountmaster',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DiscountParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
