# Generated by Django 3.0.8 on 2022-12-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0079_m_billofmaterial_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='Inward',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
