# Generated by Django 3.0.8 on 2023-02-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0079_auto_20230208_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_invoiceitems',
            name='MRP',
        ),
    ]
