# Generated by Django 3.0.8 on 2022-06-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0080_auto_20220621_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('OrderAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Discreption', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderCustomer', to='FoodERPApp.M_Parties')),
                ('PartyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'T_Orders',
            },
        ),
        migrations.CreateModel(
            name='TC_OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('UnitID', models.IntegerField()),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('GST', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='FoodERPApp.M_Items')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItem', to='FoodERPApp.T_Orders')),
            ],
            options={
                'db_table': 'TC_OrderItems',
            },
        ),
    ]
