# Generated by Django 3.0.8 on 2023-07-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0080_m_discountmaster_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_companies',
            name='CompanyGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CompanyGroup', to='FoodERPApp.C_CompanyGroups'),
        ),
        migrations.AlterField(
            model_name='m_category',
            name='CategoryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CategoryType', to='FoodERPApp.M_CategoryType'),
        ),
        migrations.AlterField(
            model_name='m_districts',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DistrictState', to='FoodERPApp.M_States'),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EmployeesCity', to='FoodERPApp.M_Cities'),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EmployeesCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EmployeesDistrict', to='FoodERPApp.M_Districts'),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='EmployeeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EmployeeType', to='FoodERPApp.M_EmployeeTypes'),
        ),
        migrations.AlterField(
            model_name='m_employees',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EmployeesState', to='FoodERPApp.M_States'),
        ),
        migrations.AlterField(
            model_name='m_fieldvalidations',
            name='ControlType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FieldControlType', to='FoodERPApp.M_ControlTypeMaster'),
        ),
        migrations.AlterField(
            model_name='m_group',
            name='GroupType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GroupType', to='FoodERPApp.M_GroupType'),
        ),
        migrations.AlterField(
            model_name='m_gsthsncode',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GstCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='m_items',
            name='BaseUnitID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BaseUnitID', to='FoodERPApp.M_Units'),
        ),
        migrations.AlterField(
            model_name='m_items',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='m_marginmaster',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MarginCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='m_marginmaster',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MarginParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='m_marginmaster',
            name='PriceList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PriceList', to='FoodERPApp.M_PriceList'),
        ),
        migrations.AlterField(
            model_name='m_mrpmaster',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MRPCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='m_mrpmaster',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MRPDivision', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='m_mrpmaster',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MRPParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='m_pages',
            name='Module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PagesModule', to='FoodERPApp.H_Modules'),
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartiesCities', to='FoodERPApp.M_Cities'),
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartiesDistrict', to='FoodERPApp.M_Districts'),
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='PriceList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyPriceList', to='FoodERPApp.M_PriceList'),
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartiesState', to='FoodERPApp.M_States'),
        ),
        migrations.AlterField(
            model_name='m_roleaccess',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RoleAccessCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='m_roleaccess',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RoleAccessDividion', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='m_roleaccess',
            name='Modules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RoleAccessModules', to='FoodERPApp.H_Modules'),
        ),
        migrations.AlterField(
            model_name='m_roleaccess',
            name='Pages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RoleAccessPages', to='FoodERPApp.M_Pages'),
        ),
        migrations.AlterField(
            model_name='m_roleaccess',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RoleAccessRole', to='FoodERPApp.M_Roles'),
        ),
        migrations.AlterField(
            model_name='m_users',
            name='Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserEmployee', to='FoodERPApp.M_Employees'),
        ),
        migrations.AlterField(
            model_name='mc_employeeparties',
            name='Party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Employeeparty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_itemcategorydetails',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemCategory', to='FoodERPApp.M_Category'),
        ),
        migrations.AlterField(
            model_name='mc_itemcategorydetails',
            name='CategoryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemCategoryType', to='FoodERPApp.M_CategoryType'),
        ),
        migrations.AlterField(
            model_name='mc_itemgroupdetails',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemGroup', to='FoodERPApp.M_Group'),
        ),
        migrations.AlterField(
            model_name='mc_itemgroupdetails',
            name='GroupType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemGroupType', to='FoodERPApp.M_GroupType'),
        ),
        migrations.AlterField(
            model_name='mc_itemgroupdetails',
            name='SubGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ItemSubGroup', to='FoodERPApp.MC_SubGroup'),
        ),
        migrations.AlterField(
            model_name='mc_itemimages',
            name='ImageType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ImageType', to='FoodERPApp.M_ImageTypes'),
        ),
        migrations.AlterField(
            model_name='mc_itemunits',
            name='UnitID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UnitID', to='FoodERPApp.M_Units'),
        ),
        migrations.AlterField(
            model_name='mc_managementparties',
            name='Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ManagementEmployee', to='FoodERPApp.M_Employees'),
        ),
        migrations.AlterField(
            model_name='mc_managementparties',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ManagementEmpparty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_pagefieldmaster',
            name='ControlType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ControlType', to='FoodERPApp.M_ControlTypeMaster'),
        ),
        migrations.AlterField(
            model_name='mc_pagefieldmaster',
            name='FieldValidation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FieldValidation', to='FoodERPApp.M_FieldValidations'),
        ),
        migrations.AlterField(
            model_name='mc_pagepageaccess',
            name='Access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.H_PageAccess'),
        ),
        migrations.AlterField(
            model_name='mc_partysubpartyopeningbalance',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_partysubpartyopeningbalance',
            name='SubParty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MSubParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_rolepageaccess',
            name='PageAccess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RolePageAccess', to='FoodERPApp.H_PageAccess'),
        ),
        migrations.AlterField(
            model_name='mc_rolesemployeetypes',
            name='EmployeeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_EmployeeTypes'),
        ),
        migrations.AlterField(
            model_name='mc_subgroup',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Group', to='FoodERPApp.M_Group'),
        ),
        migrations.AlterField(
            model_name='mc_userroles',
            name='Party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userparty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_userroles',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Role', to='FoodERPApp.M_Roles'),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OrderCustomer', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='Division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OrderDivision', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='POType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OrderPOType', to='FoodERPApp.M_POType'),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OrderSupplier', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GItem', to='FoodERPApp.M_Items'),
        ),
    ]
