# Generated by Django 3.0.8 on 2022-12-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0080_t_orders_inward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnitems',
            name='BatchCode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='BatchDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
