# Generated by Django 3.0.8 on 2023-02-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0080_remove_tc_invoiceitems_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='MRP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InvoiceItemMRP', to='FoodERPApp.M_MRPMaster'),
        ),
    ]
