# Generated by Django 3.0.8 on 2022-12-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0081_auto_20221202_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_billofmaterial',
            old_name='Date',
            new_name='BomDate',
        ),
    ]
