# Generated by Django 3.0.8 on 2023-02-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0081_tc_invoiceitems_mrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_invoiceitems',
            name='MRP',
        ),
    ]
