# Generated by Django 3.0.8 on 2022-06-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0081_t_orders_tc_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_invoices',
            name='OrderID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_Orders'),
            preserve_default=False,
        ),
    ]
