# Generated by Django 3.0.8 on 2023-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0081_auto_20230719_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_purchasereturn',
            name='Mode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
