# Generated by Django 3.0.8 on 2023-07-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0082_t_purchasereturn_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='SubReturn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
