# Generated by Django 3.0.8 on 2022-06-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0082_auto_20220621_1431'),
        ('FoodERPApp', '0036_auto_20220616_1247'),
    ]

    operations = [
    ]
