# Generated by Django 3.0.8 on 2022-12-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0082_auto_20221205_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkOrderDate', models.DateField()),
                ('NumberOfLot', models.IntegerField()),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BomID', to='FoodERPApp.M_BillOfMaterial')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.C_Companies')),
            ],
            options={
                'db_table': 'T_WorkOrder',
            },
        ),
        migrations.CreateModel(
            name='TC_WorkOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BomQuantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='WorkOrderUnitID', to='FoodERPApp.MC_ItemUnits')),
                ('WorkOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkOrderItems', to='FoodERPApp.T_WorkOrder')),
            ],
            options={
                'db_table': 'TC_WorkOrderItems',
            },
        ),
    ]
