# Generated by Django 3.0.8 on 2022-12-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0083_t_workorder_tc_workorderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_billofmaterialitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
