# Generated by Django 3.0.8 on 2023-02-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0083_auto_20230209_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_invoiceitems',
            name='GSTPercentage',
        ),
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='GST',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='InvoiceItemGST', to='FoodERPApp.M_GSTHSNCode'),
        ),
    ]
