# Generated by Django 3.0.8 on 2023-07-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0083_tc_purchasereturnitems_subreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_purchasereturnitems',
            name='SubReturn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
