# Generated by Django 3.0.8 on 2023-02-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0084_auto_20230209_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_invoices',
            name='CustomerGSTTin',
        ),
    ]
