# Generated by Django 3.0.8 on 2022-12-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0084_auto_20221206_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_workorder',
            name='Division',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_workorder',
            name='Item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_workorder',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_workorderitems',
            name='BomQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_workorderitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
