# Generated by Django 3.0.8 on 2022-06-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0084_auto_20220621_1500'),
        ('FoodERPApp', '0079_auto_20220621_1509'),
    ]

    operations = [
    ]
