# Generated by Django 3.0.8 on 2023-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0085_auto_20230724_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='BatchID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
