# Generated by Django 3.0.8 on 2022-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0085_merge_20220621_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='CreatedBy',
            field=models.IntegerField(default=False),
        ),
    ]
