# Generated by Django 3.0.8 on 2023-02-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0085_remove_t_invoices_customergsttin'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_VDCChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChallanDate', models.DateField()),
                ('ChallanNumber', models.IntegerField()),
                ('FullChallanNumber', models.CharField(max_length=500)),
                ('GrandTotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('RoundOffAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VDCChallanCustomer', to='FoodERPApp.M_Parties')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VDCChallanParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'T_VDCChallan',
            },
        ),
        migrations.CreateModel(
            name='TC_VDCChallanReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_GRNs')),
                ('VDCChallan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_VDCChallan')),
            ],
            options={
                'db_table': 'TC_VDCChallanReferences',
            },
        ),
        migrations.CreateModel(
            name='TC_VDCChallanItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DiscountType', models.CharField(blank=True, max_length=500, null=True)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('GST', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VDCChallanItemGST', to='FoodERPApp.M_GSTHSNCode')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('LiveBatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.O_LiveBatches')),
                ('MRP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VDCChallanItemMRP', to='FoodERPApp.M_MRPMaster')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VDCChallanUnitID', to='FoodERPApp.MC_ItemUnits')),
                ('VDCChallan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VDCChallanItems', to='FoodERPApp.T_VDCChallan')),
            ],
            options={
                'db_table': 'TC_VDCChallanItems',
            },
        ),
    ]
