# Generated by Django 3.0.8 on 2022-12-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0085_auto_20221206_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_billofmaterial',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
