# Generated by Django 3.0.8 on 2023-07-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0086_tc_purchasereturnitems_batchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_partysubparty',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MCParty', to='FoodERPApp.M_Parties'),
        ),
        migrations.AlterField(
            model_name='mc_partysubparty',
            name='SubParty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MCSubParty', to='FoodERPApp.M_Parties'),
        ),
    ]
