# Generated by Django 3.0.8 on 2022-06-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0086_auto_20220622_1154'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='m_employeetype',
            table='M_EmployeeTypes',
        ),
        migrations.AlterModelTable(
            name='m_state',
            table='M_States',
        ),
        migrations.DeleteModel(
            name='M_Employees',
        ),
    ]
