# Generated by Django 3.0.8 on 2022-06-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0087_auto_20220622_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_Designations',
        ),
        migrations.DeleteModel(
            name='M_EmployeeType',
        ),
        migrations.DeleteModel(
            name='M_State',
        ),
    ]
