# Generated by Django 3.0.8 on 2023-02-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0087_auto_20230211_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partyprefixs',
            name='VDCChallanprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
