# Generated by Django 3.0.8 on 2023-07-27 11:28

import FoodERPApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0087_auto_20230726_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitemimages',
            name='Image',
            field=models.ImageField(default='post/default.jpg', upload_to=FoodERPApp.models.upload_to, verbose_name='Image'),
        ),
    ]
