# Generated by Django 3.0.8 on 2022-12-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0087_auto_20221207_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_MaterialIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaterialIssueDate', models.DateField()),
                ('NumberOfLot', models.IntegerField()),
                ('LotQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Status', models.IntegerField()),
                ('ReIssueID', models.IntegerField()),
                ('IsReIssueID', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now_add=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.C_Companies')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Parties')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'T_MaterialIssue',
            },
        ),
        migrations.CreateModel(
            name='TC_MaterialIssueItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkOrderQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('IssueQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('MaterialIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MaterialIssueItems', to='FoodERPApp.T_MaterialIssue')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MaterialIssueUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'TC_MaterialIssueItems',
            },
        ),
        migrations.CreateModel(
            name='TC_MaterialIssueItemBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchDate', models.DateField()),
                ('BatchCode', models.CharField(max_length=500)),
                ('BatchCodeQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('IsssueQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('StoreLocation', models.IntegerField()),
                ('SupplierBatchCode', models.CharField(max_length=500)),
                ('BestBefore', models.CharField(max_length=500)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('MaterialIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_MaterialIssue')),
                ('MaterialIssueItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MaterialIssueItemBatches', to='FoodERPApp.TC_MaterialIssueItems')),
            ],
            options={
                'db_table': 'TC_MaterialIssueItemBatches',
            },
        ),
    ]
