# Generated by Django 3.0.8 on 2023-02-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0088_mc_partyprefixs_vdcchallanprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_vdcchallanitems',
            name='GRN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_GRNs'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TC_VDCChallanReferences',
        ),
    ]
