# Generated by Django 3.0.8 on 2022-12-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0088_t_materialissue_tc_materialissueitembatches_tc_materialissueitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_MaterialIssueWorkOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaterialIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.T_MaterialIssue')),
                ('WorkOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc', to='FoodERPApp.T_WorkOrder')),
            ],
            options={
                'db_table': 'TC_MaterialIssueWorkOrders',
            },
        ),
    ]
