# Generated by Django 3.0.8 on 2023-07-27 13:34

import FoodERPApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0088_tc_purchasereturnitemimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_purchasereturnitemimages',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=FoodERPApp.models.upload_to, verbose_name='Image'),
        ),
    ]
