# Generated by Django 3.0.8 on 2023-02-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0089_auto_20230211_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_vdcchallanitems',
            name='GRN',
        ),
        migrations.AddField(
            model_name='t_vdcchallan',
            name='GRN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_GRNs'),
            preserve_default=False,
        ),
    ]
