# Generated by Django 3.0.8 on 2023-02-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0090_auto_20230211_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceDate', models.DateField()),
                ('InvoiceNumber', models.IntegerField()),
                ('FullInvoiceNumber', models.CharField(max_length=500)),
                ('GrandTotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('RoundOffAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ChallanCustomer', to='FoodERPApp.M_Parties')),
                ('GRN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_GRNs')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ChallanParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'T_Challan',
            },
        ),
        migrations.CreateModel(
            name='TC_ChallanItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DiscountType', models.CharField(blank=True, max_length=500, null=True)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChallanItems', to='FoodERPApp.T_Challan')),
                ('GST', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ChallanItemGST', to='FoodERPApp.M_GSTHSNCode')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('LiveBatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.O_LiveBatches')),
                ('MRP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ChallanItemMRP', to='FoodERPApp.M_MRPMaster')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ChallanUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'TC_ChallanItems',
            },
        ),
        migrations.RemoveField(
            model_name='tc_vdcchallanitems',
            name='GST',
        ),
        migrations.RemoveField(
            model_name='tc_vdcchallanitems',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='tc_vdcchallanitems',
            name='LiveBatch',
        ),
        migrations.RemoveField(
            model_name='tc_vdcchallanitems',
            name='MRP',
        ),
        migrations.RemoveField(
            model_name='tc_vdcchallanitems',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='tc_vdcchallanitems',
            name='VDCChallan',
        ),
        migrations.DeleteModel(
            name='T_VDCChallan',
        ),
        migrations.DeleteModel(
            name='TC_VDCChallanItems',
        ),
    ]
