# Generated by Django 3.0.8 on 2023-02-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0091_auto_20230211_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_partyprefixs',
            name='VDCChallanprefix',
        ),
    ]
