# Generated by Django 3.0.8 on 2022-12-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0091_auto_20221208_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
