# Generated by Django 3.0.8 on 2022-06-22 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0091_m_designations_m_employeetypes_m_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('DOB', models.CharField(max_length=100)),
                ('PAN', models.CharField(max_length=100)),
                ('AadharNo', models.CharField(max_length=100)),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('CreatedOn', models.DateTimeField(blank=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedOn', models.DateTimeField(blank=True, null=True)),
                ('Companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.C_Companies')),
                ('Designations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Designations')),
                ('EmployeeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_EmployeeTypes')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_States')),
            ],
            options={
                'db_table': 'M_Employees',
            },
        ),
    ]
