# Generated by Django 3.0.8 on 2022-12-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0092_tc_orderitems_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_ordertermsandconditions',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
