# Generated by Django 3.0.8 on 2022-12-12 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0092_tc_orderitems_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_materialissueitems',
            name='BatchCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_materialissueitems',
            name='BatchCodeQuantity',
            field=models.DecimalField(decimal_places=3, default=django.utils.timezone.now, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_materialissueitems',
            name='BatchDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_materialissueitems',
            name='SupplierBatchCode',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_materialissueitems',
            name='SystemBatchDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TC_MaterialIssueItemBatches',
        ),
    ]
