# Generated by Django 3.0.8 on 2023-07-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0092_m_masterclaim_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_masterclaim',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
