# Generated by Django 3.0.8 on 2022-06-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0092_m_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_employees',
            old_name='Designations',
            new_name='Designation',
        ),
    ]
