# Generated by Django 3.0.8 on 2023-02-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0092_remove_mc_partyprefixs_vdcchallanprefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_challan',
            name='RoundOffAmount',
        ),
    ]
