# Generated by Django 3.0.8 on 2022-12-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0093_auto_20221212_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TC_MaterialIssueItems',
        ),
    ]
