# Generated by Django 3.0.8 on 2022-12-12 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0093_tc_ordertermsandconditions_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_ordertermsandconditions',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
