# Generated by Django 3.0.8 on 2023-02-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0093_remove_t_challan_roundoffamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_challanitems',
            name='LiveBatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.O_LiveBatches'),
        ),
    ]
