# Generated by Django 3.0.8 on 2022-06-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0093_auto_20220622_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_DivisionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'M_DivisionType',
            },
        ),
    ]
