# Generated by Django 3.0.8 on 2022-12-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0094_delete_tc_materialissueitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_MaterialIssueItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkOrderQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('IssueQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('BatchDate', models.DateField()),
                ('BatchCode', models.CharField(max_length=500)),
                ('BatchCodeQuantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('SystemBatchDate', models.DateField()),
                ('SupplierBatchCode', models.CharField(max_length=500)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('MaterialIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MaterialIssueItems', to='FoodERPApp.T_MaterialIssue')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MaterialIssueUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'TC_MaterialIssueItems',
            },
        ),
    ]
