# Generated by Django 3.0.8 on 2023-02-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0094_auto_20230211_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_challan',
            old_name='InvoiceDate',
            new_name='ChallanDate',
        ),
        migrations.RenameField(
            model_name='t_challan',
            old_name='InvoiceNumber',
            new_name='ChallanNumber',
        ),
        migrations.RenameField(
            model_name='t_challan',
            old_name='FullInvoiceNumber',
            new_name='FullChallanNumber',
        ),
    ]
