# Generated by Django 3.0.8 on 2023-02-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0095_auto_20230211_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_pricelist',
            name='CalculationPath',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
