# Generated by Django 3.0.8 on 2022-06-24 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0095_m_partytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='CreatedBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        
    ]
