# Generated by Django 3.0.8 on 2023-07-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0095_remove_m_masterclaim_itemreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_MasterClaimDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReturnAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('NetSaleValue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Budget', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ClaimAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ClaimAgainstNetSale', models.DecimalField(decimal_places=2, max_digits=20)),
                ('MasterClaim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MasterClaim', to='FoodERPApp.M_MasterClaim')),
            ],
            options={
                'db_table': 'MC_MasterClaimDetails',
            },
        ),
    ]
