# Generated by Django 3.0.8 on 2022-06-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0096_auto_20220624_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_orders',
            old_name='Discreption',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='BasicAmount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
