# Generated by Django 3.0.8 on 2023-07-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0096_mc_masterclaimdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_masterclaimdetails',
            name='Item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimmItem', to='FoodERPApp.M_Items'),
            preserve_default=False,
        ),
    ]
