# Generated by Django 3.0.8 on 2022-12-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0093_tc_ordertermsandconditions_isdeleted'),
        ('FoodERPApp', '0097_t_materialissue_tc_materialissueitems_tc_materialissueworkorders'),
    ]

    operations = [
    ]
