# Generated by Django 3.0.8 on 2023-07-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0097_mc_masterclaimdetails_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_masterclaimdetails',
            name='ItemReason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimItemReason', to='FoodERPApp.M_GeneralMaster'),
            preserve_default=False,
        ),
    ]
