# Generated by Django 3.0.8 on 2023-02-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0097_m_billofmaterial_isvdcitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_challan',
            name='GRN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_GRNs'),
        ),
    ]
