# Generated by Django 3.0.8 on 2023-02-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0098_auto_20230216_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_grnreferences',
            name='Challan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.T_Challan'),
        ),
    ]
