# Generated by Django 3.0.8 on 2022-06-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0098_auto_20220624_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_pages',
            name='Description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
