# Generated by Django 3.0.8 on 2023-07-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0098_mc_masterclaimdetails_itemreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_masterclaimdetails',
            name='PrimaryAmount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mc_masterclaimdetails',
            name='SecondaryAmount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
