# Generated by Django 3.0.8 on 2022-12-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0098_merge_20221212_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_workorder',
            name='Unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='WorkOrderUnitID', to='FoodERPApp.MC_ItemUnits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tc_workorderitems',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='WorkOrderItemUnitID', to='FoodERPApp.MC_ItemUnits'),
        ),
    ]
