# Generated by Django 3.0.8 on 2023-02-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0099_tc_grnreferences_challan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_ProductionReIssueItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueQuantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('BatchDate', models.DateField()),
                ('BatchCode', models.CharField(max_length=500)),
                ('SystemBatchDate', models.DateField()),
                ('SystemBatchCode', models.CharField(max_length=500)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items')),
                ('LiveBatchID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.O_LiveBatches')),
                ('ProductionReIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductionReIssueItems', to='FoodERPApp.T_MaterialIssue')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProductionReIssueItemUnitID', to='FoodERPApp.MC_ItemUnits')),
            ],
            options={
                'db_table': 'TC_ProductionReIssueItems',
            },
        ),
        migrations.CreateModel(
            name='T_ProductionReIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('ProductionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Production', to='FoodERPApp.T_Production')),
                ('ProductionItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProductionItem', to='FoodERPApp.M_Items')),
            ],
            options={
                'db_table': 'TC_ProductionReIssue',
            },
        ),
    ]
