# Generated by Django 3.0.8 on 2023-02-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0100_t_productionreissue_tc_productionreissueitems'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='t_productionreissue',
            table='T_ProductionReIssue',
        ),
    ]
