# Generated by Django 3.0.8 on 2022-06-28 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0100_auto_20220624_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_parties',
            old_name='GSTN',
            new_name='GSTIN',
        ),
        migrations.AlterField(
            model_name='mc_userroles',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoleID', to=settings.AUTH_USER_MODEL),
        ),
    ]
