# Generated by Django 3.0.8 on 2023-07-29 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0101_thirdpartyapitransactionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_stock',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='t_stock',
            name='UpdatedOn',
        ),
        migrations.AddField(
            model_name='o_batchwiselivestock',
            name='Stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='StockID', to='FoodERPApp.T_Stock'),
            preserve_default=False,
        ),
    ]
