# Generated by Django 3.0.8 on 2022-06-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0101_auto_20220628_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_parties',
            old_name='GSTIN',
            new_name='GSTN',
        ),
    ]
