# Generated by Django 3.0.8 on 2022-06-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0102_auto_20220628_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='PhoneNo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
