# Generated by Django 3.0.8 on 2023-07-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0102_mc_returnreasonwisemasterclaim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_stock',
            old_name='BaseunitQuantity',
            new_name='BaseUnitQuantity',
        ),
        migrations.RemoveField(
            model_name='t_stock',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='t_stock',
            name='UpdatedOn',
        ),
    ]
