# Generated by Django 3.0.8 on 2022-06-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0102_auto_20220629_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='CreatedOn',
        ),
    ]
