# Generated by Django 3.0.8 on 2023-02-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0102_auto_20230218_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_productionreissueitems',
            name='ProductionReIssue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductionItemsReIssue', to='FoodERPApp.T_ProductionReIssue'),
        ),
    ]
