# Generated by Django 3.0.8 on 2022-06-29 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0103_remove_tc_orderitems_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
