# Generated by Django 3.0.8 on 2023-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0103_auto_20230729_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_stock',
            name='LiveBatche',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
