# Generated by Django 3.0.8 on 2023-07-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0103_auto_20230729_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o_batchwiselivestock',
            name='Stock',
        ),
    ]
