# Generated by Django 3.0.8 on 2022-06-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0103_m_parties_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_parties',
            old_name='GSTN',
            new_name='GSTIN',
        ),
    ]
