# Generated by Django 3.0.8 on 2022-06-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0104_tc_orderitems_createdon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_orders',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='BasicAmount',
        ),
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='GSTAmount',
        ),
    ]
