# Generated by Django 3.0.8 on 2023-02-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0104_auto_20230218_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_productionreissue',
            name='ProductionItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PItem', to='FoodERPApp.M_Items'),
        ),
        migrations.AlterField(
            model_name='tc_productionreissueitems',
            name='ProductionReIssue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductionReIssueItems', to='FoodERPApp.T_ProductionReIssue'),
        ),
    ]
