# Generated by Django 3.0.8 on 2023-07-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0104_t_stock_livebatche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_returnreasonwisemasterclaim',
            name='ItemReason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ClaimmItemReason', to='FoodERPApp.M_GeneralMaster'),
        ),
    ]
