# Generated by Django 3.0.8 on 2022-06-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0105_auto_20220628_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_parties',
            old_name='PhoneNo',
            new_name='MobileNo',
        ),
    ]
