# Generated by Django 3.0.8 on 2023-02-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0105_auto_20230218_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_productionreissue',
            name='ProductionItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProductionItem', to='FoodERPApp.M_Items'),
        ),
    ]
