# Generated by Django 3.0.8 on 2022-06-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0105_auto_20220629_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='Description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
