# Generated by Django 3.0.8 on 2023-07-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0105_auto_20230729_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_stock',
            name='LiveBatche',
        ),
    ]
