# Generated by Django 3.0.8 on 2022-06-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0106_t_orders_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='BasicAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='GSTAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
