# Generated by Django 3.0.8 on 2022-06-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0106_auto_20220628_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='MobileNo',
        ),
    ]
