# Generated by Django 3.0.8 on 2022-06-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0107_remove_m_parties_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='PhoneNo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
