# Generated by Django 3.0.8 on 2022-06-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0107_auto_20220629_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='BasicAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='GSTAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
