# Generated by Django 3.0.8 on 2023-02-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0107_auto_20230222_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_orders',
            name='IsOpenPO',
        ),
    ]
