# Generated by Django 3.0.8 on 2022-06-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0108_m_parties_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_parties',
            name='PhoneNo',
        ),
    ]
