# Generated by Django 3.0.8 on 2023-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0108_auto_20230731_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_invoices',
            name='Hide',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
