# Generated by Django 3.0.8 on 2022-06-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0108_auto_20220629_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='GSTAmount',
        ),
    ]
