# Generated by Django 3.0.8 on 2023-03-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0109_m_routes_m_salesman_t_purchasereturn_tc_purchasereturnitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partysubparty',
            name='Route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MCSubPartyRoute', to='FoodERPApp.M_Routes'),
        ),
    ]
