# Generated by Django 3.0.8 on 2023-08-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0109_t_invoices_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_invoices',
            name='Hide',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
