# Generated by Django 3.0.8 on 2022-06-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0109_remove_tc_orderitems_gstamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='GSTAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
