# Generated by Django 3.0.8 on 2022-06-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0109_remove_m_parties_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='MobileNo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
