# Generated by Django 3.0.8 on 2023-03-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0110_mc_partysubparty_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partysubparty',
            name='Creditlimit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
