# Generated by Django 3.0.8 on 2022-06-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0110_m_parties_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='MobileNo',
            field=models.IntegerField(unique=True),
        ),
    ]
