# Generated by Django 3.0.8 on 2023-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0110_auto_20230801_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'M_TransactionType',
            },
        ),
    ]
