# Generated by Django 3.0.8 on 2023-08-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0111_m_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='TransactionType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Transactiontype', to='FoodERPApp.M_TransactionType'),
            preserve_default=False,
        ),
    ]
