# Generated by Django 3.0.8 on 2023-03-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0111_mc_partysubparty_creditlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('IFSC', models.CharField(blank=True, max_length=500, null=True)),
                ('BranchName', models.CharField(max_length=500)),
                ('AccountNo', models.CharField(blank=True, max_length=500, null=True)),
                ('IsSelfDepositoryBank', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartyBank', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'M_Bank',
            },
        ),
    ]
