# Generated by Django 3.0.8 on 2022-06-28 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0111_auto_20220628_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_parties',
            name='MobileNo',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
