# Generated by Django 3.0.8 on 2023-03-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0112_m_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_pricelist',
            name='CalculationPath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='m_pricelist',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PriceListCompany', to='FoodERPApp.C_Companies'),
        ),
        migrations.AlterField(
            model_name='m_pricelist',
            name='PLPartyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PriceListPartyType', to='FoodERPApp.M_PartyType'),
        ),
    ]
