# Generated by Django 3.0.8 on 2022-06-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0110_tc_orderitems_gstamount'),
        ('FoodERPApp', '0112_auto_20220628_1711'),
    ]

    operations = [
    ]
