# Generated by Django 3.0.8 on 2022-06-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0113_merge_20220629_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='GSTAmount',
        ),
        migrations.AddField(
            model_name='m_states',
            name='StateCode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='MobileNo',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='BasicAmount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
