# Generated by Django 3.0.8 on 2023-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0113_auto_20230804_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='TransactionType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
