# Generated by Django 3.0.8 on 2022-06-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0114_auto_20220629_1236'),
        ('FoodERPApp', '0113_auto_20220629_1139'),
    ]

    operations = [
    ]
