# Generated by Django 3.0.8 on 2023-08-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0114_auto_20230804_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='TransactionType',
            field=models.IntegerField(default=1),
        ),
    ]
