# Generated by Django 3.0.8 on 2022-06-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0115_merge_20220629_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_orderitems',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tc_orderitems',
            name='GSTAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_parties',
            name='MobileNo',
            field=models.BigIntegerField(unique=True),
        ),
    ]
