# Generated by Django 3.0.8 on 2023-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0115_auto_20230804_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='TransactionID',
            field=models.IntegerField(default=1),
        ),
    ]
