# Generated by Django 3.0.8 on 2023-08-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0116_transactionlog_transactionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedT_Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice', models.IntegerField(null=True)),
                ('InvoiceDate', models.DateField()),
                ('InvoiceNumber', models.IntegerField(null=True)),
                ('FullInvoiceNumber', models.CharField(max_length=500)),
                ('GrandTotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('RoundOffAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CreatedBy', models.IntegerField(null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(null=True)),
                ('UpdatedOn', models.DateTimeField()),
                ('Customer', models.IntegerField(null=True)),
                ('Driver', models.IntegerField(null=True)),
                ('Party', models.IntegerField(null=True)),
                ('Vehicle', models.IntegerField(null=True)),
                ('TCSAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Hide', models.CharField(default=0, max_length=500)),
                ('DeletedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DeletedT_Invoices',
            },
        ),
        migrations.CreateModel(
            name='DeletedTC_InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('BaseUnitQuantity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('MRPValue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('BasicAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('TaxType', models.CharField(max_length=500)),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('GSTAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DiscountType', models.CharField(blank=True, max_length=500, null=True)),
                ('Discount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('DiscountAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=20)),
                ('CGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('SGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IGSTPercentage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('BatchDate', models.DateField(blank=True, null=True)),
                ('BatchCode', models.CharField(max_length=500)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('GST', models.IntegerField(null=True)),
                ('Invoice', models.IntegerField(null=True)),
                ('Item', models.IntegerField(null=True)),
                ('LiveBatch', models.IntegerField(null=True)),
                ('MRP', models.IntegerField(null=True)),
                ('Unit', models.IntegerField(null=True)),
                ('QtyInNo', models.DecimalField(decimal_places=20, max_digits=30)),
                ('QtyInKg', models.DecimalField(decimal_places=20, max_digits=30)),
                ('QtyInBox', models.DecimalField(decimal_places=20, max_digits=30)),
            ],
            options={
                'db_table': 'DeletedTC_InvoiceItems',
            },
        ),
        migrations.CreateModel(
            name='DeletedTC_InvoicesReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice', models.IntegerField(null=True)),
                ('Order', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'DeletedTC_InvoicesReferences',
            },
        ),
        migrations.CreateModel(
            name='DeletedTC_InvoiceUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice', models.IntegerField(null=True)),
                ('AckNo', models.CharField(max_length=500, null=True)),
                ('Irn', models.CharField(max_length=500, null=True)),
                ('QRCodeUrl', models.CharField(max_length=500, null=True)),
                ('EInvoicePdf', models.CharField(max_length=500, null=True)),
                ('EwayBillNo', models.CharField(max_length=500, null=True)),
                ('EwayBillUrl', models.CharField(max_length=500, null=True)),
                ('EInvoiceCreatedBy', models.IntegerField(null=True)),
                ('EInvoiceCreatedOn', models.DateTimeField(null=True)),
                ('EwayBillCreatedBy', models.IntegerField(null=True)),
                ('EwayBillCreatedOn', models.DateTimeField(null=True)),
                ('EInvoiceCanceledBy', models.IntegerField(null=True)),
                ('EInvoiceCanceledOn', models.DateTimeField(null=True)),
                ('EwayBillCanceledBy', models.IntegerField(null=True)),
                ('EwayBillCanceledOn', models.DateTimeField(null=True)),
                ('EInvoiceIsCancel', models.BooleanField(default=False)),
                ('EwayBillIsCancel', models.BooleanField(default=False)),
                ('user_gstin', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'DeletedTC_InvoiceUploads',
            },
        ),
    ]
