# Generated by Django 3.0.8 on 2022-06-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0116_auto_20220629_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='tc_orderitems',
            name='GSTAmount',
        ),
    ]
