# Generated by Django 3.0.8 on 2023-08-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0117_deletedt_invoices_deletedtc_invoiceitems_deletedtc_invoicesreferences_deletedtc_invoiceuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_discountmaster',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
