# Generated by Django 3.0.8 on 2023-08-07 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0118_m_discountmaster_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_invoiceuploads',
            name='Invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InvoiceUploads', to='FoodERPApp.T_Invoices'),
        ),
    ]
