# Generated by Django 3.0.8 on 2023-08-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0118_m_discountmaster_isdeleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_MasterClaimDetails',
        ),
    ]
