# Generated by Django 3.0.8 on 2022-06-30 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0119_auto_20220629_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_RolePageAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageAccess', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.H_PageAccess')),
                ('RoleAccess', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_RoleAccess')),
            ],
        ),
    ]
