# Generated by Django 3.0.8 on 2023-08-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0119_auto_20230807_1911'),
        ('FoodERPApp', '0119_delete_mc_masterclaimdetails'),
    ]

    operations = [
    ]
