# Generated by Django 3.0.8 on 2022-06-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0120_mc_rolepageaccess'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mc_rolepageaccess',
            table='MC_RolePageAccess',
        ),
    ]
