# Generated by Django 3.0.8 on 2023-08-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0120_merge_20230808_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeletedT_Invoices',
            new_name='T_DeletedInvoices',
        ),
        migrations.RenameModel(
            old_name='DeletedTC_InvoiceItems',
            new_name='TC_DeletedInvoiceItems',
        ),
        migrations.RenameModel(
            old_name='DeletedTC_InvoicesReferences',
            new_name='TC_DeletedInvoicesReferences',
        ),
        migrations.RenameModel(
            old_name='DeletedTC_InvoiceUploads',
            new_name='TC_DeletedInvoiceUploads',
        ),
        migrations.AlterModelTable(
            name='t_deletedinvoices',
            table='T_DeletedInvoices',
        ),
        migrations.AlterModelTable(
            name='tc_deletedinvoiceitems',
            table='TC_DeletedInvoiceItems',
        ),
        migrations.AlterModelTable(
            name='tc_deletedinvoicesreferences',
            table='TC_DeletedInvoicesReferences',
        ),
        migrations.AlterModelTable(
            name='tc_deletedinvoiceuploads',
            table='TC_DeletedInvoiceUploads',
        ),
    ]
