# Generated by Django 3.0.8 on 2022-06-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0121_auto_20220630_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_rolepageaccess',
            name='RoleAccess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RolePageAccess', to='FoodERPApp.M_RoleAccess'),
        ),
    ]
