# Generated by Django 3.0.8 on 2023-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0121_auto_20230808_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='primarySource',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
