# Generated by Django 3.0.8 on 2022-06-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0120_auto_20220630_1132'),
        ('FoodERPApp', '0122_auto_20220630_1244'),
    ]

    operations = [
    ]
