# Generated by Django 3.0.8 on 2023-08-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0122_tc_purchasereturnitems_primarysource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_purchasereturnitems',
            name='primarySource',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
