# Generated by Django 3.0.8 on 2023-08-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0123_auto_20230809_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tc_purchasereturnitems',
            old_name='primarySource',
            new_name='primarySourceID',
        ),
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='ApprovedByCompany',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
