# Generated by Django 3.0.8 on 2022-06-30 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0124_auto_20220630_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_districts',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_States'),
        ),
        migrations.AlterField(
            model_name='m_items',
            name='ItemGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.M_ItemsGroup'),
        ),
        migrations.AlterField(
            model_name='m_pages',
            name='Module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='M_PagesModule', to='FoodERPApp.H_Modules'),
        ),
        migrations.AlterField(
            model_name='mc_pagepageaccess',
            name='AccessID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.H_PageAccess'),
        ),
        migrations.AlterField(
            model_name='tc_orderitems',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Items', to='FoodERPApp.M_Items'),
        ),
    ]
