# Generated by Django 3.0.8 on 2023-08-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0124_auto_20230810_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_deletedinvoices',
            name='Hide',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tc_purchasereturnitems',
            name='ApprovedByCompany',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
