# Generated by Django 3.0.8 on 2023-08-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0125_auto_20230811_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_invoices',
            name='Hide',
            field=models.BooleanField(),
        ),
    ]
