# Generated by Django 3.0.8 on 2022-06-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0070_m_employees_joining_date'),
        ('FoodERPApp', '0125_auto_20220630_1539'),
    ]

    operations = [
    ]
