# Generated by Django 3.0.8 on 2022-06-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0126_auto_20220630_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_orderitems',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Items', to='FoodERPApp.M_Items'),
        ),
    ]
