# Generated by Django 3.0.8 on 2023-08-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0127_auto_20230811_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='FinalApprovalDate',
            field=models.DateField(null=True),
        ),
    ]
