# Generated by Django 3.0.8 on 2023-08-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0128_tc_purchasereturnitems_finalapprovaldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='GSTPercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
