# Generated by Django 3.0.8 on 2023-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0129_tc_creditdebitnoteitems_gstpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_invoices',
            name='Hide',
            field=models.BooleanField(default=False),
        ),
    ]
