# Generated by Django 3.0.8 on 2023-08-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0131_auto_20230817_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='Budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
