# Generated by Django 3.0.8 on 2023-08-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0133_auto_20230819_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnitems',
            name='ApprovedDiscountAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
