# Generated by Django 3.0.8 on 2023-08-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0135_auto_20230822_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_Claim',
        ),
    ]
