# Generated by Django 3.0.8 on 2023-08-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0137_m_claim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_Claim',
        ),
    ]
