# Generated by Django 3.0.8 on 2023-08-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0138_delete_m_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('ClaimNo', models.IntegerField()),
                ('FullClaimNumber', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
