# Generated by Django 3.0.8 on 2023-08-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0139_m_claim'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='m_claim',
            table='M_Claim',
        ),
    ]
