# Generated by Django 3.0.8 on 2023-08-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0140_auto_20230822_1634'),
    ]

    operations = [
       
    ]
