# Generated by Django 3.0.8 on 2023-08-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0141_m_claim_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_claim',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimPParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
