# Generated by Django 3.0.8 on 2023-08-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0142_m_claim_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_claim',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimCustomer', to='FoodERPApp.M_Parties'),
        ),
    ]
