# Generated by Django 3.0.8 on 2023-08-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0143_m_claim_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_Claim',
        ),
    ]
