# Generated by Django 3.0.8 on 2023-08-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0144_delete_m_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('ClaimNo', models.IntegerField()),
                ('FullClaimNumber', models.CharField(max_length=500)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimCustomer', to='FoodERPApp.M_Parties')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ClaimPParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'M_Claim',
            },
        ),
    ]
