# Generated by Django 3.0.8 on 2023-08-23 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0145_m_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_claim',
            name='ClaimNo',
        ),
        migrations.RemoveField(
            model_name='m_claim',
            name='FullClaimNumber',
        ),
        migrations.AddField(
            model_name='m_claim',
            name='FromDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_claim',
            name='ToDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
