# Generated by Django 3.0.8 on 2023-08-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0146_auto_20230823_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_masterclaim',
            name='Claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Claim', to='FoodERPApp.M_Claim'),
        ),
    ]
