# Generated by Django 3.0.8 on 2023-08-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0147_m_masterclaim_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_returnreasonwisemasterclaim',
            name='Claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='RClaim', to='FoodERPApp.M_Claim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_masterclaim',
            name='Claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Claim', to='FoodERPApp.M_Claim'),
            preserve_default=False,
        ),
    ]
