# Generated by Django 3.0.8 on 2023-08-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0148_auto_20230823_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_claim',
            name='PrimaryAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='m_claim',
            name='ReturnAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='m_claim',
            name='SecondaryAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
