# Generated by Django 3.0.8 on 2023-09-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0149_auto_20230824_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='CustomerID',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='FromDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='ToDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
