# Generated by Django 3.0.8 on 2023-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0150_auto_20230901_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='DiscountAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='DiscountType',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='MRPValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='QtyInBox',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='QtyInKg',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='QtyInNo',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
