# Generated by Django 3.0.8 on 2023-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0151_auto_20230904_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='ItemComment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
