# Generated by Django 3.0.8 on 2023-09-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0152_tc_creditdebitnoteitems_itemcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_creditdebitnotes',
            name='Invoice',
        ),
    ]
