# Generated by Django 3.0.8 on 2023-09-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0154_m_channelwiseitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_channelwiseitems',
            name='PartyType',
        ),
    ]
