# Generated by Django 3.0.8 on 2023-09-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0155_remove_m_channelwiseitems_partytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_channelwiseitems',
            name='PartyType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ChannelPartyType', to='FoodERPApp.M_PartyType'),
            preserve_default=False,
        ),
    ]
