# Generated by Django 3.0.8 on 2023-09-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0157_tc_creditdebitnoteuploads'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tc_creditdebitnoteuploads',
            table='TC_CreditDebitNoteUploads',
        ),
    ]
