# Generated by Django 3.0.8 on 2023-09-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0158_auto_20230906_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_creditdebitnotes',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
