# Generated by Django 3.0.8 on 2023-09-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0160_tc_purchasereturnitemimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLogJsonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JsonData', models.TextField(blank=True)),
                ('Transactionlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactionlog', to='FoodERPApp.Transactionlog')),
            ],
            options={
                'db_table': 'TransactionLogJsonData',
            },
        ),
    ]
