# Generated by Django 3.0.8 on 2023-09-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0161_transactionlogjsondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_stock',
            name='BatchCode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='t_stock',
            name='Difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='t_stock',
            name='IsSaleable',
            field=models.BooleanField(default=False),
        ),
    ]
