# Generated by Django 3.0.8 on 2023-09-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0162_auto_20230915_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='L_TransactionDateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OldestTrnDate', models.DateField()),
                ('NewestTrnDate', models.DateField()),
                ('StockAdjustmentDate', models.DateField()),
                ('Party', models.IntegerField()),
                ('Item', models.IntegerField()),
            ],
            options={
                'db_table': 'L_TransactionDateLog',
            },
        ),
    ]
