# Generated by Django 3.0.8 on 2023-09-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0164_t_stock_batchcodeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_ClaimTrackingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Month', models.CharField(max_length=500, null=True)),
                ('year', models.CharField(max_length=500, null=True)),
                ('ClaimReceivedSource', models.CharField(max_length=500, null=True)),
                ('Type', models.IntegerField()),
                ('ClaimTrade', models.IntegerField()),
                ('TypeOfClaim', models.IntegerField()),
                ('ClaimAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Remark', models.CharField(max_length=500, null=True)),
                ('ClaimCheckBy', models.IntegerField()),
                ('CreditNotestatus', models.IntegerField()),
                ('CreditNoteNo', models.CharField(max_length=500, null=True)),
                ('CreditNoteDate', models.DateField()),
                ('CreditoteAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ClaimSummaryDate', models.DateField()),
                ('CreditNoteUpload', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tc_creditdebitnoteuploads',
            name='CRDRNote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CRDRNoteUploads', to='FoodERPApp.T_CreditDebitNotes'),
        ),
        migrations.AlterField(
            model_name='tc_invoiceuploads',
            name='Invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='InvoiceUploads', to='FoodERPApp.T_Invoices'),
        ),
    ]
