# Generated by Django 3.0.8 on 2023-09-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0165_auto_20230918_1309'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='t_claimtrackingentry',
            table='T_ClaimTrackingEntry',
        ),
    ]
