# Generated by Django 3.0.8 on 2023-09-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0166_auto_20230918_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_claimtrackingentry',
            name='Claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimTracking', to='FoodERPApp.M_Claim'),
            preserve_default=False,
        ),
    ]
