# Generated by Django 3.0.8 on 2023-09-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0167_t_claimtrackingentry_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_claimtrackingentry',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimTrackingParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
