# Generated by Django 3.0.8 on 2023-09-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0169_auto_20230918_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_claimtrackingentry',
            name='FullClaimNo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='t_claimtrackingentry',
            name='Claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimTracking', to='FoodERPApp.M_Claim'),
        ),
    ]
