# Generated by Django 3.0.8 on 2023-09-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0170_auto_20230922_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_claimtrackingentry',
            name='PartyType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimTrackingPartyType', to='FoodERPApp.M_PartyType'),
        ),
    ]
