# Generated by Django 3.0.8 on 2023-09-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0171_t_claimtrackingentry_partytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_claimtrackingentry',
            name='Claim',
        ),
    ]
