# Generated by Django 3.0.8 on 2023-09-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0172_remove_t_claimtrackingentry_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_claimtrackingentry',
            name='Claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ClaimTracking', to='FoodERPApp.M_Claim'),
        ),
    ]
