# Generated by Django 3.0.8 on 2023-09-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0173_t_claimtrackingentry_claim'),
        ('FoodERPApp', '0170_auto_20230920_1745'),
    ]

    operations = [
    ]
