# Generated by Django 3.0.8 on 2023-09-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0174_merge_20230930_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_stock',
            name='IsStockAdjustment',
            field=models.BooleanField(default=False),
        ),
    ]
