# Generated by Django 3.0.8 on 2023-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0175_t_stock_isstockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='IsApprovedParty',
            field=models.BooleanField(default=False),
        ),
    ]
