# Generated by Django 3.0.8 on 2023-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0176_m_parties_isapprovedparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_datewiselivestock',
            name='StockAdjustment',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
