# Generated by Django 3.0.8 on 2023-10-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0177_o_datewiselivestock_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='SkyggID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
