# Generated by Django 3.0.8 on 2023-10-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0178_m_parties_skyggid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_parties',
            old_name='SkyggID',
            new_name='SkyggeID',
        ),
    ]
