# Generated by Django 3.0.8 on 2023-10-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0179_auto_20231009_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_purchasereturnitemimages',
            name='Image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media'),
        ),
    ]
