# Generated by Django 3.0.8 on 2023-10-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0180_auto_20231011_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_purchasereturnitemimages',
            name='Image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
