# Generated by Django 3.0.8 on 2023-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0181_auto_20231011_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_purchasereturnitemimages',
            name='Image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images\\ReturnImages'),
        ),
    ]
