# Generated by Django 3.0.8 on 2023-10-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0184_m_items_skyggeproductid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_items',
            name='SkyggeProductID',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
