# Generated by Django 3.0.8 on 2023-10-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0185_auto_20231017_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='TransactionCategory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
