# Generated by Django 3.0.8 on 2023-10-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0186_transactionlog_transactioncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='TransactionCategory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
