# Generated by Django 3.0.8 on 2023-10-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0187_auto_20231019_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500, null=True)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'M_Cluster',
            },
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='TransactionCategory',
        ),
        migrations.AddField(
            model_name='m_transactiontype',
            name='TransactionCategory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
