# Generated by Django 3.0.8 on 2023-10-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0188_auto_20231020_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_SubCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500, null=True)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubClusters', to='FoodERPApp.M_Cluster')),
            ],
            options={
                'db_table': 'M_SubCluster',
            },
        ),
    ]
