# Generated by Django 3.0.8 on 2023-10-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0189_m_subcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_importfields',
            name='Sequence',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
