# Generated by Django 3.0.8 on 2023-10-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0190_m_importfields_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partyimportfields',
            name='Sequence',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
