# Generated by Django 3.0.8 on 2023-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0191_mc_partyimportfields_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_importfields',
            name='Sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mc_partyimportfields',
            name='Sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
