# Generated by Django 3.0.8 on 2023-10-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0192_auto_20231020_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_CentralServiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('HSNCode', models.CharField(max_length=500)),
                ('GSTPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isActive', models.BooleanField(default=False)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CentralServiceItemCompany', to='FoodERPApp.C_Companies')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CentralServiceItemUnit', to='FoodERPApp.M_Units')),
            ],
            options={
                'db_table': 'M_CentralServiceItems',
            },
        ),
    ]
