# Generated by Django 3.0.8 on 2023-10-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0193_m_centralserviceitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_CentralServiceItems',
        ),
    ]
