# Generated by Django 3.0.8 on 2023-10-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0195_m_centralserviceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_centralserviceitems',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='CentralServiceItemCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
