# Generated by Django 3.0.8 on 2023-10-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0197_remove_m_centralserviceitems_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_CentralServiceItemAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('CentralServiceItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CentralServiceItems', to='FoodERPApp.M_CentralServiceItems')),
            ],
            options={
                'db_table': 'MC_CentralServiceItemAssign',
            },
        ),
    ]
