# Generated by Django 3.0.8 on 2023-10-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0198_mc_centralserviceitemassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_centralserviceitemassign',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='CentralServiceItemParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
