# Generated by Django 3.0.8 on 2023-10-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0199_mc_centralserviceitemassign_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mc_centralserviceitemassign',
            name='Party',
        ),
    ]
