# Generated by Django 3.0.8 on 2023-10-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0200_remove_mc_centralserviceitemassign_party'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_CentralServiceItemAssign',
        ),
    ]
