# Generated by Django 3.0.8 on 2023-10-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0203_mc_centralserviceitemassign_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_centralserviceitems',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ServiceItemCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_centralserviceitems',
            name='Rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
