# Generated by Django 3.0.8 on 2023-10-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0204_auto_20231023_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_subcluster',
            name='Cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SubClusters', to='FoodERPApp.M_Cluster'),
        ),
    ]
