# Generated by Django 3.0.8 on 2023-10-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0205_auto_20231023_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_PartyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PartyDetailsParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'M_PartyDetails',
            },
        ),
    ]
