# Generated by Django 3.0.8 on 2023-10-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0206_m_partydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partydetails',
            name='Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyItemGroup', to='FoodERPApp.M_Group'),
        ),
    ]
