# Generated by Django 3.0.8 on 2023-10-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0207_m_partydetails_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partydetails',
            name='Cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyCluster', to='FoodERPApp.M_Cluster'),
        ),
    ]
