# Generated by Django 3.0.8 on 2023-10-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0209_m_partydetails_subcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_importfields',
            name='Format',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
