# Generated by Django 3.0.8 on 2023-10-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0210_m_importfields_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_importfields',
            name='Format',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
