# Generated by Django 3.0.8 on 2023-10-31 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0211_auto_20231030_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partydetails',
            name='Supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='PartyDetailSupplier', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
