# Generated by Django 3.0.8 on 2023-10-31 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0212_m_partydetails_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_partydetails',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyDetailSupplier', to='FoodERPApp.M_Parties'),
        ),
    ]
