# Generated by Django 3.0.8 on 2023-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0213_auto_20231031_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_claimtrackingentry',
            name='File',
            field=models.FileField(blank=True, default='', null=True, upload_to='Images\\ClaimTrackingFiles'),
        ),
    ]
