# Generated by Django 3.0.8 on 2023-11-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0215_auto_20231103_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_creditdebitnoteitems',
            name='ServiceItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_CentralServiceItems'),
        ),
    ]
