# Generated by Django 3.0.8 on 2023-11-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0216_tc_creditdebitnoteitems_serviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_creditdebitnoteitems',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FoodERPApp.M_Items'),
        ),
    ]
