# Generated by Django 3.0.8 on 2023-11-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0217_auto_20231103_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='TransactionDetails',
            field=models.CharField(max_length=2000),
        ),
    ]
