# Generated by Django 3.0.8 on 2023-11-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0219_auto_20231121_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_invoices',
            name='ImportFromExcel',
            field=models.BooleanField(default=False),
        ),
    ]
