# Generated by Django 3.0.8 on 2023-11-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0220_t_invoices_importfromexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_invoices',
            name='DeletedFromSAP',
            field=models.BooleanField(default=False),
        ),
    ]
