# Generated by Django 3.0.8 on 2023-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0221_t_invoices_deletedfromsap'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='UploadSalesDatafromExcelParty',
            field=models.BooleanField(default=False),
        ),
    ]
