# Generated by Django 3.0.8 on 2023-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0222_m_parties_uploadsalesdatafromexcelparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='MobileAppOrderFlag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mc_itemimages',
            name='Item_pic',
            field=models.FileField(blank=True, default='', null=True, upload_to='Images\\ItemImages'),
        ),
    ]
