# Generated by Django 3.0.8 on 2023-12-06 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0223_auto_20231202_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partydetails',
            name='GM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyDetailGM', to='FoodERPApp.M_Employees'),
        ),
    ]
