# Generated by Django 3.0.8 on 2023-12-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0225_m_partydetails_nh'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partydetails',
            name='RH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyDetailRH', to='FoodERPApp.M_Employees'),
        ),
    ]
