# Generated by Django 3.0.8 on 2023-12-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0228_m_partydetails_se'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partydetails',
            name='SO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyDetailSO', to='FoodERPApp.M_Employees'),
        ),
    ]
