# Generated by Django 3.0.8 on 2023-12-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0231_m_partydetails_mt'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_channelwiseitems',
            name='IsAvailableForOrdering',
            field=models.BooleanField(default=False),
        ),
    ]
