# Generated by Django 3.0.8 on 2023-12-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0232_m_channelwiseitems_isavailableforordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_pricelist',
            name='Sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='m_pricelist',
            name='ShortName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
