# Generated by Django 3.0.8 on 2023-12-11 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0233_auto_20231207_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_partydetails',
            name='ASM',
        ),
        migrations.RemoveField(
            model_name='m_partydetails',
            name='GM',
        ),
        migrations.RemoveField(
            model_name='m_partydetails',
            name='MT',
        ),
        migrations.RemoveField(
            model_name='m_partydetails',
            name='NH',
        ),
        migrations.RemoveField(
            model_name='m_partydetails',
            name='RH',
        ),
        migrations.RemoveField(
            model_name='m_partydetails',
            name='SE',
        ),
        migrations.RemoveField(
            model_name='m_partydetails',
            name='SO',
        ),
        migrations.RemoveField(
            model_name='m_partydetails',
            name='SR',
        ),
        
    ]
