# Generated by Django 3.0.8 on 2023-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0234_auto_20231211_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_partydetails',
            name='ASM',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_partydetails',
            name='GM',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_partydetails',
            name='MT',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_partydetails',
            name='NH',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_partydetails',
            name='RH',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_partydetails',
            name='SE',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_partydetails',
            name='SO',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_partydetails',
            name='SR',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
