# Generated by Django 3.0.8 on 2024-01-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0247_auto_20231223_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_claimtrackingentry',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
