# Generated by Django 3.0.8 on 2024-01-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0248_t_claimtrackingentry_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_purchasereturn',
            name='ASMApprovalUpload',
            field=models.FileField(blank=True, default='', null=True, upload_to='Images\\ReturnASMApprovalUpload'),
        ),
    ]
