# Generated by Django 3.0.8 on 2024-01-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0249_t_purchasereturn_asmapprovalupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_purchasereturn',
            name='ASMApprovalUpload',
        ),
    ]
