# Generated by Django 3.0.8 on 2024-01-30 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0251_t_purchasereturn_asmapprovalimgupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_receiptinvoices',
            name='Return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CRDRReturn', to='FoodERPApp.T_PurchaseReturn'),
        ),
    ]
