# Generated by Django 3.0.8 on 2024-01-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0252_tc_receiptinvoices_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_purchasereturn',
            name='IsApproved',
            field=models.IntegerField(default=0),
        ),
    ]
