# Generated by Django 3.0.8 on 2024-02-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0253_auto_20240131_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_receiptinvoices',
            name='Return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CRDRReturn', to='FoodERPApp.T_PurchaseReturn'),
        ),
    ]
