# Generated by Django 3.0.8 on 2024-02-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0254_auto_20240209_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_purchasereturn',
            name='ReturnReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ReturnReason', to='FoodERPApp.M_GeneralMaster'),
        ),
    ]
