# Generated by Django 3.0.8 on 2024-02-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0255_auto_20240212_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_creditdebitnotes',
            name='PurchaseReturn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FoodERPApp.T_PurchaseReturn'),
        ),
        migrations.AlterField(
            model_name='t_purchasereturn',
            name='ReturnReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReturnReason', to='FoodERPApp.M_GeneralMaster'),
        ),
    ]
