# Generated by Django 3.0.8 on 2024-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0256_auto_20240212_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='CItemID',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
