# Generated by Django 3.0.8 on 2024-02-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0257_m_items_citemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_employees',
            name='City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EmployeesCity', to='FoodERPApp.M_Cities'),
        ),
    ]
