# Generated by Django 3.0.8 on 2024-02-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0258_auto_20240228_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='SAPUnitID',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='m_partytype',
            name='SAPIndicator',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
