# Generated by Django 3.0.8 on 2024-03-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0259_auto_20240229_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_TargetUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.IntegerField(default=False)),
                ('Year', models.IntegerField(default=False)),
                ('TargetQuantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CreatedBy', models.IntegerField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TargetUploadsItem', to='FoodERPApp.M_Items')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TargetUploadsParty', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'T_TargetUploads',
            },
        ),
    ]
