# Generated by Django 3.0.8 on 2024-03-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0260_t_targetuploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_targetuploads',
            name='Party',
        ),
    ]
