# Generated by Django 3.0.8 on 2024-03-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0261_remove_t_targetuploads_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_targetuploads',
            name='Party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='TargetUploadsParty', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_targetuploads',
            name='SheetNo',
            field=models.IntegerField(default=False),
        ),
    ]
