# Generated by Django 3.0.8 on 2024-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0262_auto_20240302_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_targetuploads',
            name='TargetQuantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
