# Generated by Django 3.0.8 on 2024-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0263_auto_20240305_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_targetuploads',
            name='TargetQuantity',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
