# Generated by Django 3.0.8 on 2024-03-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0265_auto_20240321_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_targetuploads',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_targetuploads',
            name='QtyInBox',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_targetuploads',
            name='QtyInKg',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_targetuploads',
            name='QtyInNo',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_targetuploads',
            name='Rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_targetuploads',
            name='TargetQuantityInBaseUnit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_targetuploads',
            name='Unit',
            field=models.IntegerField(default=False),
        ),
    ]
