# Generated by Django 3.0.8 on 2024-03-22 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0266_auto_20240322_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partysubpartyopeningbalance',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
