# Generated by Django 3.0.8 on 2024-03-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0267_mc_partysubpartyopeningbalance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_claimtrackingentry',
            name='Claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ClaimTracking', to='FoodERPApp.M_Claim'),
        ),
    ]
