# Generated by Django 3.0.8 on 2024-03-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0268_auto_20240327_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_FinancialYearFirstTransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FinancialYear', models.IntegerField(default=False)),
                ('Party', models.IntegerField(default=False)),
                ('Flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'M_FinancialYearFirstTransactionLog',
            },
        ),
    ]
