# Generated by Django 3.0.8 on 2024-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0269_m_financialyearfirsttransactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_financialyearfirsttransactionlog',
            name='FinancialYear',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
