# Generated by Django 3.0.8 on 2024-03-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0270_auto_20240328_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_stock',
            name='Difference',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
