# Generated by Django 3.0.8 on 2024-04-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0271_auto_20240331_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_creditdebitnotes',
            name='ImportFromExcel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
