# Generated by Django 3.0.8 on 2024-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0272_t_creditdebitnotes_importfromexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_creditdebitnotes',
            name='ImportFromExcel',
            field=models.BooleanField(default=False),
        ),
    ]
