# Generated by Django 3.0.8 on 2024-04-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0275_remove_m_ratemaster_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_ratemaster',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='RateCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
