# Generated by Django 3.0.8 on 2024-04-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0276_m_ratemaster_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_SAPCustomerLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyCode', models.CharField(max_length=50)),
                ('DocumentNo', models.CharField(max_length=50)),
                ('FiscalYear', models.CharField(max_length=50)),
                ('DocumentType', models.CharField(max_length=50)),
                ('PostingDate', models.DateField()),
                ('DocumentDesc', models.CharField(max_length=100)),
                ('CustomerCode', models.CharField(max_length=50)),
                ('CustomerName', models.CharField(max_length=100)),
                ('DebitCredit', models.CharField(max_length=20)),
                ('Amount', models.IntegerField()),
                ('ItemText', models.CharField(max_length=300, null=True)),
                ('CreatedBy', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedBy', models.IntegerField()),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('FileDate', models.DateField()),
            ],
            options={
                'db_table': 'M_SAPCustomerLedger',
            },
        ),
        migrations.AddField(
            model_name='m_ratemaster',
            name='UnitID',
            field=models.IntegerField(default=False),
        ),
    ]
