# Generated by Django 3.0.8 on 2024-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0277_auto_20240422_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_stock',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
