# Generated by Django 3.0.8 on 2024-05-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0278_t_stock_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_ratemaster',
            name='Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RateParty', to='FoodERPApp.M_Parties'),
        ),
    ]
