# Generated by Django 3.0.8 on 2024-05-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0279_m_ratemaster_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_ratemaster',
            name='PriceList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='RatePriceList', to='FoodERPApp.M_PriceList'),
            preserve_default=False,
        ),
    ]
