# Generated by Django 3.0.8 on 2024-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0281_auto_20240509_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_employees',
            name='Designation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
