# Generated by Django 3.0.8 on 2024-05-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0282_m_employees_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_materialissue',
            name='Status',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='t_workorder',
            name='Status',
            field=models.IntegerField(default=False),
        ),
    ]
