# Generated by Django 3.0.8 on 2024-05-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0286_auto_20240529_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_invoices',
            name='DataRecovery',
        ),
        migrations.AlterField(
            model_name='t_production',
            name='Remark',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
