# Generated by Django 3.0.8 on 2024-05-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0288_auto_20240530_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_invoices',
            name='IsDataRecovery',
            field=models.BooleanField(default=False),
        ),
    ]
