# Generated by Django 3.0.8 on 2024-06-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0289_t_invoices_isdatarecovery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_invoices',
            name='IsDataRecovery',
        ),
    ]
