# Generated by Django 3.0.8 on 2024-06-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0290_remove_t_invoices_isdatarecovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_ChallanReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Demands', models.IntegerField()),
                ('Challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChallanReferences', to='FoodERPApp.T_Challan')),
            ],
            options={
                'db_table': 'TC_ChallanReferences',
            },
        ),
    ]
