# Generated by Django 3.0.8 on 2024-06-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0292_auto_20240611_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_productionmaterialissue',
            name='MaterialIssue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MaterialIssue', to='FoodERPApp.T_MaterialIssue'),
        ),
    ]
