# Generated by Django 3.0.8 on 2024-06-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0293_auto_20240613_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_itemunits',
            name='IsShowUnit',
            field=models.BooleanField(default=False),
        ),
    ]
