# Generated by Django 3.0.8 on 2024-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0294_mc_itemunits_isshowunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_itemgroupdetails',
            name='ItemSequence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
