# Generated by Django 3.0.8 on 2024-06-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0295_mc_itemgroupdetails_itemsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_itemgroupdetails',
            name='ItemSequence',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
