# Generated by Django 3.0.8 on 2024-06-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0296_auto_20240618_1036'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='m_items',
            constraint=models.UniqueConstraint(fields=('Company', 'SAPItemCode'), name='unique_company_sapitemcode'),
        ),
    ]
