# Generated by Django 3.0.8 on 2024-06-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0298_auto_20240624_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_group',
            name='Company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='ItemGroupCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
    ]
