# Generated by Django 3.0.8 on 2024-07-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0299_m_group_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='IsCBMItem',
            field=models.BooleanField(default=False),
        ),
    ]
