# Generated by Django 3.0.8 on 2024-07-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0300_m_items_iscbmitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_ItemSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemSupplier_Item', to='FoodERPApp.M_Items')),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemSupplier_Supplier', to='FoodERPApp.M_Parties')),
            ],
            options={
                'db_table': 'M_ItemSupplier',
            },
        ),
    ]
