# Generated by Django 3.0.8 on 2024-07-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0301_m_itemsupplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_itemsupplier',
            name='SupplierID',
        ),
    ]
