# Generated by Django 3.0.8 on 2024-07-30 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0302_remove_m_itemsupplier_supplierid'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_itemsupplier',
            name='SupplierID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ItemSupplier_Supplier', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
