# Generated by Django 3.0.8 on 2024-08-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0304_auto_20240801_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grns',
            name='InvoiceDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
