# Generated by Django 3.0.8 on 2024-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0305_t_grns_invoicedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='IsMixItem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_pages',
            name='IsSweetPOSPage',
            field=models.BooleanField(default=False),
        ),
    ]
