# Generated by Django 3.0.8 on 2024-08-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0306_auto_20240814_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_users',
            name='POSRateType',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
