# Generated by Django 3.0.8 on 2024-09-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0308_debug_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debug_log',
            old_name='created_at',
            new_name='CreatedOn',
        ),
    ]
