# Generated by Django 3.0.8 on 2024-09-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0309_auto_20240905_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='debug_log',
        ),
    ]
