# Generated by Django 3.0.8 on 2024-10-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0312_m_country'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='m_partytype',
            name='Country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
