# Generated by Django 3.0.8 on 2024-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0313_auto_20241004_1223'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='m_partytype',
            name='Country',
        ),
        
        migrations.AddField(
            model_name='m_partytype',
            name='CountryID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
