# Generated by Django 3.0.8 on 2024-10-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0314_auto_20241004_1237'),
    ]

    operations = [
       
        migrations.RenameField(
            model_name='m_partytype',
            old_name='CountryID',
            new_name='Country',
        ),
    ]
