# Generated by Django 3.0.8 on 2024-10-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0315_auto_20241004_1244'),
    ]

    operations = [
        
        migrations.RenameField(
            model_name='m_partytype',
            old_name='Country',
            new_name='CountryID',
        ),
    ]
