# Generated by Django 3.0.8 on 2024-10-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0316_auto_20241004_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_partytype',
            name='CountryID',
        ),
        migrations.AddField(
            model_name='m_partytype',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartyTypeCountry', to='FoodERPApp.M_Country'),
        ),
    ]
