# Generated by Django 3.0.8 on 2024-10-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0317_auto_20241007_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='Country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PartiesCountry', to='FoodERPApp.M_Country'),
        ),
    ]
