# Generated by Django 3.0.8 on 2024-11-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0319_m_country_istaxapplicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='AdvanceAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
