# Generated by Django 3.0.8 on 2024-11-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0320_t_orders_advanceamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_orders',
            name='DeliveryDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
