# Generated by Django 3.0.8 on 2024-11-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0322_m_mrpmaster_partytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_gsthsncode',
            name='PartyType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GSTMasterPartyType', to='FoodERPApp.M_PartyType'),
        ),
    ]
