# Generated by Django 3.0.8 on 2024-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0324_m_billofmaterial_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_users',
            name='IsLoginPermissions',
            field=models.BooleanField(default=False),
        ),
    ]
