# Generated by Django 3.0.8 on 2025-01-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0327_auto_20241226_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_billofmaterialitems',
            name='Quantity',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
