# Generated by Django 3.0.8 on 2025-01-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0329_auto_20250113_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_schemeparties',
            name='PartyID',
            field=models.IntegerField(),
        ),
    ]
