# Generated by Django 3.0.8 on 2025-01-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0330_auto_20250113_1820'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='m_schemeqrs',
            table='MC_SchemeQRs',
        ),
    ]
