# Generated by Django 3.0.8 on 2025-01-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0330_auto_20250115_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_GiftVoucherCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherCode', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=False)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('InvoiceDate', models.DateField()),
                ('InvoiceNumber', models.CharField(max_length=500)),
                ('InvoiceAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Party', models.IntegerField()),
                ('client', models.IntegerField()),
                ('VoucherType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GiftVoucherType', to='FoodERPApp.M_GeneralMaster')),
            ],
            options={
                'db_table': 'M_GiftVoucherCode',
            },
        ),
    ]
