# Generated by Django 3.0.8 on 2025-01-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0331_auto_20250113_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_schemetype',
            old_name='Usage',
            new_name='UsageTime',
        ),
        migrations.AddField(
            model_name='m_scheme',
            name='BillAbove',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='m_scheme',
            name='FreeItemID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='m_scheme',
            name='FromPeriod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='m_scheme',
            name='ToPeriod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='m_scheme',
            name='VoucherLimit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
