# Generated by Django 3.0.8 on 2025-01-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0331_m_giftvouchercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_giftvouchercode',
            name='InvoiceAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='m_giftvouchercode',
            name='InvoiceDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='m_giftvouchercode',
            name='InvoiceNumber',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
