# Generated by Django 3.0.8 on 2025-02-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0333_t_grns_issave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_grns',
            name='IsSave',
            field=models.IntegerField(),
        ),
    ]
