# Generated by Django 3.0.8 on 2025-02-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0335_tc_grnitems_discrepancycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_invoices',
            name='HideComment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
