# Generated by Django 3.0.8 on 2025-02-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0336_t_invoices_hidecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_SAPPOSUploadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadDate', models.DateTimeField(auto_now=True)),
                ('UploadBy', models.IntegerField()),
                ('Party', models.IntegerField()),
                ('FileID', models.IntegerField()),
                ('SaleDate', models.DateField()),
                ('UploadStatus', models.CharField(max_length=500)),
                ('Message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'M_SAPPOSUploadLog',
            },
        ),
    ]
