# Generated by Django 3.0.8 on 2025-02-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0338_auto_20250213_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='IsStockProcessItem',
            field=models.BooleanField(default=False),
        ),
    ]
