# Generated by Django 3.0.8 on 2025-02-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0339_m_items_isstockprocessitem'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='t_invoices',
            index=models.Index(fields=['InvoiceDate'], name='T_Invoices_Invoice_dae863_idx'),
        ),
        migrations.AddIndex(
            model_name='t_invoices',
            index=models.Index(fields=['InvoiceNumber'], name='T_Invoices_Invoice_4beb11_idx'),
        ),
        migrations.AddIndex(
            model_name='t_invoices',
            index=models.Index(fields=['CreatedBy'], name='T_Invoices_Created_9c0b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='t_invoices',
            index=models.Index(fields=['Customer'], name='T_Invoices_Custome_a11def_idx'),
        ),
        migrations.AddIndex(
            model_name='t_invoices',
            index=models.Index(fields=['Party'], name='T_Invoices_Party_i_1d5e41_idx'),
        ),
        migrations.AddIndex(
            model_name='t_invoices',
            index=models.Index(fields=['Party', 'InvoiceDate'], name='T_Invoices_Party_i_00f364_idx'),
        ),
        migrations.AddIndex(
            model_name='t_invoices',
            index=models.Index(fields=['Customer', 'InvoiceDate'], name='T_Invoices_Custome_f22154_idx'),
        ),
    ]
