# Generated by Django 3.0.8 on 2025-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0341_tc_grnitems_discrepancyreason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='m_partydetails',
            index=models.Index(fields=['Party', 'Group'], name='M_PartyDeta_Party_i_a2bbd4_idx'),
        ),
    ]
