# Generated by Django 3.0.8 on 2025-03-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0342_auto_20250303_1606'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mc_partyaddress',
            index=models.Index(fields=['Party', 'IsDefault'], name='MC_PartyAdd_Party_i_83f638_idx'),
        ),
    ]
