# Generated by Django 3.0.8 on 2025-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0343_auto_20250303_1624'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='m_parties',
            index=models.Index(fields=['PartyType', 'District', 'State'], name='M_Parties_PartyTy_4910ae_idx'),
        ),
        migrations.AddIndex(
            model_name='m_partytype',
            index=models.Index(fields=['IsRetailer'], name='M_PartyType_IsRetai_2a1fce_idx'),
        ),
        migrations.AddIndex(
            model_name='m_partytype',
            index=models.Index(fields=['IsFranchises'], name='M_PartyType_IsFranc_fd972c_idx'),
        ),
        migrations.AddIndex(
            model_name='mc_managementparties',
            index=models.Index(fields=['Employee', 'Party'], name='MC_Manageme_Employe_9a0cdc_idx'),
        ),
    ]
