# Generated by Django 3.0.8 on 2025-03-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0344_auto_20250304_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_roles',
            name='IdentifyKey',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
