# Generated by Django 3.0.8 on 2025-03-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0347_auto_20250313_1123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tc_grnreferences',
            unique_together=set(),
        ),
    ]
