# Generated by Django 3.0.8 on 2025-03-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0348_auto_20250319_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grns',
            name='IsTallySave',
            field=models.BooleanField(default=False),
        ),
    ]
