# Generated by Django 3.0.8 on 2025-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0349_t_grns_istallysave'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_scheme',
            name='SchemeValueUpto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='m_scheme',
            name='BillAbove',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='m_scheme',
            name='SchemeValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
