# Generated by Django 3.0.8 on 2025-03-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0351_t_invoices_istallysave'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_scheme',
            name='Column1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_scheme',
            name='Column2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='m_scheme',
            name='Column3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
