# Generated by Django 3.0.8 on 2025-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0352_auto_20250321_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_materialissue',
            name='NumberOfLot',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
