# Generated by Django 3.0.8 on 2025-03-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0353_auto_20250326_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_materialissue',
            name='RemainNumberOfLot',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
