# Generated by Django 3.0.8 on 2025-03-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0354_auto_20250326_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_production',
            name='NumberOfLot',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='t_workorder',
            name='NumberOfLot',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='t_workorder',
            name='RemainNumberOfLot',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
