# Generated by Django 3.0.8 on 2025-03-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0355_auto_20250327_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_invoices',
            name='IsSendToFTPSAP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_invoices',
            name='IsVDCChallan',
            field=models.BooleanField(default=False),
        ),
    ]
