# Generated by Django 3.0.8 on 2025-03-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0357_auto_20250329_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_invoices',
            name='IsVDCChallan',
        ),
        migrations.AddField(
            model_name='t_challan',
            name='IsVDCChallan',
            field=models.BooleanField(default=False),
        ),
    ]
