# Generated by Django 3.0.8 on 2025-03-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0358_auto_20250329_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_invoiceitems',
            name='TrayQuantity',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=30),
            preserve_default=False,
        ),
    ]
