# Generated by Django 3.0.8 on 2025-03-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0360_auto_20250330_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grns',
            name='IsGRNType',
            field=models.BooleanField(default=False),
        ),
    ]
