# Generated by Django 3.0.8 on 2025-03-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0361_t_grns_isgrntype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_grns',
            name='IsGRNType',
        ),
    ]
