# Generated by Django 3.0.8 on 2025-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0362_remove_t_grns_isgrntype'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_datewiselivestock',
            name='Production',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
