# Generated by Django 3.0.8 on 2025-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0363_o_datewiselivestock_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_giftvouchercode',
            name='ClientSaleID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
