# Generated by Django 3.0.8 on 2025-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0364_m_giftvouchercode_clientsaleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grns',
            name='IsGRNType',
            field=models.BooleanField(default=False),
        ),
    ]
