# Generated by Django 3.0.8 on 2025-04-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0365_t_grns_isgrntype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_partyprefixs',
            name='Productionprefix',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='t_production',
            name='FullProductionNumber',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_production',
            name='ProductionNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
