# Generated by Django 3.0.8 on 2025-04-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0368_auto_20250407_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_materialissue',
            name='IsDelete',
        ),
        migrations.RemoveField(
            model_name='t_production',
            name='IsDelete',
        ),
    ]
