# Generated by Django 3.0.8 on 2025-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0369_auto_20250408_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_materialissue',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_production',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
