# Generated by Django 3.0.8 on 2025-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0370_auto_20250408_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_datewiselivestock',
            name='MaterialIssue',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
