# Generated by Django 3.0.8 on 2025-04-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0372_m_pages_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_AccountGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'M_AccountGroupType',
            },
        ),
        migrations.CreateModel(
            name='M_Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('GST_Percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('HSN', models.CharField(max_length=50)),
                ('AccountGroupType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='FoodERPApp.M_AccountGroupType')),
            ],
            options={
                'db_table': 'M_Ledger',
            },
        ),
        migrations.CreateModel(
            name='T_Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullVoucherNumber', models.CharField(max_length=100)),
                ('VoucherNumber', models.CharField(max_length=50)),
                ('VoucherType', models.CharField(max_length=50)),
                ('VoucherDate', models.DateField()),
                ('GRN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='FoodERPApp.T_GRNs')),
            ],
            options={
                'db_table': 'T_Voucher',
            },
        ),
        migrations.CreateModel(
            name='TC_VoucherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrAmt', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('CrAmt', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('LedgerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_entries', to='FoodERPApp.M_Ledger')),
                ('Voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='FoodERPApp.T_Voucher')),
            ],
            options={
                'db_table': 'TC_VoucherDetails',
            },
        ),
    ]
