# Generated by Django 3.0.8 on 2025-04-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0374_t_voucher_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_voucher',
            name='GRN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Voucher_GRN', to='FoodERPApp.T_GRNs'),
        ),
        migrations.AlterField(
            model_name='t_voucher',
            name='Invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Voucher_Invoice', to='FoodERPApp.T_Invoices'),
        ),
    ]
