# Generated by Django 3.0.8 on 2025-04-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0376_t_voucher_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_voucher',
            name='DebitNote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Voucher_DebitNote', to='FoodERPApp.T_CreditDebitNotes'),
        ),
    ]
