# Generated by Django 3.0.8 on 2025-04-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0377_t_voucher_debitnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_ledger',
            name='GST_Percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='m_ledger',
            name='HSN',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
