# Generated by Django 3.0.8 on 2025-04-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0379_auto_20250416_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grns',
            name='TotalExpenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='TC_GRNExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasicAmount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('GSTPercentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('CGST', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SGST', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('GRN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExpensesGRN', to='FoodERPApp.T_GRNs')),
                ('Ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LedgerExpenses', to='FoodERPApp.M_Ledger')),
            ],
            options={
                'db_table': 'TC_GRNExpenses',
            },
        ),
    ]
