# Generated by Django 3.0.8 on 2025-04-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0380_auto_20250417_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='M_SchemeQRs',
            new_name='MC_SchemeQRs',
        ),
    ]
