# Generated by Django 3.0.8 on 2025-04-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0381_auto_20250417_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc_grnexpenses',
            name='Ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ledger_Expenses', to='FoodERPApp.M_Ledger'),
        ),
    ]
