# Generated by Django 3.0.8 on 2025-04-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0382_auto_20250417_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_grnexpenses',
            name='Ledger',
        ),
    ]
