# Generated by Django 3.0.8 on 2025-04-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0383_remove_tc_grnexpenses_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_grnexpenses',
            name='Ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Ledger_Expenses', to='FoodERPApp.M_Ledger'),
            preserve_default=False,
        ),
    ]
