# Generated by Django 3.0.8 on 2025-04-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0385_auto_20250417_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_roles',
            name='IdentifyKey',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
