# Generated by Django 3.0.8 on 2025-04-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0386_auto_20250418_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_grouptype',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ItemGroupTypeCompany', to='FoodERPApp.C_Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_grouptype',
            name='IsPos',
            field=models.BooleanField(default=False),
        ),
    ]
