# Generated by Django 3.0.8 on 2025-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0387_auto_20250419_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_deletedinvoices',
            name='IsTallySave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_grns',
            name='AccountingGRNStatus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_grns',
            name='RoundOffAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='m_giftvouchercode',
            index=models.Index(fields=['client', 'ClientSaleID'], name='M_GiftVouch_client_5bbd22_idx'),
        ),
    ]
