# Generated by Django 3.0.8 on 2025-04-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0388_auto_20250421_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_workorder',
            name='CommonID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
