# Generated by Django 3.0.8 on 2025-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0389_t_workorder_commonid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_billofmaterialitems',
            name='IsReprocess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_materialissue',
            name='IsReissue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_materialissue',
            name='IsReprocess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_workorder',
            name='IsReprocess',
            field=models.BooleanField(default=False),
        ),
    ]
