# Generated by Django 3.0.8 on 2025-05-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0390_auto_20250505_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_scheme',
            name='Column1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='m_scheme',
            name='Column2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='m_scheme',
            name='Column3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
