# Generated by Django 3.0.8 on 2025-05-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0391_auto_20250520_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_CronJobSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('Settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodERPApp.M_Settings')),
            ],
            options={
                'db_table': 'MC_CronJobSettings',
            },
        ),
    ]
