# Generated by Django 3.0.8 on 2025-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0392_mc_cronjobsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mc_cronjobsettings',
            name='URL',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
