# Generated by Django 3.0.8 on 2025-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0393_auto_20250527_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='IsThirdPartyItem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='t_orders',
            name='DeliveryDate',
            field=models.DateTimeField(),
        ),
    ]
