# Generated by Django 3.0.8 on 2025-05-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0394_auto_20250529_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='ClosingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
