# Generated by Django 3.0.8 on 2025-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0396_auto_20250531_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_invoices',
            name='CustomerGSTIN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
