# Generated by Django 3.0.8 on 2025-06-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0397_t_invoices_customergstin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='m_giftvouchercode',
            index=models.Index(fields=['Party', 'InvoiceDate', 'InvoiceNumber'], name='M_GiftVouch_Party_a68728_idx'),
        ),
        migrations.AddIndex(
            model_name='m_giftvouchercode',
            index=models.Index(fields=['Party', 'InvoiceDate', 'InvoiceNumber', 'client', 'ClientSaleID'], name='M_GiftVouch_Party_1984b4_idx'),
        ),
    ]
