# Generated by Django 3.0.8 on 2025-06-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0398_auto_20250604_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC_SchemePartie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchemeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SchemeIDForPartie', to='FoodERPApp.M_Scheme')),
            ],
            options={
                'db_table': 'MC_SchemePartie',
            },
        ),
    ]
