# Generated by Django 3.0.8 on 2025-06-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0399_mc_schemepartie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_schemepartie',
            name='PartyID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='PartyIDForScheme', to='FoodERPApp.M_Parties'),
            preserve_default=False,
        ),
    ]
