# Generated by Django 3.0.8 on 2025-06-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0400_mc_schemepartie_partyid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MC_SchemeParties',
        ),
    ]
