# Generated by Django 3.0.8 on 2025-06-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0401_delete_mc_schemeparties'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MC_SchemePartie',
            new_name='MC_SchemeParties',
        ),
        migrations.AlterModelTable(
            name='mc_schemeparties',
            table='MC_SchemeParties',
        ),
    ]
