# Generated by Django 3.0.8 on 2025-06-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0402_auto_20250605_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_scheme',
            name='ShortName',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
