# Generated by Django 3.0.8 on 2025-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0403_m_scheme_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_scheme',
            name='SchemeName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='m_scheme',
            name='ShortName',
            field=models.CharField(max_length=200),
        ),
    ]
