# Generated by Django 3.0.8 on 2025-06-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0404_auto_20250611_1330'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='m_giftvouchercode',
            index=models.Index(fields=['Party', 'InvoiceDate', 'VoucherCode'], name='M_GiftVouch_Party_27a26a_idx'),
        ),
    ]
