# Generated by Django 3.0.8 on 2025-06-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0405_auto_20250612_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_giftvouchercode',
            name='Scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='GiftVoucherSchemeID', to='FoodERPApp.M_Scheme'),
            preserve_default=False,
        ),
    ]
