# Generated by Django 3.0.8 on 2025-06-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0406_m_giftvouchercode_scheme'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='m_giftvouchercode',
            constraint=models.UniqueConstraint(fields=('VoucherCode', 'Scheme'), name='unique_vouchercode_scheme'),
        ),
    ]
