# Generated by Django 3.0.8 on 2025-06-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0408_mc_partyaddress_fssaidocumenturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_sapcustomerledger',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
