# Generated by Django 3.0.8 on 2025-06-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0409_auto_20250625_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_orders',
            name='IsOrderClose',
            field=models.BooleanField(default=False),
        ),
    ]
