# Generated by Django 3.0.8 on 2025-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0410_t_orders_isorderclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_scheme',
            name='SchemeQuantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
