# Generated by Django 3.0.8 on 2025-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0411_m_scheme_schemequantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_ratemaster',
            name='Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tc_grnitems',
            name='ReferenceRate',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
    ]
