# Generated by Django 3.0.8 on 2025-07-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0412_auto_20250630_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_grns',
            name='PostingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
