# Generated by Django 3.0.8 on 2025-07-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0413_t_grns_postingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_livebatches',
            name='Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
