# Generated by Django 3.0.8 on 2025-07-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0415_auto_20250703_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_parties',
            name='IsSEZ',
            field=models.BooleanField(default=False),
        ),
    ]
