# Generated by Django 3.0.8 on 2025-07-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0416_m_parties_issez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_scheme',
            name='QRPrefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
