# Generated by Django 3.0.8 on 2025-07-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0417_auto_20250721_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_purchasereturn',
            name='Vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnVehicle', to='FoodERPApp.M_Vehicles'),
        ),
    ]
