# Generated by Django 3.0.8 on 2025-07-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0418_t_purchasereturn_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_PurchaseReturnUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EwayBillNo', models.CharField(max_length=500, null=True)),
                ('EwayBillUrl', models.CharField(max_length=500, null=True)),
                ('EwayBillCreatedBy', models.IntegerField(null=True)),
                ('EwayBillCreatedOn', models.DateTimeField(null=True)),
                ('EwayBillCanceledBy', models.IntegerField(null=True)),
                ('EwayBillCanceledOn', models.DateTimeField(null=True)),
                ('EwayBillIsCancel', models.BooleanField(default=False)),
                ('PurchaseReturn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseReturnUploads', to='FoodERPApp.T_PurchaseReturn')),
            ],
            options={
                'db_table': 'TC_PurchaseReturnUploads',
            },
        ),
    ]
