# Generated by Django 3.0.8 on 2025-07-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodERPApp', '0419_tc_purchasereturnuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='tc_purchasereturnuploads',
            name='user_gstin',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
